import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import {createHash} from 'node:crypto';import {createArchiveLauncher,parseArchiveList} from '../src/features/converter/archive-runtime.mjs';import {rarFixture,sevenFixture} from './converter-archive-fixtures.mjs';
const root=process.env.CONVERTER_ARCHIVE_TEST_ROOT;const executable=path.resolve('src/features/converter/native/bin/Release/net8.0-windows/ConverterSandbox.exe');const hash=async p=>createHash('sha256').update(await fs.readFile(p)).digest('hex');
// The complete runtime digest is fixed to the reviewed publisher package.
const dllHash='899cd73d7fc60e1c1c35c7de0f5bed3dc69bfe2cecbd48014d868a347970a0b1';
async function verifiedRuntime(){const companions={};for(const suffix of ['.dll','.deps.json','.runtimeconfig.json']){const p=executable.slice(0,-4)+suffix;companions[path.basename(p)]=await hash(p);}return createArchiveLauncher({launcherPath:executable,launcherSha256:await hash(executable),launcherCompanionHashes:companions,sevenZipPath:path.join(root,'7z.exe'),sevenZipSha256:'95fff19b73eff77c87c0d7bd32822e43fb90dd2932459f962eb532d8dfb6ba53',sevenZipDllPath:path.join(root,'7z.dll'),sevenZipDllSha256:dllHash});}
test('archive index rejects unsafe names, links, encryption and bombs',()=>{for(const body of ['Path = ../escape\nSize = 1','Path = under_score\nSize = 1','Path = a\nSize = 1\nEncrypted = +','Path = a\nSize = 1\nSymbolic Link = x','Path = a\nSize = 999999999'])assert.throws(()=>parseArchiveList(Buffer.from(body)));});
test('real AppContainer lists and extracts stored 7z and RAR fixtures',{skip:!root||process.platform!=='win32'},async()=>{const launcher=await verifiedRuntime();for(const [format,input]of [['7z',sevenFixture()],['rar',rarFixture()]]){const listed=await launcher.launch({adapterId:format+'-list',inputs:[input]}).result;assert.equal(JSON.parse(listed.outputs[0].bytes)[0].name,'hello.txt');const result=await launcher.launch({adapterId:format+'-extract',inputs:[input]}).result;assert.equal(result.outputs[0].name,'hello.txt');assert.equal(result.outputs[0].bytes.toString(),'hello');}});
test('real AppContainer rejects traversal and corrupted archive content',{skip:!root||process.platform!=='win32'},async()=>{const launcher=await verifiedRuntime();for(const input of [rarFixture('../escape'),rarFixture('under_score')])await assert.rejects(launcher.launch({adapterId:'rar-extract',inputs:[input]}).result);const bad=rarFixture();bad[bad.length-8]^=1;await assert.rejects(launcher.launch({adapterId:'rar-extract',inputs:[bad]}).result);});

test('archive cancellation stops before publishing outputs',{skip:!root||process.platform!=='win32'},async()=>{const launcher=await verifiedRuntime();const worker=launcher.launch({adapterId:'7z-extract',inputs:[sevenFixture()]});await worker.terminate();await assert.rejects(worker.result,/Cancelled|cancelled|timed out/);});
test('official compressed 7z package is listed and extracted without executing contents',{skip:!root||process.platform!=='win32'},async()=>{const p=path.join(root,'..','7z2604-extra.7z');const bytes=await fs.readFile(p);assert.equal(createHash('sha256').update(bytes).digest('hex'),'dc4b11d3399db18b063630137145f5585d8f7ac847bf3639bd1185d7d1f7cee0');const launcher=await verifiedRuntime();const result=await launcher.launch({adapterId:'7z-extract',inputs:[bytes]}).result;assert.ok(result.outputs.length>2);assert.ok(result.outputs.some(o=>o.name.endsWith('7za.exe')&&o.bytes.length>10000));});

test('main sandbox provider enables archive catalog proof after real startup',{skip:!root||process.platform!=='win32'},async()=>{const {createWindowsSandboxProvider}=await import('../src/features/converter/windows-sandbox.mjs');const companions={};for(const suffix of ['.dll','.deps.json','.runtimeconfig.json']){const p=executable.slice(0,-4)+suffix;companions[path.basename(p)]=await hash(p);}const provider=await createWindowsSandboxProvider({launcherPath:executable,launcherSha256:await hash(executable),launcherCompanionHashes:companions,runtimePath:process.execPath,runtimeSha256:await hash(process.execPath),archiveRuntime:{sevenZipPath:path.join(root,'7z.exe'),sevenZipSha256:'95fff19b73eff77c87c0d7bd32822e43fb90dd2932459f962eb532d8dfb6ba53',sevenZipDllPath:path.join(root,'7z.dll'),sevenZipDllSha256:dllHash}});assert.equal(provider.verifiedArchiveRuntime,true);const result=await provider.launch({adapterId:'rar-extract',inputs:[rarFixture()]}).result;assert.equal(result.outputs[0].bytes.toString(),'hello');});
