import test from 'node:test';import assert from 'node:assert/strict';import {safeConverterDiagnostic,createWindowsSandboxProvider} from '../src/features/converter/windows-sandbox.mjs';
test('converter diagnostics never contain exception text, paths or untrusted fields',()=>{const error=Object.assign(new Error('private filename and input contents'),{code:'ENOENT',converterPhase:'media-probe',name:'PrivateClass',input:'secret',path:'private'});assert.deepEqual(safeConverterDiagnostic(error,'media'),{schema:1,component:'media',phase:'media-probe',code:'ENOENT',errorName:'Error'});assert.ok(!JSON.stringify(safeConverterDiagnostic(error,'unknown')).includes('private'));});
test('provider failure retains original exception and emits a safe diagnostic',{skip:process.platform!=='win32'},async()=>{const diagnostics=[];await assert.rejects(createWindowsSandboxProvider({launcherPath:'Z:/not-a-component/launcher.exe',launcherSha256:'0'.repeat(64),runtimePath:'Z:/not-a-component/node.exe',runtimeSha256:'0'.repeat(64),onDiagnostic:d=>diagnostics.push(d)}),error=>{assert.equal(error.converterDiagnostic.component,'provider');return true;});assert.equal(diagnostics.length,1);assert.equal(diagnostics[0].code,'ENOENT');assert.ok(!JSON.stringify(diagnostics).includes('not-a-component'));});

import {validateNativeReceipt} from '../src/features/converter/windows-sandbox.mjs';
const nonce='a'.repeat(64);
const receipt={schema:1,nonce,isolated:true,exitCode:0,timedOut:false,cancelled:false,killedForStorage:false,profileDeleted:true,networkCapabilities:0,activeProcessLimit:1,memoryBytes:268435456,timeoutMs:30000,appContainerVerified:true,capabilityCount:0,jobLimitsVerified:true};
test('validated native failure exposes only bounded numeric codes',()=>{assert.throws(()=>validateNativeReceipt(JSON.stringify({schema:1,nonce,isolated:false,nativeError:5,hresult:-2147024891,error:'private message',path:'private path'}),nonce,1),error=>{assert.deepEqual(safeConverterDiagnostic(error),{schema:1,component:'provider',phase:'provider-native',code:'NATIVE_EXIT_FAILED',errorName:'Error',launcherExitCode:1,nativeError:5,nativeHresult:-2147024891});return true;});});
test('invalid receipt identity never exposes supplied numeric diagnostics',()=>{assert.throws(()=>validateNativeReceipt(JSON.stringify({...receipt,nonce:'wrong',nativeError:5}),nonce,1),error=>{const result=safeConverterDiagnostic(error);assert.equal(result.phase,'provider-receipt');assert.equal(result.code,'RECEIPT_INVALID');assert.equal(result.nativeError,undefined);return true;});});
test('native success still requires complete isolation proof',()=>{assert.equal(validateNativeReceipt(JSON.stringify(receipt),nonce,0).isolated,true);for(const altered of [{networkCapabilities:1},{cancelled:true},{jobLimitsVerified:false},{killedForStorage:true}])assert.throws(()=>validateNativeReceipt(JSON.stringify({...receipt,...altered}),nonce,0),/RECEIPT_INVALID/);});
