import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {createFeatureServices} from '../src/main/feature-services.js';
const dataUrl='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR4nGNgYGBgAAAABQABpfZFQAAAAABJRU5ErkJggg==';
const safeStorage={isEncryptionAvailable:()=>true,encryptString:s=>Buffer.from(s),decryptString:b=>b.toString()};
async function setup(t,extra={}){const directory=await fs.mkdtemp(path.join(os.tmpdir(),'converter-diagnostic-')),diagnostics=[];const service=createFeatureServices({dataDirectory:directory,applicationRoot:directory,safeStorage,dialog:{},getWindow:()=>null,openPath:async()=>'',onConverterDiagnostic:d=>diagnostics.push(d),...extra});t.after(async()=>{await service.close();await fs.rm(directory,{recursive:true,force:true});});return{service,directory,diagnostics};}
test('image failure always identifies absent provider and missing directory',async t=>{const {service,diagnostics}=await setup(t);await assert.rejects(service.request('personalization','normalizeImage',{dataUrl}),/provider\/configuration\/MISSING_SANDBOX_DIRECTORY/);assert.equal(diagnostics[0].code,'MISSING_SANDBOX_DIRECTORY');});
test('image failure identifies missing operating system proof',async t=>{const {service}=await setup(t,{sandboxProvider:{verifiedOsIsolation:false}});await assert.rejects(service.request('personalization','normalizeImage',{dataUrl}),/provider\/proof\/OS_ISOLATION_UNVERIFIED/);});
test('image failure identifies missing media proof',async t=>{const {service}=await setup(t,{sandboxProvider:{verifiedOsIsolation:true,launch(){}}});await assert.rejects(service.request('personalization','normalizeImage',{dataUrl}),/media\/proof\/MEDIA_RUNTIME_UNVERIFIED/);});
test('manifest read catches emit sanitized media and archive diagnostics',async t=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'converter-manifest-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));await fs.writeFile(path.join(dir,'manifest.json'),JSON.stringify({launcherSha256:'0'.repeat(64),runtimeSha256:'0'.repeat(64)}));const {service,diagnostics}=await setup(t,{sandboxDirectory:dir});await assert.rejects(service.request('personalization','normalizeImage',{dataUrl}),/provider\//);assert.ok(diagnostics.some(d=>d.component==='media'&&d.phase==='manifest'&&d.code==='ENOENT'));assert.ok(diagnostics.some(d=>d.component==='archive'&&d.phase==='manifest'&&d.code==='ENOENT'));assert.ok(!JSON.stringify(diagnostics).includes(dir));for(const d of diagnostics)assert.deepEqual(Object.keys(d).sort(),['code','component','errorName','phase','schema']);});

import {sanitizeConverterDiagnostic} from '../src/main/feature-services.js';
test('factory preserves bounded native diagnostics and excludes raw error material',()=>{const result=sanitizeConverterDiagnostic({component:'provider',phase:'provider-native',code:'NATIVE_EXIT_FAILED',errorName:'Error',launcherExitCode:1,workerExitCode:4294967295,nativeError:5,nativeHresult:-2147024891,message:'private filename',path:'private path',input:'private data'});assert.deepEqual(result,{schema:1,component:'provider',phase:'provider-native',code:'NATIVE_EXIT_FAILED',errorName:'Error',launcherExitCode:1,workerExitCode:4294967295,nativeError:5,nativeHresult:-2147024891});assert.ok(!JSON.stringify(result).includes('private'));const invalid=sanitizeConverterDiagnostic({launcherExitCode:Infinity,workerExitCode:4294967296,nativeError:-2147483649,nativeHresult:'5'});for(const key of ['launcherExitCode','workerExitCode','nativeError','nativeHresult'])assert.equal(invalid[key],undefined);});
