import test from 'node:test';import assert from 'node:assert/strict';import {convertTable,readTableXml} from '../src/features/converter/table.mjs';import {readZip,writeZip} from '../src/features/converter/archive.mjs';import {detectFormat,catalog} from '../src/features/converter/registry.mjs';
const table=[['name','value','text'],['café','00012','a  b\t中文\n<&>'],['blank','','😀']];
const json=Buffer.from(JSON.stringify(table));
for(const format of ['xlsx','ods'])test(format+' round trip preserves string cells and detector',()=>{const made=convertTable('json-to-'+format,[json]).outputs[0].bytes;assert.equal(detectFormat(made),format);assert.deepEqual(JSON.parse(convertTable(format+'-to-json',[made]).outputs[0].bytes),table);const other=format==='xlsx'?'ods':'xlsx';assert.deepEqual(JSON.parse(convertTable(other+'-to-json',[convertTable(format+'-to-'+other,[made]).outputs[0].bytes]).outputs[0].bytes),table);});
test('table CSV quotes and delimiter controls remain active',()=>{const x=convertTable('csv-to-xlsx',[Buffer.from('one;"two;three"')],{delimiter:';'}).outputs[0].bytes;assert.equal(Buffer.from(convertTable('xlsx-to-csv',[x],{delimiter:';'}).outputs[0].bytes).toString(),'one;"two;three"');});
test('XML rejects DTD, undefined entities, duplicate attrs, excessive depth',()=>{for(const xml of ['<!DOCTYPE x><x/>','<x>&unknown;</x>','<x a="&bad"/>','<x a="1" a="2"/>','<x>'.repeat(34)+'</x>'.repeat(34)])assert.throws(()=>readTableXml(Buffer.from(xml)));});
test('formula text requires chosen handling and formulas are never calculated',()=>{const input=Buffer.from('[["=1+1"]]');assert.throws(()=>convertTable('json-to-xlsx',[input]),/Formula-like/);const x=convertTable('json-to-xlsx',[input],{formulaPolicy:'escape'}).outputs[0].bytes;assert.deepEqual(JSON.parse(convertTable('xlsx-to-json',[x]).outputs[0].bytes),[["'=1+1"]]);});
test('XLSX formula cells, external links, multiple sheets and huge refs are rejected',()=>{const made=convertTable('json-to-xlsx',[Buffer.from('[["x"]]')]).outputs[0].bytes;for(const mutate of [entries=>{entries.find(e=>e.name.endsWith('sheet1.xml')).bytes=Buffer.from('<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData><row><c r="A1"><f>1+1</f><v>2</v></c></row></sheetData></worksheet>');},entries=>{const e=entries.find(e=>e.name.endsWith('workbook.xml.rels'));e.bytes=Buffer.from(e.bytes.toString().replace('Target="','TargetMode="External" Target="'));},entries=>{const e=entries.find(e=>e.name==='xl/workbook.xml');e.bytes=Buffer.from(e.bytes.toString().replace('</sheets>','<sheet name="two" sheetId="2" r:id="r1"/></sheets>'));},entries=>{const e=entries.find(e=>e.name.endsWith('sheet1.xml'));e.bytes=Buffer.from(e.bytes.toString().replace('A1','A999999'));}]){const entries=readZip(made);mutate(entries);assert.throws(()=>convertTable('xlsx-to-json',[writeZip(entries)]));}});
test('ODS formula and repeat bombs rejected',()=>{const made=convertTable('json-to-ods',[Buffer.from('[["x"]]')]).outputs[0].bytes;for(const attribute of ['table:formula="of:=1+1"','table:number-columns-repeated="999999"']){const entries=readZip(made),e=entries.find(e=>e.name==='content.xml');e.bytes=Buffer.from(e.bytes.toString().replace('<table:table-cell ','<table:table-cell '+attribute+' '));assert.throws(()=>convertTable('ods-to-json',[writeZip(entries)]));}});
test('all workbook routes are actionable catalog entries',()=>assert.equal(catalog().filter(e=>/^(xlsx|ods)-to-|^(csv|tsv|json)-to-(xlsx|ods)$/.test(e.id)&&e.enabled).length,14));

test('sparse cell references preserve blank rows and columns',()=>{const entries=readZip(convertTable('json-to-xlsx',[Buffer.from('[["x"]]')]).outputs[0].bytes);const cell=entries.find(e=>e.name.endsWith('sheet1.xml'));cell.bytes=Buffer.from(cell.bytes.toString().replace('A1','B3'));assert.deepEqual(JSON.parse(convertTable('xlsx-to-json',[writeZip(entries)]).outputs[0].bytes),[['',''],['',''],['','x']]);});
