import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import os from 'node:os';
import {validateMinimalRuntime,prepareMinimalComponent} from '../scripts/converter-minimal-component.mjs';
test('component downloader rejects untrusted or mutable URL forms before fetching',async()=>{await assert.rejects(prepareMinimalComponent('http://github.com/a/b/releases/download/v/ffmpeg-9.0.2-minimal-v1-win64.zip','unused'),/immutable/);await assert.rejects(prepareMinimalComponent('https://example.com/releases/download/v/ffmpeg-9.0.2-minimal-v1-win64.zip','unused'),/immutable/);});
test('component verifies every packaged file and rejects tampering',{skip:!process.env.CONVERTER_COMPONENT_TEST_ROOT},async t=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'converter-component-test-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));await fs.cp(process.env.CONVERTER_COMPONENT_TEST_ROOT,dir,{recursive:true});const config=await validateMinimalRuntime(dir);assert.equal(config.profile,'minimal-v1');await fs.appendFile(path.join(dir,'README.txt'),'changed');await assert.rejects(validateMinimalRuntime(dir),/hash mismatch/);});

import {assertUnlinkedPath,validateArchiveEntries,publishMinimalRuntime,runBounded} from '../scripts/converter-minimal-component.mjs';
const assetRoot=process.env.CONVERTER_COMPONENT_TEST_ROOT;
test('linked destination ancestors are rejected',async t=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'converter-link-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));await fs.mkdir(path.join(dir,'real'));await fs.symlink(path.join(dir,'real'),path.join(dir,'linked'),process.platform==='win32'?'junction':'dir');await assert.rejects(assertUnlinkedPath(path.join(dir,'linked','child')),/Linked|subprocess/);});
test('existing invalid destination is preserved before download',async t=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'converter-existing-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));await fs.writeFile(path.join(dir,'keep.txt'),'original');await assert.rejects(prepareMinimalComponent('https://github.com/example/example/releases/download/v/ffmpeg-9.0.2-minimal-v1-win64.zip',dir),/Unexpected/);assert.equal(await fs.readFile(path.join(dir,'keep.txt'),'utf8'),'original');});
test('bounded subprocess terminates on deadline',async()=>{await assert.rejects(runBounded(process.execPath,['-e','setInterval(()=>{},1000)'],{timeoutMs:30}),/timed out/);});
test('frozen ZIP member inventory rejects changed names and links',{skip:!assetRoot},async()=>{const archive=await fs.readFile(path.join(assetRoot,'..','ffmpeg-9.0.2-minimal-v1-win64.zip'));assert.equal(validateArchiveEntries(archive),true);const changed=Buffer.from(archive);const offset=changed.indexOf(Buffer.from('./README.txt'));changed.write('../evil.txt ',offset);assert.throws(()=>validateArchiveEntries(changed),/member/);const linked=Buffer.from(archive);let i=linked.indexOf(Buffer.from([0x50,0x4b,0x01,0x02]));linked.writeUInt32LE(0xa0000000,i+38);assert.throws(()=>validateArchiveEntries(linked),/Unsafe/);});
test('copy failure leaves destination absent and removes partial stage',{skip:!assetRoot},async t=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'converter-copy-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));let count=0;const failure=new Error('injected copy failure');await assert.rejects(publishMinimalRuntime(assetRoot,path.join(dir,'new'),{copyFile:async(...args)=>{if(++count===2)throw failure;await fs.copyFile(...args);}}),error=>error===failure);assert.deepEqual(await fs.readdir(dir),[]);});
test('publication never replaces an existing directory',{skip:!assetRoot},async t=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'converter-publish-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));await fs.writeFile(path.join(dir,'keep'),'original');await assert.rejects(publishMinimalRuntime(assetRoot,dir),/must not be overwritten/);assert.equal(await fs.readFile(path.join(dir,'keep'),'utf8'),'original');});

test('validated stage publishes complete component into absent destination',{skip:!assetRoot},async t=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'converter-atomic-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));const destination=path.join(dir,'runtime');const config=await publishMinimalRuntime(assetRoot,destination);assert.equal(config.profile,'minimal-v1');assert.deepEqual(await fs.readdir(dir),['runtime']);await validateMinimalRuntime(destination);});

test('bounded subprocess failure includes only safe stage and exit status',async()=>{await assert.rejects(runBounded(process.execPath,['-e','process.stderr.write("sensitive fixture output");process.exit(23)'],{stage:'archive-package-extract'}),error=>{assert.equal(error.stage,'archive-package-extract');assert.equal(error.exitCode,23);assert.equal(error.code,'SUBPROCESS_FAILED');assert.ok(!error.message.includes('sensitive'));assert.ok(!error.message.includes(process.execPath));return true;});});
