import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
import {createRestrictedProcess} from '../src/features/converter/sandbox.mjs';
import {createConverterService} from '../src/features/converter/service.mjs';
async function fixture(t){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'converter-'));t.after(async()=>{await service.close();await fs.rm(dir,{recursive:true,force:true});});const source=path.join(dir,'input.json'),dest=path.join(dir,'output.json');await fs.writeFile(source,'{"a":1}');const grants={source,dest};const service=createConverterService({stateDirectory:path.join(dir,'state'),sandboxProvider:{verifiedOsIsolation:true,launch:createRestrictedProcess},resolveGrant:async id=>{if(!grants[id])throw new Error('Invalid grant.');return grants[id];}});return{service,source,dest,dir};}
async function terminal(service,id){for(let i=0;i<100;i++){const r=(await service.list()).find(r=>r.id===id);if(['completed','failed','cancelled'].includes(r.state))return r;await new Promise(r=>setTimeout(r,20));}throw new Error('Timed out');}
test('queue converts atomically and retains source bytes',async t=>{const {service,source,dest}=await fixture(t);const r=await service.enqueue({sourceIds:['source'],destinationId:'dest',adapterId:'json-format'});assert.equal((await terminal(service,r.id)).state,'completed');assert.deepEqual(JSON.parse(await fs.readFile(dest)),{a:1});assert.equal(await fs.readFile(source,'utf8'),'{"a":1}');});
test('ungranted paths, missing proof, and overwrite are rejected',async t=>{const {service,dest}=await fixture(t);await assert.rejects(service.inspect({sourceIds:['C:/arbitrary']}));await assert.rejects(service.enqueue({sourceIds:['source'],destinationId:'dest',adapterId:'pdf-merge'}),/verification/);await fs.writeFile(dest,'keep');await assert.rejects(service.enqueue({sourceIds:['source'],destinationId:'dest',adapterId:'json-format'}),/overwrite/);assert.equal(await fs.readFile(dest,'utf8'),'keep');});
test('pagination rejects unbounded requests and recovery pauses interrupted work',async t=>{const {service,dir}=await fixture(t);await assert.rejects(service.list({limit:100000}));const id='00000000-0000-0000-0000-000000000001';await fs.mkdir(path.join(dir,'state'),{recursive:true});await fs.writeFile(path.join(dir,'state',id+'.json'),JSON.stringify({id,state:'running',progress:20,adapterId:'json-format'}));await service.run();assert.equal((await service.list())[0].state,'paused');});


test('production catalog disables execution without verified OS isolation',async t=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'converter-disabled-'));t.after(async()=>{await service.close();await fs.rm(dir,{recursive:true,force:true});});const service=createConverterService({stateDirectory:dir,resolveGrant:async()=>{throw new Error('No grant');},bundledProof:{pdfLib:true}});assert.ok(service.catalog().every(row=>!row.enabled));await assert.rejects(service.enqueue({adapterId:'hex'}),/isolation/);});

test('cancel during source revalidation cannot become running or completed',async t=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'converter-cancel-'));t.after(async()=>{await service.close();await fs.rm(dir,{recursive:true,force:true});});const source=path.join(dir,'source.txt'),dest=path.join(dir,'out.txt');await fs.writeFile(source,'safe');let reads=0,release,enteredResolve;const entered=new Promise(r=>enteredResolve=r),blocked=new Promise(r=>release=r);const service=createConverterService({stateDirectory:path.join(dir,'state'),sandboxProvider:{verifiedOsIsolation:true,launch(){throw new Error('Cancelled work must not launch.');}},resolveGrant:async(id)=>{if(id==='source'&&++reads===3){enteredResolve();await blocked;}return id==='source'?source:dest;}});const item=await service.enqueue({sourceIds:['source'],destinationId:'dest',adapterId:'hex'});await entered;await service.control({id:item.id,action:'cancel'});release();await new Promise(r=>setTimeout(r,50));assert.equal((await service.list())[0].state,'cancelled');await assert.rejects(fs.stat(dest),{code:'ENOENT'});});

test('split preflights every granted-folder output before publishing any',async t=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'converter-split-'));t.after(async()=>{await service.close();await fs.rm(dir,{recursive:true,force:true});});const source=path.join(dir,'source.pdf');await fs.writeFile(source,'%PDF-test');await fs.writeFile(path.join(dir,'page-2.pdf'),'keep');const service=createConverterService({stateDirectory:path.join(dir,'state'),bundledProof:{pdfLib:true},sandboxProvider:{verifiedOsIsolation:true,launch:()=>({terminate:async()=>{},result:Promise.resolve({outputs:[{name:'page-1.pdf',bytes:Buffer.from('one')},{name:'page-2.pdf',bytes:Buffer.from('two')}],details:{}})})},resolveGrant:async(id,mode)=>{if(id==='source'&&mode==='read')return source;if(id==='folder'&&mode==='directory')return dir;throw new Error('Invalid grant');}});const item=await service.enqueue({sourceIds:['source'],destinationDirectoryId:'folder',adapterId:'pdf-split',lossyConfirmed:true});assert.equal((await terminal(service,item.id)).state,'failed');await assert.rejects(fs.stat(path.join(dir,'page-1.pdf')),{code:'ENOENT'});assert.equal(await fs.readFile(path.join(dir,'page-2.pdf'),'utf8'),'keep');});


test('quit inventory streams beyond one page and preserves paused records',async t=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'converter-quit-'));const service=createConverterService({stateDirectory:dir,resolveGrant:async()=>{throw new Error('No grant');}});t.after(async()=>{await service.close();await fs.rm(dir,{recursive:true,force:true});});for(let i=0;i<62;i++){const id='00000000-0000-0000-0000-'+String(i).padStart(12,'0');await fs.writeFile(path.join(dir,id+'.json'),JSON.stringify({id,state:i<60?'queued':'paused',adapterId:'hex'}));}assert.equal(await service.pending(),60);assert.deepEqual(await service.cancelAll(),{cancelled:60,remaining:0});const paused=[];for(let offset=0;offset<62;offset+=50)paused.push(...(await service.list({offset,limit:50})).filter(x=>x.state==='paused'));assert.equal(paused.length,2);});

test('cancelAll waits for worker settlement before returning',async t=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'converter-quit-worker-')),source=path.join(dir,'input.txt'),dest=path.join(dir,'out.txt');await fs.writeFile(source,'data');let launched,settled=false;const started=new Promise(resolve=>launched=resolve);let rejectWorker;const service=createConverterService({stateDirectory:path.join(dir,'state'),resolveGrant:async id=>id==='source'?source:dest,sandboxProvider:{verifiedOsIsolation:true,launch:()=>{launched();return {result:new Promise((_,reject)=>rejectWorker=reject),terminate:()=>new Promise(resolve=>setTimeout(()=>{settled=true;rejectWorker(new Error('Cancelled'));resolve();},30))};}}});t.after(async()=>{await service.close();await fs.rm(dir,{recursive:true,force:true});});await service.enqueue({sourceIds:['source'],destinationId:'dest',adapterId:'hex'});await started;const result=await service.cancelAll();assert.equal(settled,true);assert.equal(result.remaining,0);assert.equal((await service.list())[0].state,'cancelled');await assert.rejects(fs.stat(dest),{code:'ENOENT'});});

test('cancelAll invalidates an admission still reading its source',async t=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'converter-admission-')),source=path.join(dir,'in.txt'),dest=path.join(dir,'out.txt');await fs.writeFile(source,'data');let release,notify;const blocked=new Promise(resolve=>release=resolve),entered=new Promise(resolve=>notify=resolve);const service=createConverterService({stateDirectory:path.join(dir,'state'),sandboxProvider:{verifiedOsIsolation:true,launch(){throw new Error('Admission should have been cancelled.');}},resolveGrant:async id=>{if(id==='source'){notify();await blocked;return source;}return dest;}});t.after(async()=>{await service.close();await fs.rm(dir,{recursive:true,force:true});});const admission=service.enqueue({sourceIds:['source'],destinationId:'dest',adapterId:'hex'});await entered;const rejection=assert.rejects(admission,/stopped before/);const stopping=service.cancelAll();release();assert.deepEqual(await stopping,{cancelled:0,remaining:0});await rejection;assert.equal(await service.pending(),0);});

test('ZIP extraction uses a folder grant and safely publishes nested files',async t=>{const {writeZip}=await import('../src/features/converter/archive.mjs');const dir=await fs.mkdtemp(path.join(os.tmpdir(),'converter-zip-')),source=path.join(dir,'input.zip'),folder=path.join(dir,'output');await fs.mkdir(folder);await fs.writeFile(source,writeZip([{name:'nested/data.txt',bytes:Buffer.from('content')} ]));const service=createConverterService({stateDirectory:path.join(dir,'state'),sandboxProvider:{verifiedOsIsolation:true,launch:createRestrictedProcess},resolveGrant:async(id,mode)=>{if(id==='source'&&mode==='read')return source;if(id==='folder'&&mode==='directory')return folder;throw new Error('Invalid grant');}});t.after(async()=>{await service.close();await fs.rm(dir,{recursive:true,force:true});});const item=await service.enqueue({sourceIds:['source'],destinationDirectoryId:'folder',adapterId:'zip-extract',lossyConfirmed:true});assert.equal((await terminal(service,item.id)).state,'completed');assert.equal(await fs.readFile(path.join(folder,'nested','data.txt'),'utf8'),'content');});
