import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { createCredentialStore, createFeatureServices } from '../src/main/feature-services.js';
const safeStorage={isEncryptionAvailable:()=>true,encryptString:text=>Buffer.from(text),decryptString:value=>value.toString()};
async function fixture(t){const directory=await fs.mkdtemp(path.join(os.tmpdir(),'feature-services-'));t.after(()=>fs.rm(directory,{recursive:true,force:true}));return directory;}
test('protected record operations serialize, reload and reject unsupported keys',async t=>{const directory=await fixture(t);const store=createCredentialStore({directory,safeStorage});await Promise.all([store.set('local-profile:v1',{version:2}),store.set('element-lock:test',{policy:'pin'}),store.set('history:verifier',{version:2})]);assert.deepEqual(await store.get('local-profile:v1'),{version:2});assert.equal((await store.list('element-lock:')).length,1);await store.delete('history:verifier');assert.equal(await store.get('history:verifier'),null);assert.throws(()=>store.set('../escape',{}));assert.throws(()=>store.set('profile:unsafe',JSON.parse('{"__proto__":{"x":true}}')));});
test('protected storage refuses plaintext fallback',async t=>{const directory=await fixture(t);const store=createCredentialStore({directory,safeStorage:{isEncryptionAvailable:()=>false}});await assert.rejects(store.get('local-profile:v1'));assert.throws(()=>store.set('local-profile:v1',{}));assert.deepEqual(await fs.readdir(directory),[]);});
test('shared mode requires existing credentials to change an active record',async t=>{const directory=await fixture(t);const services=createFeatureServices({dataDirectory:directory,applicationRoot:directory,safeStorage,dialog:{},getWindow:()=>null,openPath:async()=>{}});await services.request('personalization','setSharedCredential',{password:'synthetic credential'});await services.request('personalization','sharedWrite',{value:{enabled:true,name:'School'}});await assert.rejects(services.request('personalization','sharedWrite',{value:{enabled:false}}));await assert.rejects(services.request('personalization','setSharedCredential',{password:'replacement'}));assert.equal(await services.request('personalization','verifySharedCredential',{password:'wrong'}),false);assert.equal(await services.request('personalization','verifySharedCredential',{password:'synthetic credential'}),true);await services.request('personalization','sharedWrite',{value:{enabled:false}});await assert.rejects(services.request('personalization','sharedWrite',{value:{vocabulary:{}}}));await services.close();});
test('feature dispatch refuses arbitrary methods and structured oversized input',async t=>{const directory=await fixture(t);const services=createFeatureServices({dataDirectory:directory,applicationRoot:directory,safeStorage,dialog:{},getWindow:()=>null,openPath:async()=>{}});await assert.rejects(services.request('arbitrary','exec',{}));await assert.rejects(services.request('converter','exec',{}));await assert.rejects(services.request('access','credentialSet',{key:'profile:x',value:'x'.repeat(300000)}));await services.close();await assert.rejects(services.request('status','status',{}));});
