import test from 'node:test';
import assert from 'node:assert/strict';
import {defaultImageTransform,validateImageTransform,renderImageLayers} from '../src/renderer/features/personalization/image-layers.js';
import {createAccessDocument} from './helpers/local-access-dom.js';
import {validateAppearance,newLayer,defaultAppearance} from '../src/renderer/features/personalization/appearance.js';
import {sanitizeImageExport} from '../src/renderer/features/personalization/image-source.js';
const source={version:1,mime:'image/png',dataUrl:'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAIAAAADCAYAAAAAAAAAAAAAAUlEQVQBAAAAAAAAAABJRU5EAAAAAA==',width:2,height:3,bytes:58};
test('image transform bounds reject unsafe crop, scale and blend values',()=>{assert.equal(validateImageTransform().opacity,1);for(const value of [{crop:[90,0,20,100]},{scaleX:0},{rotate:Infinity},{skewX:89},{blend:'url(https://invalid)'}])assert.throws(()=>validateImageTransform(value));});
test('immutable image source survives model edits but never portable export',()=>{const model=defaultAppearance();model.elements.test={normal:[{...newLayer('Image'),imageSource:source,imageTransform:defaultImageTransform()}]};const value=validateAppearance(model);assert.equal(value.elements.test.normal[0].imageSource.dataUrl,source.dataUrl);assert.equal(Object.isFrozen(value.elements.test.normal[0].imageSource),true);const exported=sanitizeImageExport(value);assert.equal(JSON.stringify(exported).includes('base64'),false);assert.equal(exported.elements.test.normal[0].imageSourceOmitted,true);});
test('image groups create independent ordered SVG layers with crop mask and visibility',()=>{const document=createAccessDocument(),create=document.createElement.bind(document);document.createElement=tag=>{const node=create(tag);node.style={};return node;};document.createElementNS=(_ns,tag)=>document.createElement(tag);const target=document.createElement('input');target.getBoundingClientRect=()=>({left:4,top:8,width:120,height:60});document.body.append(target);const layer={visible:true,imageSource:source,imageTransform:{...defaultImageTransform(),crop:[10,10,80,80],rotate:30},selection:{kind:'ellipse',values:[50,50,40,30]}};const overlay=renderImageLayers(target,[{kind:'group',visible:true,imageTransform:{opacity:.5},children:[layer,{...layer,visible:false}]}],value=>value);assert.equal(overlay.querySelectorAll('image').length,1);assert.equal(overlay.querySelectorAll('clipPath').length,1);assert.equal(overlay.children[1].getAttribute('opacity'),'0.5');assert.match(overlay.querySelectorAll('g')[1].getAttribute('transform'),/rotate\(30\)/);assert.equal(overlay.style.left,'4px');overlay.remove();assert.equal(document.body.querySelectorAll('image').length,0);});
import {mountAppearanceEditor} from '../src/renderer/features/personalization/appearance.js';
test('mounted editor persists image layers, draws target overlay, resets and tears down',()=>{
 const document=createAccessDocument(),create=document.createElement.bind(document);document.createElement=tag=>{const n=create(tag);n.style={};n.getBoundingClientRect=()=>({left:0,top:0,width:100,height:100});return n;};document.createElementNS=(_ns,tag)=>document.createElement(tag);document.documentElement={style:{setProperty(){}}};document.adoptedStyleSheets=[];document.defaultView={CSSStyleSheet:class{replaceSync(){}}};document.addEventListener=()=>{};document.removeEventListener=()=>{};
 const root=document.createElement('main'),target=document.createElement('div');target.id='picture';root.append(target);document.body.append(root);const previous={CSS:globalThis.CSS,addEventListener:globalThis.addEventListener,removeEventListener:globalThis.removeEventListener};globalThis.CSS={escape:x=>x};globalThis.addEventListener=()=>{};globalThis.removeEventListener=()=>{};let saved;
 try{const editor=mountAppearanceEditor(root,{storage:{getItem:()=>null,setItem:(_key,value)=>saved=value}});const model=defaultAppearance();model.elements['id:picture']={normal:[{...newLayer('Image'),imageSource:source,imageTransform:defaultImageTransform()}]};editor.setState(model);assert.equal(document.body.querySelectorAll('image').length,1);assert.ok(saved.includes(source.dataUrl));editor.reset();assert.equal(document.body.querySelectorAll('image').length,0);editor.setState(model);editor.destroy();assert.equal(document.body.querySelectorAll('image').length,0);assert.equal(document.adoptedStyleSheets.length,0);}finally{for(const [key,value]of Object.entries(previous)){if(value===undefined)delete globalThis[key];else globalThis[key]=value;}}
});
test('reset while image decoding is pending cancels the old layer write',async()=>{
 const document=createAccessDocument(),create=document.createElement.bind(document);document.createElement=tag=>{const n=create(tag);n.style={};n.getBoundingClientRect=()=>({left:0,top:0,right:100,width:100,height:100});if(tag==='canvas'){n.getContext=()=>({drawImage(){}});n.toDataURL=()=>source.dataUrl;}return n;};document.createElementNS=(_ns,tag)=>document.createElement(tag);document.documentElement={style:{setProperty(){}}};document.adoptedStyleSheets=[];document.defaultView={CSSStyleSheet:class{replaceSync(){}}};document.addEventListener=()=>{};document.removeEventListener=()=>{};
 const root=document.createElement('main'),target=document.createElement('div');target.id='picture';root.append(target);root.contains=node=>node===target;document.body.append(root);let release,started;const ready=new Promise(r=>started=r),hold=new Promise(r=>release=r);const previous={CSS:globalThis.CSS,addEventListener:globalThis.addEventListener,removeEventListener:globalThis.removeEventListener,innerWidth:globalThis.innerWidth,innerHeight:globalThis.innerHeight,createImageBitmap:globalThis.createImageBitmap};Object.assign(globalThis,{CSS:{escape:x=>x},addEventListener(){},removeEventListener(){},innerWidth:1000,innerHeight:800,createImageBitmap:async()=>{started();await hold;return{width:2,height:3,close(){}};}});let writes=0,editor;
 try{editor=mountAppearanceEditor(root,{storage:{getItem:()=>null,setItem:()=>writes++}});editor.open(target);const upload=document.body.querySelectorAll('input').find(n=>n.type==='file'&&n.accept==='image/png');const bytes=Uint8Array.from(atob(source.dataUrl.split(',')[1]),c=>c.charCodeAt(0));upload.files=[{size:bytes.length,arrayBuffer:async()=>bytes.buffer}];const pending=upload.onchange();await ready;document.body.querySelectorAll('button').find(n=>n.textContent==='Reset element').onclick();const before=writes;release();await pending;assert.equal(writes,before);assert.equal(JSON.stringify(editor.getState()).includes(source.dataUrl),false);}finally{release?.();editor?.destroy();for(const [key,value]of Object.entries(previous)){if(value===undefined)delete globalThis[key];else globalThis[key]=value;}}
});
