import test from 'node:test';
import assert from 'node:assert/strict';
import {createAccessDocument} from './helpers/local-access-dom.js';
import {mountAccess} from '../src/renderer/features/access/index.js';
const entry={secret:'JBSWY3DPEHPK3PXP',issuer:'Fixture',account:'sample',group:'Tests',algorithm:'SHA1',digits:6,period:30};
const click=(root,label)=>{const button=root.querySelectorAll('button').find(b=>b.textContent===label);assert.ok(button,label);return button.click();};
function fixture(onDelete){const document=createAccessDocument(),root=document.createElement('main');document.body.append(root);const data=new Map([['authenticator:index:v1',['sample']],['authenticator:sample',entry]]),exports=[];const api=mountAccess(root,{storage:{getItem:()=>null,setItem(){}},credentialStore:{get:async k=>data.get(k),set:async(k,v)=>data.set(k,v),delete:async k=>{if(onDelete)await onDelete(k);data.delete(k);}},exportLocalJson:value=>exports.push(value)});return {root,data,exports,api};}

test('authenticator metadata UI requires profile unlock and omits secrets',async()=>{const f=fixture();try{await f.api.loadAuthenticators();const auth=f.root.querySelectorAll('fieldset').find(x=>x.querySelector('legend')?.textContent==='Authenticator');await click(auth,'Select visible');await click(auth,'Export selected');assert.equal(f.exports.length,0);const profile=f.root.querySelectorAll('fieldset')[0];profile.querySelector('input').value='synthetic local password';await click(profile,'Set up local profile');await click(auth,'Export selected');assert.equal(f.exports.length,1);assert.equal(f.exports[0].entries.length,1);assert.equal(JSON.stringify(f.exports).includes(entry.secret),false);await click(auth,'Remove selected');await click(auth,'Cancel');assert.ok(f.data.has('authenticator:sample'));}finally{f.api.destroy();}});

test('cancelled authenticator bulk deletion restores the record',async()=>{let release,started;const ready=new Promise(r=>started=r),hold=new Promise(r=>release=r);const f=fixture(async()=>{started();await hold;});try{await f.api.loadAuthenticators();const auth=f.root.querySelectorAll('fieldset').find(x=>x.querySelector('legend')?.textContent==='Authenticator');await click(auth,'Select visible');await click(auth,'Remove selected');const pending=click(auth,'Confirm');await ready;const confirmation=auth.querySelectorAll('fieldset').at(-1);await click(confirmation,'Cancel');release();await pending;assert.deepEqual(f.data.get('authenticator:sample'),entry);assert.deepEqual(f.data.get('authenticator:index:v1'),['sample']);}finally{release?.();f.api.destroy();}});

test('tickets expose selected export with disclosure and confirm bulk removal',async()=>{const f=fixture();try{const support=f.root.querySelectorAll('fieldset').find(x=>x.querySelector('legend')?.textContent==='Support Tickets');const inputs=support.querySelectorAll('input');inputs[0].value='Sample';inputs[1].value='Synthetic description';await click(support,'Create local ticket');await click(support,'Select visible');await click(support,'Export selected');assert.equal(f.exports[0].tickets.length,1);assert.match(f.exports[0].privacyDisclosure,/Nothing is sent/);await click(support,'Remove selected');await click(support,'Confirm');await click(support,'Export selected');assert.equal(f.exports[1].tickets.length,0);}finally{f.api.destroy();}});

test('duplicate stale ticket confirmation cannot remove another ticket',async()=>{const f=fixture();try{const support=f.root.querySelectorAll('fieldset').find(x=>x.querySelector('legend')?.textContent==='Support Tickets');const inputs=support.querySelectorAll('input');for(const category of ['First','Second']){inputs[0].value=category;inputs[1].value='Synthetic';await click(support,'Create local ticket');}const remove=support.querySelectorAll('button').find(b=>b.textContent==='Remove');await remove.click();await remove.click();const confirmations=support.querySelectorAll('button').filter(b=>b.textContent==='Confirm');await confirmations[0].click();await confirmations[1].click();await click(support,'Select visible');await click(support,'Export selected');assert.equal(f.exports[0].tickets.length,1);assert.equal(f.exports[0].tickets[0].category,'Second');}finally{f.api.destroy();}});

test('cancelling during index persistence restores authenticator ordering',async()=>{
 const document=createAccessDocument(),root=document.createElement('main');document.body.append(root);const data=new Map([['authenticator:index:v1',['A','B']],['authenticator:A',entry],['authenticator:B',{...entry,account:'second'}]]);let release,started,pause=false;const ready=new Promise(r=>started=r),hold=new Promise(r=>release=r);const api=mountAccess(root,{storage:{getItem:()=>null,setItem(){}},credentialStore:{get:async k=>data.get(k),delete:async k=>data.delete(k),set:async(k,v)=>{data.set(k,v);if(pause&&k==='authenticator:index:v1'){pause=false;started();await hold;}}}});try{await api.loadAuthenticators();const auth=root.querySelectorAll('fieldset').find(x=>x.querySelector('legend')?.textContent==='Authenticator');const box=auth.querySelectorAll('input').find(x=>x.getAttribute('aria-label')==='Select record A');box.checked=true;await box.dispatchEvent({type:'change'});await click(auth,'Remove selected');pause=true;const pending=click(auth,'Confirm');await ready;await click(auth.querySelectorAll('fieldset').at(-1),'Cancel');release();await pending;assert.deepEqual(data.get('authenticator:index:v1'),['A','B']);assert.ok(data.has('authenticator:A'));}finally{release?.();api.destroy();}
});
