import test from 'node:test';import assert from 'node:assert/strict';
const traces=[];let response;
const chunk=(type,data=[])=>{const b=new Uint8Array(data.length+12);new DataView(b.buffer).setUint32(0,data.length);b.set([...type].map(c=>c.charCodeAt(0)),4);b.set(data,8);return b;};
function png(w,h){const header=new Uint8Array(13),view=new DataView(header.buffer);view.setUint32(0,w);view.setUint32(4,h);header[8]=8;header[9]=6;return Uint8Array.from([137,80,78,71,13,10,26,10,...chunk('IHDR',header),...chunk('IDAT',[1]),...chunk('IEND')]);}
class Canvas{constructor(w,h){this.width=w;this.height=h;this.context={canvas:this,clipped:false,stack:[],beginPath(){},rect(){},ellipse(){},moveTo(){},lineTo(){},closePath(){},scale(){},translate(){},rotate(){},transform(){traces.push('transform');},setTransform(){traces.push('reset-transform');},clip(){this.clipped=true;traces.push('clip');},save(){this.stack.push(this.clipped);},restore(){this.clipped=this.stack.pop();},fillRect(){traces.push({paint:'fill',clipped:this.clipped});},drawImage(){traces.push({paint:'image',clipped:this.clipped});}};}getContext(){return this.context;}async convertToBlob(){return new Blob([png(this.width,this.height)],{type:'image/png'});}}
globalThis.OffscreenCanvas=Canvas;globalThis.Path2D=class{};globalThis.createImageBitmap=async()=>({width:2,height:3,close(){}});globalThis.postMessage=value=>response=value;
await import('../src/renderer/features/personalization/appearance-raster-worker.js');
test('worker removes ambient network and retains SVG-path clip through painting',async()=>{assert.equal(globalThis.fetch,undefined);traces.length=0;await globalThis.onmessage({data:{operation:'composite',width:20,height:20,layers:[{properties:{backgroundColor:'#ffffff'},selection:{kind:'path',path:'M 0 0 L 100 0 L 0 100 Z'}}]}});assert.ok(response.source);assert.ok(traces.some(v=>v.paint==='fill'&&v.clipped));assert.ok(traces.includes('reset-transform'));});
test('nested groups allocate separate surfaces and apply outer compositing after child paint',async()=>{traces.length=0;await globalThis.onmessage({data:{operation:'composite',width:20,height:20,layers:[{children:[{properties:{backgroundColor:'#000000'}}],imageTransform:{opacity:.5,blend:'multiply'}}]}});assert.ok(response.source);assert.equal(traces.filter(v=>v.paint==='fill').length,1);assert.equal(traces.filter(v=>v.paint==='image').length,3);});
test('normalization rejects a decoded-size mismatch instead of returning pixels',async()=>{await globalThis.onmessage({data:{operation:'normalize',bytes:png(4,5)}});assert.match(response.error,/dimensions do not match/);});
