import {element} from './registry.js';
import {WORKFLOW_COPY} from './workflow-copy.js';
import './search.js';
import {validateDocument,downloadProgress,validCollection} from './workflow-model.js';
import {requestSuperConfirmation} from './workflow-confirm.js';

/** A document workspace with native, allowlisted handoffs supplied by the host. */
export function mount(host,{services={},translate=value=>value}={}){
 const doc=host.ownerDocument,storage=services.storage,sourceLabels=new Map(),labelRecords=new WeakMap();
 const t=source=>{const external=translate(source),language=services.getLanguage?.()||'en',yue=WORKFLOW_COPY[source];const value=external!==source?external:language==='yue'?(yue||source):language==='bilingual'&&yue?`${source} · ${yue}`:source;sourceLabels.set(value,source);return value;};
 function refreshLabels(scope=root){const walker=doc.createTreeWalker(scope,4);while(walker.nextNode()){const node=walker.currentNode;if(node.parentElement?.closest('input,textarea,pre,code,script,style'))continue;const old=labelRecords.get(node),source=old&&node.nodeValue===old.rendered?old.source:sourceLabels.get(node.nodeValue);if(source){const rendered=t(source);labelRecords.set(node,{source,rendered});if(node.nodeValue!==rendered)node.nodeValue=rendered;}}for(const node of [scope,...scope.querySelectorAll('*')]){for(const key of ['aria-label','title','label']){const value=node.getAttribute?.(key),source=sourceLabels.get(value);if(source)node.setAttribute(key,t(source));}if(node.shadowRoot)refreshLabels(node.shadowRoot);}}

 const root=element('section',{'aria-label':t('Document workflow')});host.append(root);
 const status=element('p',{role:'status','aria-live':'polite'});
 let editorSettingBound=false;let documents=[],templates=[],editors=[],accounts=[],owners=[],downloads=[],current=null,handoff=null,exportedHandoff=null,dirty=false,disposed=false,loading=false,generation=0;
 const cleanups=[],workflowAbort=new AbortController();
 const call=async(action,payload={})=>{if(typeof services.request!=='function')throw new Error(t('Connect the desktop workflow service first.'));return services.request(action,payload);};
 const showError=error=>{status.textContent=String(error?.message||error);};
 const button=(label,action)=>element('md-outlined-button',{text:t(label),onclick:()=>Promise.resolve().then(action).catch(showError)});
 const bindBusy=async(control,action)=>{if(loading)return;loading=true;control.disabled=true;try{return await action();}finally{loading=false;control.disabled=false;}};
 const field=(label,{multiline=false,value='',readOnly=false}={})=>{
  const wrap=element('div'),input=element('md-outlined-text-field',{label:t(label),value,type:multiline?'textarea':'text',readOnly,rows:multiline?8:1,maxLength:262144});
  wrap.append(input);let clear;if(!readOnly){clear=button(`Clear ${label}`,()=>{if(input.readOnly||input.disabled)return;input.value='';input.dispatchEvent(new Event('input'));input.focus();});wrap.append(clear);}return{wrap,input,clear};
 };
 const choice=(label,explanation)=>{const wrap=element('section'),select=element('select',{'aria-label':t(label)}),details=element('details',{},[element('summary',{text:t('Help')}),element('p',{text:t(explanation)})]),provenance=element('p');wrap.append(element('label',{text:t(label)}),select,details,provenance);return{wrap,select,provenance};};
 const fill=(select,items,label=item=>item.name||item.label)=>{const previous=select.value;select.replaceChildren(element('option',{value:'',text:t('Choose an available item')}),...items.map(item=>element('option',{value:item.id,text:label(item)})));if(items.some(item=>item.id===previous))select.value=previous;};
 const setting=(control,key)=>{let saved;try{saved=storage?.getItem(`mfe.workflow.${key}`);}catch{}const available=saved&&Array.from(control.select.options).some(option=>option.value===saved);if(available)control.select.value=saved;control.provenance.textContent=saved&&!available?t('Saved editor unavailable. Choose again.'):saved?`${t('Saved value')}: ${saved}`:t('Built-in default: no item selected');control.select.addEventListener('change',()=>{try{storage?.setItem(`mfe.workflow.${key}`,control.select.value);}catch{}control.provenance.textContent=`${t('Saved value')}: ${control.select.value||t('none')}`;});};
 const filterPanel=element('details'),filterSummary=element('summary',{text:t('Find documents')}),search=element('mfe-search',{label:t('Find documents'),scope:'workflow-documents'});
 try{filterPanel.open=storage?.getItem('mfe.workflow.filters')==='open';}catch{}filterPanel.append(filterSummary,search);filterPanel.addEventListener('toggle',()=>{try{storage?.setItem('mfe.workflow.filters',filterPanel.open?'open':'closed');}catch{}});
 const list=element('div'),name=field('Document name',{value:'document.txt'}),content=field('Document content',{multiline:true});
 const presets=choice('Starting preset','Presets insert local starting content. Custom edits remain unchanged until you explicitly choose a preset.');
 const editor=choice('External editor','Only host-detected or natively selected trusted editors can open the selected file or project. Editor choice is stored locally.');
 const save=button('Save document',()=>bindBusy(save,async()=>{const value=validateDocument({name:name.input.value,text:content.input.value});const token=generation;const saved=current?await call('saveDocument',{id:current.id,text:value.text,revision:current.revision}):await call('createDocument',value);if(token!==generation)return;current=saved;if(current){dirty=false;name.input.readOnly=true;name.clear.disabled=true;status.textContent=t('Document saved.');await refreshDocuments();}}));
 const discard=async next=>{if(!dirty)return next();const answer=await requestSuperConfirmation(root,{action:'Discard unsaved text',affected:name.input.value,translate:t,signal:workflowAbort.signal,run:async()=>{dirty=false;return next();}});return answer;};
 const selectProject=item=>discard(()=>{generation++;current=item;dirty=false;name.input.value=item.name;name.input.readOnly=true;name.clear.disabled=true;content.input.value='';content.input.readOnly=true;content.clear.disabled=true;save.disabled=true;save.title=t('Project folders open in an external editor. Choose a text document to save.');status.textContent=t('Project selected.');});
 const load=async id=>{await discard(async()=>{const token=++generation;const result=await call('readDocument',{id});if(disposed||token!==generation)return;current=result;content.input.readOnly=false;content.clear.disabled=false;save.disabled=false;save.title='';name.input.readOnly=true;name.clear.disabled=true;name.input.value=result.name;content.input.value=result.text;dirty=false;status.textContent=t('Document loaded.');});};
 async function renderDocuments(){const rows=await search.filter(documents.map(item=>({id:item.id,text:item.name})));if(disposed||rows===null)return;filterSummary.textContent=`${t('Find documents')}${search.query?` (${t('active filter')})`:''}`;list.replaceChildren(...rows.map(row=>{const item=documents.find(item=>item.id===row.id);return button(item.name,()=>item.kind==='folder'?selectProject(item):load(item.id));}));if(!rows.length)list.append(element('p',{text:t('No matching documents.')}));}
 async function refreshDocuments(){documents=validCollection(await call('documents'),'Documents');await renderDocuments();}
 content.input.addEventListener('input',()=>{dirty=true;});name.input.addEventListener('input',()=>{dirty=true;});search.addEventListener('search-change',renderDocuments);
 presets.select.addEventListener('change',()=>{const preset=templates.find(item=>item.id===presets.select.value);if(preset)discard(()=>{generation++;current=null;content.input.readOnly=false;content.clear.disabled=false;save.disabled=false;save.title='';name.input.readOnly=false;name.clear.disabled=false;name.input.value=preset.nameSuggestion||'document.txt';content.input.value=preset.text;dirty=false;status.textContent=t('Preset loaded.');}).catch(showError);});
 const browse=button('Browse document',async()=>{const item=await call('pickDocument');if(item){await refreshDocuments();await load(item.id);}}),project=button('Browse project folder',async()=>{const item=await call('pickProject');if(item){await selectProject(item);await refreshDocuments();}});
 const open=button('Open selected in editor',async()=>{if(dirty)throw new Error(t('Save the document before opening its stored version.'));if(!current||!editor.select.value)throw new Error(t('Select a saved document or project and an installed editor.'));await call('openEditor',{editorId:editor.select.value,documentId:current.id});status.textContent=t('Editor opened.');});
 const addEditor=button('Browse editor',async()=>{await call('pickEditor');editors=validCollection(await call('editors'),'Editors');fill(editor.select,editors);});
 const downloadEditor=button('Get Visual Studio Code',()=>call('editorDownload'));
 root.append(element('h2',{text:t('Document workflow')}),element('div',{class:'row'},[browse,project,button('New blank document',()=>discard(()=>{generation++;current=null;content.input.readOnly=false;content.clear.disabled=false;save.disabled=false;save.title='';name.input.readOnly=false;name.clear.disabled=false;name.input.value='document.txt';content.input.value='';dirty=false;}))]),filterPanel,list,presets.wrap,name.wrap,content.wrap,save,editor.wrap,element('div',{class:'row'},[open,button('Open selected in Visual Studio Code',async()=>{if(!current||dirty)throw new Error(t('Select and save a document first.'));await call('openInCode',{documentId:current.id});}),addEditor,downloadEditor]));
 const downloadSection=element('details'),downloadSummary=element('summary',{text:t('Downloads')}),url=field('HTTPS download URL'),downloadList=element('div');
 const prepare=button('Choose destination and review',async()=>{await call('prepareDownload',{url:url.input.value});await refreshDownloads();});
 async function refreshDownloads(){downloads=validCollection(await call('downloads'),'Downloads');if(disposed)return;downloadList.replaceChildren();for(const item of downloads){const card=element('section',{'aria-label':item.name}),progress=downloadProgress(item);card.append(element('h3',{text:item.name}),element('p',{text:item.source}),element('p',{text:item.destination||t('Destination unavailable')}),element('p',{role:'status',text:`${item.state}: ${progress.received}${progress.total?` / ${progress.total}`:''} ${t('bytes')}${item.rate?` · ${item.rate} ${t('bytes per second')}`:''}${item.eta?` · ${Math.ceil(item.eta)} ${t('seconds remaining')}`:''}`}));if(progress.value!==null)card.append(element('md-linear-progress',{value:progress.value,'aria-label':t('Download progress')}));if(item.error)card.append(element('p',{role:'status',text:item.error}));if(['ready','failed','cancelled'].includes(item.state))card.append(button(item.state==='ready'?'Start download':'Retry download',async()=>{await call('startDownload',{id:item.id});await refreshDownloads();}));if(['ready','downloading'].includes(item.state))card.append(button('Cancel download',async()=>{await call('cancelDownload',{id:item.id});await refreshDownloads();}));downloadList.append(card);}if(!downloads.length)downloadList.append(element('p',{text:t('No queued downloads.')}));}
 downloadSection.append(downloadSummary,element('p',{text:t('Choose a public HTTPS source and a new native destination. No transfer starts until Start download is pressed. Transfers support cancel and retry; pause and resume are unavailable.')}),url.wrap,prepare,button('Refresh downloads',refreshDownloads),downloadList);root.append(downloadSection);
 const forge=element('details'),forgeSummary=element('summary',{text:t('Publication handoff')}),account=choice('Forge account','Accounts come from the host credential manager. Credentials never enter this document or its export.'),owner=choice('Destination owner','Only destinations available to the selected account are offered.'),route=choice('Publication route','Copy and push is available independently of provider fork support. This prepares a local handoff; it does not publish.');
 fill(route.select,[{id:'copy-push',name:'Copy and push'}]);
 account.select.addEventListener('change',async()=>{try{owners=validCollection(await call('owners',{accountId:account.select.value}),'Owners');fill(owner.select,owners);}catch(error){showError(error);}});
 owner.select.addEventListener('change',()=>{const selected=owners.find(item=>item.id===owner.select.value);fill(route.select,[{id:'copy-push',name:t('Copy and push')},...(selected?.canFork?[{id:'fork',name:t('Fork')}]:[])]);});
 const preview=field('Prepared handoff',{multiline:true,readOnly:true});
 forge.append(forgeSummary,account.wrap,owner.wrap,route.wrap,button('Prepare handoff',async()=>{if(!current)throw new Error(t('Select a saved document or project first.'));handoff=await call('prepareHandoff',{documentId:current.id,accountId:account.select.value,ownerId:owner.select.value,route:route.select.value});preview.input.value=handoff.summary;}),preview.wrap,button('Open prepared handoff',async()=>{if(!handoff)throw new Error(t('Prepare and review the handoff first.'));await call('openHandoff',{id:handoff.id});}),button('Export prepared handoff',async()=>{if(!handoff)throw new Error(t('Prepare and review the handoff first.'));exportedHandoff=await call('exportHandoff',{id:handoff.id});}),button('Open exported handoff in Visual Studio Code',async()=>{if(!exportedHandoff?.documentId)throw new Error(t('Export the handoff first.'));await call('openInCode',{documentId:exportedHandoff.documentId});}));root.append(forge,status);
 async function refresh(){try{refreshLabels();await refreshDocuments();templates=validCollection(await call('templates'),'Presets');fill(presets.select,templates,item=>t(item.name));editors=validCollection(await call('editors'),'Editors');fill(editor.select,editors);if(!editors.length)editor.provenance.textContent=t('No supported editor was detected. Browse for one or get Visual Studio Code.');if(!editorSettingBound){setting(editor,'editor');editorSettingBound=true;}accounts=validCollection(await call('accounts'),'Accounts');fill(account.select,accounts);account.provenance.textContent=accounts.length?t('Available signed-in accounts'):t('No signed-in forge accounts are available. Sign in through the desktop host.');await refreshDownloads();}catch(error){showError(error);}}
 if(services.subscribe)cleanups.push(services.subscribe(event=>{if(event?.type==='download')refreshDownloads().catch(showError);}));
 if(typeof services.request!=='function'){for(const control of root.querySelectorAll('md-outlined-button,md-filled-button,select'))control.disabled=true;status.textContent=t('Connect the desktop workflow service first.');}else void refresh();
 return{refresh,refreshLabels,destroy(){disposed=true;workflowAbort.abort();generation++;cleanups.forEach(stop=>stop?.());root.remove();}};
}
