import { createScopedSearch } from '../../scoped-search.js';
export function mountConverter(root,{services,translate=(s)=>s}={}) {
 const api=services.converter;let selected=[],choice=null,offset=0,disposed=false;const searches=[];
 const el=(tag,text)=>{const e=document.createElement(tag);if(text)e.textContent=translate(text);return e;};
 const title=el('h2','Local file converter'),notice=el('p','Choose source files. Sources stay unchanged. Processing happens locally with bounded resources.'),status=el('p');status.setAttribute('role','status');status.setAttribute('aria-live','polite');
 const pick=el('button','Choose source files'),preview=el('pre'),catalogHost=el('div'),settings=el('fieldset');preview.style.whiteSpace='pre-wrap';settings.append(el('legend','Conversion options'));
 const fields=[];const field=(label,type='text',group='all',values)=>{const wrap=el('label',label),input=el(values?'select':'input');if(values)for(const [value,text]of values){const option=el('option',text);option.value=value;input.append(option);}else input.type=type;wrap.append(input);settings.append(wrap);fields.push({id:String(fields.length),path:label,wrap,group});return input;};
 const pages=field('PDF pages, for example 1,3-5','text','pdf'),rotation=field('Rotation in degrees','number','pdf');rotation.value='90';const metadata=field('PDF title','text','pdf');
 const delimiter=field('CSV delimiter','text','data',[[',','Comma'],[';','Semicolon'],['\t','Tab']]);delimiter.value=',';
 const lineEnding=field('Output line ending','text','data',[['LF','LF'],['CRLF','CRLF']]);lineEnding.value='LF';
 const formula=field('Spreadsheet formula handling','text','data',[['reject','Reject formula-like cells'],['escape','Prefix formula-like cells with apostrophe'],['preserve','Preserve formula-like cells with warning']]);formula.value='reject';
 const compression=field('ZIP compression','text','zip',[['store','Store without compression'],['deflate','Deflate']]);compression.value='store';
 const acknowledge=field('Confirm disclosed metadata and encoding changes','checkbox'),overwrite=field('Allow replacing the selected output file','checkbox');
 const optionSearchHost=el('div');settings.append(optionSearchHost);const optionsSearch=createScopedSearch(optionSearchHost,translate,refreshOptions);searches.push(optionsSearch);
 async function refreshOptions(){const matched=new Set((await optionsSearch.filter(fields)).map(row=>row.id));const group=choice?.id.startsWith('pdf-')?'pdf':choice?.id.startsWith('zip-')?'zip':'data';for(const f of fields)f.wrap.hidden=!matched.has(f.id)||(f.group!=='all'&&f.group!==group);}
 const convert=el('button','Choose output and convert');convert.disabled=true;const history=el('section');history.append(el('h3','Queue and result history'));const rows=el('div'),previous=el('button','Previous page'),next=el('button','Next page');history.append(rows,previous,next);root.replaceChildren(title,notice,pick,preview,catalogHost,settings,convert,status,history);
 function fail(error){status.textContent=error?.message||translate('Operation could not complete.');}
 pick.onclick=async()=>{try{const values=await services.pickSources();selected=values.map(x=>typeof x==='string'?x:x.id);const result=selected.length?await api.inspect({sourceIds:selected}):[];preview.textContent=result.map(x=>`${x.type}: ${x.bytes} bytes${x.preview?'\n'+x.preview:''}${x.media?'\n'+Object.entries(x.media).filter(([,v])=>v!==undefined).map(([k,v])=>k+': '+v).join(', '):''}`).join('\n\n');convert.disabled=!selected.length||!choice;}catch(e){fail(e);}};
 const catalogPromise=Promise.resolve(api.catalog()).then(items=>{for(const category of [...new Set(items.map(x=>x.category))]){const section=el('section');section.append(el('h3',category));const searchHost=el('div'),list=el('div');section.append(searchHost,list);catalogHost.append(section);const scoped=createScopedSearch(searchHost,translate,refresh);searches.push(scoped);async function refresh(){list.replaceChildren();for(const item of await scoped.filter(items.filter(x=>x.category===category).map(x=>({...x,path:x.name})))){const button=el('button',item.name);button.disabled=!item.enabled;button.setAttribute('aria-pressed',String(choice?.id===item.id));button.onclick=()=>{choice=item;notice.textContent=translate(item.metadata)+' '+translate(item.encoding);convert.disabled=!selected.length;void refreshOptions();};list.append(button,el('p',item.enabled?item.metadata:item.disabledReason));}}void refresh();}}).catch(fail);
 convert.onclick=async()=>{try{const folder=['pdf-split','zip-extract'].includes(choice.id);if(folder&&!services.pickDestinationDirectory)throw new Error('A destination folder picker is required for this operation.');const destination=folder?await services.pickDestinationDirectory():await services.pickDestination({extension:choice.target});if(!destination)return;if(overwrite.checked&&!await services.confirmOverwrite?.())return;await api.enqueue({sourceIds:selected,destinationId:folder?undefined:(typeof destination==='string'?destination:destination.id),destinationDirectoryId:folder?(typeof destination==='string'?destination:destination.id):undefined,adapterId:choice.id,options:{pages:pages.value||undefined,rotation:Number(rotation.value),metadata:metadata.value?{title:metadata.value}:undefined,delimiter:delimiter.value,lineEnding:lineEnding.value,formulaPolicy:formula.value,compression:compression.value},lossyConfirmed:acknowledge.checked,overwriteConfirmed:overwrite.checked});status.textContent=translate('Queued for local conversion.');await refreshHistory();}catch(e){fail(e);}};
 async function refreshHistory(){try{const entries=await api.list({offset,limit:50});if(disposed)return;rows.replaceChildren();for(const row of entries){const item=el('article');item.append(el('p',`${row.adapterId}: ${row.state} (${row.progress}%)`));if(row.error)item.append(el('p',row.error));if(row.outputs)item.append(el('p',row.outputs.join(', ')));for(const action of ['pause','resume','cancel']){const button=el('button',action);button.disabled=['completed','failed','cancelled'].includes(row.state);button.onclick=async()=>{try{await api.control({id:row.id,action});await refreshHistory();}catch(e){fail(e);}};item.append(button);}rows.append(item);}previous.disabled=offset===0;next.disabled=entries.length<50;}catch(e){fail(e);}}
 previous.onclick=()=>{offset=Math.max(0,offset-50);void refreshHistory();};next.onclick=()=>{offset+=50;void refreshHistory();};const timer=setInterval(()=>void refreshHistory(),1500);void refreshHistory();void refreshOptions();return {ready:catalogPromise,destroy(){disposed=true;clearInterval(timer);root.replaceChildren();},refresh:refreshHistory};
}
