import { createRegexFilter } from './regex.js';
/** Local-only UI. The host supplies an authenticated request and event bridge. */
export function mountOllama(root,{services,translate=(s)=>s,confirm:confirmAction=async()=>false}={}) {
  const bridge=services?.ollama;if(!root||!bridge?.request)throw new Error('The authenticated local model bridge is required.');
  const t=translate, request=(action,p={})=>bridge.request(action,p);
  let models=[],cart=[],catalog={},sessions=[],profiles=[],hardware=null,selected=null,operation=null,sessionId=null,disposed=false;
  const regexFilter=createRegexFilter();let searchRevision=0;
  const elements={};const section=document.createElement('section');section.className='ollama-suite';section.setAttribute('aria-label',t('Local models'));root.append(section);
  const el=(tag,text,parent=section)=>{const e=document.createElement(tag);if(text)e.textContent=t(text);parent.append(e);return e;};
  const button=(text,parent,fn)=>{const b=el('button',text,parent);b.type='button';b.addEventListener('click',()=>safe(fn));return b;};
  const label=(text,type,parent)=>{const l=el('label',text,parent),input=el(type,null,l);return input;};
  const row=parent=>{const r=el('div',null,parent);r.className='ollama-row';return r;};
  const select=(text,values,parent)=>{const s=label(text,'select',parent);for(const [value,name] of values){const o=el('option',name,s);o.value=value;}return s;};
  const status=el('p','Check the local runtime to begin.');status.className='ollama-status';status.setAttribute('role','status');status.setAttribute('aria-live','polite');
  const safe=async(fn)=>{try{await fn();}catch(error){status.textContent=error.message;}};
  const tabs=el('nav');tabs.setAttribute('aria-label',t('Local model sections'));
  const panels={};for(const name of ['Model Store','Pull cart','Local chat','Profiles','Help']){const p=el('article');p.hidden=name!=='Model Store';panels[name]=p;button(name,tabs,()=>{Object.entries(panels).forEach(([n,v])=>v.hidden=n!==name);});el('h3',name,p);}
  const summary=el('p','No verified catalog is stored.',panels['Model Store']);
  const controls=row(panels['Model Store']);
  const runtimeDetails=el('p',null,panels['Model Store']);let runtimeState=null;
  async function checkRuntime(){runtimeState=await request('status');runtimeDetails.textContent=`${t('Runtime state')}: ${t(runtimeState.state)}. ${t(runtimeState.reason||'')} ${runtimeState.version||''} ${runtimeState.endpoint||''} · ${t(runtimeState.managedModelStore?'Application-managed model storage':'Existing runtime model storage')}`;if(runtimeState.endpoint)portInput.value=new URL(runtimeState.endpoint).port;installButton.disabled=!runtimeState.actions?.install;startButton.disabled=!runtimeState.actions?.start;chooseRuntimeButton.disabled=!runtimeState.actions?.selectExecutable;registerProfileButton.disabled=!runtimeState.actions?.registerProfile;}
  const portInput=label('Local runtime port','input',controls);portInput.type='number';portInput.min='1024';portInput.max='65535';portInput.value='11434';
  const configureButton=button('Apply runtime port',controls,async()=>{const port=Number(portInput.value);if(!Number.isInteger(port)||port<1024||port>65535)throw new Error(t('Choose a port from 1024 to 65535.'));await bridge.configureRuntime({port});await checkRuntime();});configureButton.disabled=typeof bridge.configureRuntime!=='function';
  button('Check runtime',controls,checkRuntime);
  const installButton=button('Open official installation guide',controls,async()=>{if(!await confirmAction({title:t('Open the official installer page?'),message:t('No installer will be downloaded or executed by this application. Complete the official installation, then check runtime again.'),destructive:false}))return;const result=await request('runtimeInstall',{confirmed:true});status.textContent=t(result.next);});installButton.disabled=true;
  const startButton=button('Start verified local runtime',controls,async()=>{if(!await confirmAction({title:t('Start the verified local runtime?'),message:t('Starts the verified Ollama executable with a loopback-only address and cloud features disabled. No model will be downloaded.'),destructive:false}))return;const result=await request('runtimeStart',{confirmed:true});status.textContent=t(result.state);await checkRuntime();});startButton.disabled=true;
  const chooseRuntimeButton=button('Locate installed runtime',controls,async()=>{await request('chooseRuntimeExecutable');await checkRuntime();});chooseRuntimeButton.disabled=true;

  button('Refresh official catalog',controls,async()=>{const r=await request('refreshCatalog');operation=r.operationId;status.textContent=t('Refreshing all official model families and tags. Installed models remain available.');});
  button('Refresh installed models',controls,refresh);
  const search=label('Search models','input',panels['Model Store']);search.type='search';
  const filters=row(panels['Model Store']);
  const installedFilter=select('Installed state',[['all','All states'],['installed','Installed'],['running','Running'],['available','Available to pull']],filters);
  const capability=select('Capability',[['all','All capabilities'],['vision','Vision'],['tools','Tools'],['embedding','Embedding'],['thinking','Thinking']],filters);
  const fitFilter=select('Hardware fit',[['all','All verdicts'],['Runs well','Runs well'],['Runs with limits','Runs with limits'],['Unlikely','Unlikely'],['Unknown','Unknown']],filters);
  const sort=select('Sort',[['name','Name'],['size','Size']],filters);
  const familyFilter=label('Family','input',filters);familyFilter.type='search';
  const quantFilter=label('Quantization','input',filters);quantFilter.type='search';
  const regexDetails=el('details',null,panels['Model Store']);el('summary','Regular expression builder',regexDetails);
  const regexMode=select('Search mode',[['plain','Plain text'],['regex','Regular expression']],regexDetails);
  const anchor=select('Match location',[['any','Anywhere'],['start','Starts with'],['exact','Exact match']],regexDetails);
  el('p','Regex searches run in a disposable worker with a 150 ms deadline, a 128-character pattern limit, and a 4 MiB text limit.',regexDetails);
  const list=el('div',null,panels['Model Store']);list.className='ollama-list';
  const detail=el('div',null,panels['Model Store']);
  async function renderModels(){
    const revision=++searchRevision;regexFilter.cancel();
    const query=search.value.toLowerCase();
    let filtered=models.filter(m=>(installedFilter.value==='all'||(installedFilter.value==='available'?!m.installed:m[installedFilter.value]))&&(capability.value==='all'||m.capabilities?.includes(capability.value))&&(fitFilter.value==='all'||(m.fit?.verdict||'Unknown')===fitFilter.value)&&(!familyFilter.value||m.family?.toLowerCase().includes(familyFilter.value.toLowerCase()))&&(!quantFilter.value||m.quantization?.toLowerCase().includes(quantFilter.value.toLowerCase())));
    const text=m=>[m.tag,m.family,m.variant,m.quantization,m.description].join(' ');
    if(query&&regexMode.value==='regex'){
      // Do not leave rows from a previous query actionable while an expression
      // is pending, invalid or timed out.
      list.replaceChildren();status.textContent=t('Searching in an isolated worker.');
      try {const matches=await regexFilter.filter(query,filtered.map(text),anchor.value);if(disposed||revision!==searchRevision)return;filtered=matches.map(i=>filtered[i]);}
      catch(error){if(!disposed&&revision===searchRevision){list.replaceChildren();status.textContent=t(error.message);}return;}
    }else if(query)filtered=filtered.filter(m=>text(m).toLowerCase().includes(query));
    if(disposed||revision!==searchRevision)return;
    filtered.sort(sort.value==='size'?(a,b)=>(a.sizeBytes??Infinity)-(b.sizeBytes??Infinity):(a,b)=>a.tag.localeCompare(b.tag));list.replaceChildren();
    el('p',`${filtered.length} ${t('matching variants')}`,list);
    for(const m of filtered.slice(0,200)){const b=button(`${m.tag} · ${m.installed?t('Installed'):t('Available')} · ${m.fit?.verdict||t('Unknown')} · ${m.sizeBytes?formatBytes(m.sizeBytes):t('Size unknown')}`,list,()=>showModel(m));b.className='ollama-model';}
    if(filtered.length>200)el('p','Refine the search to show more variants. All variants are included in filtering.',list);
  }
  for(const control of [search,installedFilter,capability,fitFilter,sort,familyFilter,quantFilter,regexMode,anchor])control.addEventListener('input',()=>safe(renderModels));
  async function showModel(m){selected=m;detail.replaceChildren();el('h4',m.tag,detail);el('p',m.description||'Official variant; detailed metadata is available after installation.',detail);el('p',`${t('Context')}: ${m.contextLength??t('Unknown')} · ${t('Quantization')}: ${m.quantization??t('Unknown')} · ${t('Parameters')}: ${m.parameterCount??t('Unknown')}`,detail);el('p',m.fit?.reason||'Hardware fit is unknown. Refresh hardware evidence before deciding.',detail);button('Add to pull cart',detail,async()=>{cart=await request('addToCart',{model:m.tag});renderCart();status.textContent=t('Added to local pull cart. No download has started.');});const inspect=button('Inspect installed metadata',detail,async()=>{const data=await request('show',{model:m.tag});m.capabilities=data.capabilities||[];m.quantization=data.details?.quantization_level;m.parameterCount=data.details?.parameter_size;el('pre',JSON.stringify({capabilities:m.capabilities,details:data.details,modelInfo:data.model_info},null,2),detail);});inspect.disabled=!m.installed;inspect.title=m.installed?'':t('Pull this model first to inspect local metadata.');
    if(m.installed){const slot=select('Copy destination',[['local-copy',m.family+':local-copy'],['local-copy-2',m.family+':local-copy-2'],['local-copy-3',m.family+':local-copy-3']],detail);button('Copy installed model',detail,async()=>{await request('copyModel',{model:m.tag,slot:slot.value});await refresh();status.textContent=t('Model copy created.');});button('Delete installed model',detail,async()=>{if(!await confirmAction({title:t('Delete installed model?'),message:m.tag,destructive:true,requiredText:m.tag}))return;await request('deleteModel',{model:m.tag,confirmation:m.tag});detail.replaceChildren();await refresh();status.textContent=t('Installed model removed.');});}
  }
  const hardwareEvidence=el('pre',null,panels['Model Store']);
  button('Refresh hardware evidence',panels['Model Store'],async()=>{const h=await request('hardware');hardware=h.hardware;models=h.models;hardwareEvidence.textContent=JSON.stringify(hardware,null,2);renderModels();status.textContent=t('Hardware evidence refreshed. Missing GPU or context evidence remains unknown.');});
  const transfer=el('p','Pulls download model data from Ollama. They consume network transfer and local storage. No download starts until you confirm.',panels['Pull cart']);
  const parallelism=select('Parallel downloads',[['1','1 (recommended)'],['2','2'],['3','3']],panels['Pull cart']);
  const cartList=el('div',null,panels['Pull cart']);
  function renderCart(){cartList.replaceChildren();let total=0,unknown=false;for(const c of cart){const model=models.find(m=>m.tag===c.model);if(model?.sizeBytes)total+=model.sizeBytes*1.2;else unknown=true;const r=row(cartList);el('span',`${c.model}: ${c.state} · ${formatBytes(c.completed||0)} / ${c.total?formatBytes(c.total):t('Unknown')}`,r);button('Remove',r,async()=>{cart=await request('removeFromCart',{model:c.model});renderCart();});if(['failed','cancelled','interrupted'].includes(c.state))button('Retry',r,async()=>{cart=await request('retryPull',{model:c.model});renderCart();});}transfer.textContent=`${t('Estimated additional storage')}: ${formatBytes(total)}${unknown?' + '+t('unknown variants'):''}. ${t('Free space')}: ${hardware?.freeDiskBytes?formatBytes(hardware.freeDiskBytes):t('Unknown')}. ${t('Pulls download model data and consume network transfer.')}`;}
  button('Review and start pulls',panels['Pull cart'],async()=>{if(!await confirmAction({title:t('Download selected models?'),message:transfer.textContent,destructive:false}))return;const r=await request('startPulls',{parallelism:Number(parallelism.value),confirmNetwork:true});operation=r.operationId;status.textContent=t('Downloads started.');});
  button('Cancel active operation',panels['Pull cart'],()=>operation?request('cancel',{operationId:operation}):Promise.reject(new Error(t('No active operation.'))));
  const chatPanel=panels['Local chat'];
  const modelSelect=select('Installed model',[],chatPanel),sessionSelect=select('Saved session',[['','New session']],chatPanel);
  sessionSelect.addEventListener('change',()=>safe(async()=>{sessionId=sessionSelect.value||null;if(!sessionId){output.textContent='';return;}const s=await request('session',{id:sessionId});modelSelect.value=s.model;sessionName.value=s.name;output.textContent=s.messages.map(m=>`${m.role}: ${m.content}`).join('\n\n');}));
  const sessionName=label('Session name','input',chatPanel);sessionName.maxLength=100;
  const sessionActions=row(chatPanel);button('Rename',sessionActions,async()=>{await request('renameSession',{id:sessionId,name:sessionName.value});await refreshSessions();});
  button('Delete session',sessionActions,async()=>{if(!sessionId)throw new Error(t('Select a session first.'));if(!await confirmAction({title:t('Delete local session permanently?'),message:t('All messages in this session will be removed.'),destructive:true,requiredText:'DELETE'}))return;await request('deleteSession',{id:sessionId,confirm:true,confirmation:'DELETE'});sessionId=null;await refreshSessions();output.textContent='';});
  button('Export redacted session',sessionActions,async()=>{const result=await request('exportSession',{id:sessionId});const blob=new Blob([JSON.stringify(result,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='local-chat-redacted.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
  const system=label('System instruction','textarea',chatPanel);system.maxLength=65536;
  const parameters=row(chatPanel),temperature=label('Temperature (recommended 0.7)','input',parameters);temperature.type='number';temperature.min='0';temperature.max='2';temperature.step='.1';temperature.value='.7';
  const context=select('Context limit',[['2048','2048 (recommended)'],['4096','4096'],['8192','8192']],parameters),length=select('Response limit',[['512','512'],['1024','1024 (recommended)'],['2048','2048']],parameters);length.value='1024';
  const prompt=label('Message','textarea',chatPanel);prompt.maxLength=65536;
  const attachment=label('Image attachments','input',chatPanel);attachment.type='file';attachment.accept='image/png,image/jpeg,image/webp';attachment.multiple=true;attachment.disabled=true;attachment.title=t('Select and inspect an installed vision model to enable image attachments.');
  modelSelect.addEventListener('change',()=>safe(async()=>{attachment.disabled=true;const m=await request('show',{model:modelSelect.value});attachment.disabled=!m.capabilities?.includes('vision');attachment.title=attachment.disabled?t('This model does not report vision capability. Filter Model Store by Vision and pull a compatible model.'):'Up to 4 images, 1 MB each.';}));
  const output=el('div',null,chatPanel);output.className='ollama-output';output.setAttribute('role','log');output.setAttribute('aria-live','polite');
  async function send(regenerate=false){const files=[...attachment.files];if(files.length>4||files.some(f=>f.size>1024*1024))throw new Error(t('Choose up to four images, each at most 1 MB.'));const images=await Promise.all(files.map(f=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(f);})));const r=await request('chat',{model:modelSelect.value,prompt:prompt.value,system:system.value,sessionId,options:{temperature:Number(temperature.value),num_ctx:Number(context.value),num_predict:Number(length.value)},images,regenerate});operation=r.operationId;output.textContent='';status.textContent=t('Generating locally.');}
  const sendRow=row(chatPanel);button('Send',sendRow,()=>send());button('Regenerate',sendRow,()=>send(true));button('Stop',sendRow,()=>request('cancel',{operationId:operation}));
  button('Generate a single response',sendRow,async()=>{const r=await request('generate',{model:modelSelect.value,prompt:prompt.value,system:system.value,options:{temperature:Number(temperature.value),num_ctx:Number(context.value),num_predict:Number(length.value)}});operation=r.operationId;output.textContent='';});
  const profileSelect=select('Registered profile',[],panels.Profiles),profilePreview=el('pre',null,panels.Profiles);
  const recipe=select('Native profile recipe',[['version','Ollama version check'],['models','Installed model list'],['inspect','Model metadata inspection']],panels.Profiles);
  const registerProfileButton=button('Register profile with native pickers',panels.Profiles,async()=>{await request('registerProfile',{recipe:recipe.value});await refresh();});registerProfileButton.disabled=true;

  button('Preflight selected model',panels.Profiles,async()=>{profilePreview.textContent=JSON.stringify(await request('preflight',{id:profileSelect.value,model:selected?.tag||modelSelect.value}),null,2);});
  button('Launch reviewed profile',panels.Profiles,async()=>{const model=selected?.tag||modelSelect.value;const preview=await request('preflight',{id:profileSelect.value,model});profilePreview.textContent=JSON.stringify(preview,null,2);if(!preview.ready)throw new Error(preview.blockers.join(' '));if(!await confirmAction({title:t('Launch selected profile?'),message:JSON.stringify(preview),destructive:false}))return;const r=await request('launch',{id:profileSelect.value,model});status.textContent=r.state;if(r.internal==='local-chat')Object.entries(panels).forEach(([n,p])=>p.hidden=n!=='Local chat');});
  const snapshots=select('Configuration snapshot',[],panels.Profiles);button('Refresh snapshots',panels.Profiles,async()=>{snapshots.replaceChildren();for(const s of await request('snapshots')){const o=el('option',s.at,snapshots);o.value=s.id;}});button('Restore selected snapshot',panels.Profiles,async()=>{await request('restore',{id:snapshots.value});status.textContent=t('Profile snapshot restored.');});
  for(const text of ['This suite uses only the configured loopback Ollama API. No cloud model account is used.','Runtime unavailable: install the official desktop package if absent, or open Ollama through your operating-system application launcher if stopped. Then choose Check runtime. This suite never starts or installs a service automatically.','Catalog offline: use the last successful catalog and installed models. A refresh that loses a family, tag, or page does not replace the previous catalog.','Pull failed: check available storage and connectivity, then retry the individual item. Completed models are retained.','Model incompatible: inspect its declared capabilities and select another installed model. GPU, driver, or context evidence that cannot be verified is shown as Unknown.','External profiles require a host-provided executable picker, allowlist, and readiness verifier. No freeform shell commands or environment values are accepted.','Session exports redact recognized credentials, environment values, and private paths, and omit image bytes. Review the export locally before sharing because automatic redaction cannot identify every secret.'])el('p',text,panels.Help);
  async function refreshSessions(){sessions=await request('sessions');sessionSelect.replaceChildren();const n=el('option','New session',sessionSelect);n.value='';for(const s of sessions){const o=el('option',s.name,sessionSelect);o.value=s.id;}sessionSelect.value=sessionId||'';}
  async function refresh(){const results=await Promise.all([request('models'),request('catalog'),request('profiles'),request('cart')]);if(disposed)return;models=results[0].models;catalog=results[1];profiles=results[2];cart=results[3];summary.textContent=catalog.lastSuccessfulRefresh?`${t('Last successful refresh')}: ${catalog.lastSuccessfulRefresh} · ${catalog.familyCount} ${t('families')} · ${catalog.variants.length} ${t('variants')} · ${catalog.pageCount} ${t('pages')} · ${catalog.stale?t('Stale'):t('Verified refresh')} · ${t('Global completeness unknown')}`:t('No complete official catalog has been stored. Refresh the official catalog to discover models.');modelSelect.replaceChildren();for(const m of models.filter(m=>m.installed)){const o=el('option',m.tag,modelSelect);o.value=m.tag;}profileSelect.replaceChildren();for(const p of profiles){const o=el('option',p.name,profileSelect);o.value=p.id;}renderModels();renderCart();await refreshSessions();}
  const unsubscribe=bridge.subscribe?.(event=>{if(disposed)return;if(event.type==='chat'){sessionId=event.sessionId;output.textContent+=event.delta;}if(event.type==='generate')output.textContent+=event.delta;if(event.type==='pull'){const i=cart.findIndex(c=>c.model===event.item.model);if(i>=0)cart[i]=event.item;else cart.push(event.item);renderCart();}if(['complete','error','cancelled'].includes(event.type)){operation=null;status.textContent=event.message||t('Operation finished. Review its outcome.');safe(refresh);}if(event.type==='catalog'){catalog=event.catalog;safe(refresh);}});
  safe(async()=>{await refresh();await checkRuntime();});
  return {refresh,destroy(){disposed=true;searchRevision++;regexFilter.dispose();unsubscribe?.();section.remove();}};
}
function formatBytes(n){if(!Number.isFinite(n))return 'Unknown';if(n<1024)return `${n} B`;const unit=Math.min(Math.floor(Math.log(n)/Math.log(1024)),4);return `${(n/1024**unit).toFixed(1)} ${['B','KiB','MiB','GiB','TiB'][unit]}`;}
