using System.Security.Cryptography;
using System.Text;
using MaterialFileEncryptor.Core;

var cases = new (string,Action)[] {
    ("random access, sparse growth, truncate, atomic rename and stable handles",RandomAccess),
    ("credential wrapping, key file and raw master restore",Credentials),
    ("case folding, traversal and Windows reserved names",Paths),
    ("physical ciphertext caps, packed records and explicit resplit",Caps),
    ("authenticated record tamper is rejected",Tamper),
    ("offline pin, dirty journal recovery and queued publication",Offline),
    ("independent devices preserve concurrent file edits",Conflicts),
    ("incomplete incoming version preserves last usable view",Incomplete),
    ("pinned, open and dirty ciphertext cannot be evicted",Eviction),
    ("concurrent directory deletion preserves visible descendant edits",DirectoryConflict),
    ("remote deletion retains open-handle content",RemoteOpen),
    ("root and managed-child symbolic links are rejected",Links),
    ("folder pin inheritance and sparse terabyte lengths",FolderPin),
};
if(args.Length==2 && args[0]=="crash-write") {
    var options=Options(args[1]); using var c=VaultCredentials.Password("strong test credential"); var v=VaultEngine.Open(options,c);
    v.CreateFile("recovered.txt");v.WriteRange("recovered.txt",0,Encoding.UTF8.GetBytes("journal survives abrupt termination"));v.FlushAsync().GetAwaiter().GetResult();
    Environment.Exit(0);
}
var failed=0;
foreach(var (name,test) in cases) {try {test();Console.WriteLine("PASS "+name);}catch(Exception e){failed++;Console.Error.WriteLine("FAIL "+name+": "+e);}}
Console.WriteLine($"{cases.Length-failed}/{cases.Length} checks passed");
return failed==0?0:1;

static VaultOptions Options(string root,string cache="cache",long cap=1024) => new() { StorageRoot=Path.Combine(root,"source"),CacheRoot=Path.Combine(root,cache),PartSizeBytes=cap };
static void Assert(bool result,string message="Assertion failed") {if(!result)throw new Exception(message);}
static void Equal(byte[] expected,byte[] actual) => Assert(expected.SequenceEqual(actual),"Bytes differ.");
static void Throws<T>(Action action) where T:Exception {try{action();}catch(T){return;}throw new Exception("Expected "+typeof(T).Name);}
static string Temp() {var p=Path.Combine(Path.GetTempPath(),"mfe-tests-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(p);return p;}
static VaultEngine Create(string root,long cap=1024) {using var c=VaultCredentials.Password("strong test credential");return VaultEngine.Create(Options(root,cap:cap),c);}
static VaultEngine Open(string root,string cache="cache") {using var c=VaultCredentials.Password("strong test credential");return VaultEngine.Open(Options(root,cache),c);}
static byte[] Read(VaultEngine v,string path) {var bytes=new byte[v.GetInfo(path)!.Length];Assert(v.ReadRange(path,0,bytes)==bytes.Length);return bytes;}
static void RandomAccess() {
    var root=Temp();try {using var v=Create(root);v.CreateDirectory("docs");v.CreateFile("docs/a.txt");var a=RandomNumberGenerator.GetBytes(12000);v.WriteRange("docs/a.txt",0,a);Equal(a,Read(v,"DOCS/A.TXT"));
        var patch=Encoding.UTF8.GetBytes("offset patch");v.WriteRange("docs/a.txt",981,patch);patch.CopyTo(a,981);Equal(a,Read(v,"docs/a.txt"));
        v.SetLength("docs/a.txt",15000);var extended=Read(v,"docs/a.txt");Equal(a,extended[..a.Length]);Assert(extended[a.Length..].All(b=>b==0));
        v.SetLength("docs/a.txt",997);v.SetLength("docs/a.txt",1100);Assert(Read(v,"docs/a.txt")[997..].All(b=>b==0),"Truncated bytes reappeared.");
        v.CreateFile("docs/b.txt");v.WriteRange("docs/b.txt",0,"old destination"u8);var id=v.GetInfo("docs/b.txt")!.EntryId;using var lease=v.AcquireOpenById(id);v.Rename("docs/a.txt","docs/b.txt",true);var old=new byte[15];Assert(v.ReadRangeById(id,0,old)==15);Equal("old destination"u8.ToArray(),old);Assert(v.GetInfo("docs/a.txt")==null);v.FlushAsync().GetAwaiter().GetResult();
        using var restored=Open(root,"second");Assert(restored.GetInfo("docs/b.txt")!.Length==1100);Assert(restored.GetInfoById(restored.VaultId).IsDirectory);using var rootLease=restored.AcquireOpenById(restored.VaultId);
        v.Rename("docs","DOCS",false);v.FlushAsync().GetAwaiter().GetResult();using var again=Open(root,"third");Assert(again.Enumerate("").Single().Name=="DOCS","Local "+v.Enumerate("").Single().Name+" remote "+again.Enumerate("").Single().Name);
    } finally{Directory.Delete(root,true);}}
static void Credentials() {
    var root=Temp();try {byte[] master;using(var v=Create(root)){v.CreateFile("secret-name.txt");v.WriteRange("secret-name.txt",0,"secret plaintext marker"u8);v.FlushAsync().GetAwaiter().GetResult();master=v.ExportMasterKey();}
        using(var c=VaultCredentials.Password("wrong"))Throws<CryptographicException>(()=>VaultEngine.Open(Options(root),c));
        using(var v=VaultEngine.OpenWithMasterKey(Options(root,"master"),master))Equal("secret plaintext marker"u8.ToArray(),Read(v,"secret-name.txt"));
        Throws<CryptographicException>(()=>VaultEngine.OpenWithMasterKey(Options(root,"bad-master"),RandomNumberGenerator.GetBytes(32)));
        foreach(var file in Directory.EnumerateFiles(root,"*",SearchOption.AllDirectories)) {var raw=File.ReadAllBytes(file);Assert(!Encoding.UTF8.GetString(raw).Contains("secret-name.txt")&&!Encoding.UTF8.GetString(raw).Contains("secret plaintext marker"),"Plaintext leaked to filesystem.");}
        var keyRoot=Path.Combine(root,"keyvault");var bytes=VaultCredentials.GenerateKeyFile();using var cred=VaultCredentials.KeyFile(bytes);using(var v=VaultEngine.Create(Options(keyRoot),cred)){v.CreateFile("key.bin");v.FlushAsync().GetAwaiter().GetResult();}using var opened=VaultEngine.Open(Options(keyRoot),cred);Assert(opened.GetInfo("key.bin")!=null);Throws<ArgumentException>(()=>VaultCredentials.KeyFile(new byte[31]));
    } finally{Directory.Delete(root,true);}}
static void Paths() {foreach(var path in new[]{"../a","a/../b","a//b","C:/a","con.txt","LPT1","com².dat","a.","a ","a?b","//server/a"})Throws<ArgumentException>(()=>VaultPath.Normalize(path));Assert(VaultPath.Normalize("\\docs\\a")=="docs/a");var root=Temp();try{using var v=Create(root);v.CreateFile("Readme.txt");Throws<IOException>(()=>v.CreateFile("README.TXT"));}finally{Directory.Delete(root,true);}}
static void Caps() {var root=Temp();try{using var v=Create(root,140000);v.CreateFile("cap.bin");var bytes=RandomNumberGenerator.GetBytes(300000);v.WriteRange("cap.bin",0,bytes);v.FlushAsync().GetAwaiter().GetResult();Assert(v.GetInfo("cap.bin")!.PartCount<5,"Records were not packed.");foreach(var p in Directory.EnumerateFiles(Path.Combine(root,"source","parts")))Assert(new FileInfo(p).Length<=140000);v.SetPartSize(1024);Assert(v.GetInfo("cap.bin")!.PartSizeBytes==140000);v.WriteRange("cap.bin",0,new byte[]{42});bytes[0]=42;Assert(v.GetInfo("cap.bin")!.PartSizeBytes==1024);v.FlushAsync().GetAwaiter().GetResult();Equal(bytes,Read(v,"cap.bin"));var prior=Directory.GetFiles(Path.Combine(root,"source","parts")).Length;v.ResplitAsync("cap.bin",4096).GetAwaiter().GetResult();Assert(v.GetInfo("cap.bin")!.PartSizeBytes==4096);Equal(bytes,Read(v,"cap.bin"));Assert(Directory.GetFiles(Path.Combine(root,"source","parts")).Length>prior,"Previous objects were deleted.");foreach(var p in Directory.EnumerateFiles(Path.Combine(root,"source","parts")))Assert(new FileInfo(p).Length<=140000);Throws<ArgumentOutOfRangeException>(()=>v.SetPartSize(1023));Throws<ArgumentOutOfRangeException>(()=>v.SetPartSize(1073741825));}finally{Directory.Delete(root,true);}}
static void Tamper() {var root=Temp();try{using var v=Create(root);v.CreateFile("t.bin");v.WriteRange("t.bin",0,RandomNumberGenerator.GetBytes(2000));v.FlushAsync().GetAwaiter().GetResult();foreach(var p in Directory.EnumerateFiles(Path.Combine(root,"cache","parts"))){var bytes=File.ReadAllBytes(p);bytes[^1]^=1;File.WriteAllBytes(p,bytes);}Assert(Read(v,"t.bin").Length==2000,"Clean cache did not recover from authenticated source."); foreach(var folder in new[]{"cache","source"})foreach(var p in Directory.EnumerateFiles(Path.Combine(root,folder,"parts"))){var bytes=File.ReadAllBytes(p);bytes[^1]^=1;File.WriteAllBytes(p,bytes);} Throws<CryptographicException>(()=>Read(v,"t.bin"));}finally{Directory.Delete(root,true);}}
static void Offline() {var root=Temp();try{using(var v=Create(root)){v.CreateFile("offline.txt");v.WriteRange("offline.txt",0,"available offline"u8);v.FlushAsync().GetAwaiter().GetResult();v.SetPinnedAsync("offline.txt",true).GetAwaiter().GetResult();}Directory.Move(Path.Combine(root,"source"),Path.Combine(root,"away"));
        var executable=Environment.ProcessPath!;var assembly=System.Reflection.Assembly.GetExecutingAssembly().Location;var psi=new System.Diagnostics.ProcessStartInfo(executable){UseShellExecute=false};if(Path.GetFileNameWithoutExtension(executable)=="dotnet")psi.ArgumentList.Add(assembly);psi.ArgumentList.Add("crash-write");psi.ArgumentList.Add(root);using(var child=System.Diagnostics.Process.Start(psi)!){child.WaitForExit();Assert(child.ExitCode==0);}
        using(var v=Open(root)){Equal("available offline"u8.ToArray(),Read(v,"offline.txt"));Equal("journal survives abrupt termination"u8.ToArray(),Read(v,"recovered.txt"));Assert(v.Status.PendingCommits>0&&!v.Status.IsSourceAvailable);Directory.Move(Path.Combine(root,"away"),Path.Combine(root,"source"));v.SyncAsync().GetAwaiter().GetResult();Assert(v.Status.PendingCommits==0&&v.Status.IsSourceAvailable);}using var remote=Open(root,"remote");Assert(remote.GetInfo("recovered.txt")!=null);
    }finally{Directory.Delete(root,true);}}
static void Conflicts() {var root=Temp();try{using(var initial=Create(root)){initial.CreateFile("shared.txt");initial.WriteRange("shared.txt",0,"base"u8);initial.FlushAsync().GetAwaiter().GetResult();}using var a=Open(root,"a");using var b=Open(root,"b");a.WriteRange("shared.txt",0,"AAAA"u8);b.WriteRange("shared.txt",0,"BBBB"u8);a.FlushAsync().GetAwaiter().GetResult();b.FlushAsync().GetAwaiter().GetResult();a.SyncAsync().GetAwaiter().GetResult();b.SyncAsync().GetAwaiter().GetResult();var views=a.Enumerate("").Select(i=>Encoding.UTF8.GetString(Read(a,i.Path))).Order().ToArray();Assert(views.SequenceEqual(new[]{"AAAA","BBBB"}));Assert(a.Enumerate("").Select(x=>x.Path).SequenceEqual(b.Enumerate("").Select(x=>x.Path)),"Devices diverged."); Assert(a.Enumerate("").Select(x=>x.EntryId).Distinct().Count()==2,"Conflicts share a handle identity."); foreach(var info in a.Enumerate("")){var bytes=new byte[4];Assert(a.ReadRangeById(info.EntryId,0,bytes)==4);Equal(Read(a,info.Path),bytes);}}finally{Directory.Delete(root,true);}}
static void Incomplete() {var root=Temp();try{using(var initial=Create(root)){initial.CreateFile("version.txt");initial.WriteRange("version.txt",0,"old"u8);initial.FlushAsync().GetAwaiter().GetResult();}using var reader=Open(root,"reader");var oldParts=Directory.GetFiles(Path.Combine(root,"source","parts")).ToHashSet();using(var writer=Open(root,"writer")){writer.WriteRange("version.txt",0,"new version"u8);writer.FlushAsync().GetAwaiter().GetResult();}var newest=Directory.GetFiles(Path.Combine(root,"source","parts")).Single(p=>!oldParts.Contains(p));var held=newest+".held";File.Move(newest,held);reader.SyncAsync().GetAwaiter().GetResult();Equal("old"u8.ToArray(),Read(reader,"version.txt"));Assert(reader.Status.PendingIncomingCommits>0);File.Move(held,newest);reader.SyncAsync().GetAwaiter().GetResult();Equal("new version"u8.ToArray(),Read(reader,"version.txt"));}finally{Directory.Delete(root,true);}}
static void Eviction() {var root=Temp();try{using var v=Create(root);v.CreateFile("pinned");v.WriteRange("pinned",0,"keep"u8);v.FlushAsync().GetAwaiter().GetResult();v.SetPinnedAsync("pinned",true).GetAwaiter().GetResult();Assert(v.EvictCache(long.MaxValue)==0);v.SetPinnedAsync("pinned",false).GetAwaiter().GetResult();using(var lease=v.AcquireOpen("pinned"))Assert(v.EvictCache(long.MaxValue)==0);v.WriteRange("pinned",0,"dirty"u8);Assert(v.EvictCache(long.MaxValue)>=0);Equal("dirty"u8.ToArray(),Read(v,"pinned"));v.FlushAsync().GetAwaiter().GetResult();Assert(v.EvictCache(long.MaxValue)>0);Equal("dirty"u8.ToArray(),Read(v,"pinned"));}finally{Directory.Delete(root,true);}}

static void DirectoryConflict() {var root=Temp();try{using(var initial=Create(root)){initial.CreateDirectory("d");initial.CreateFile("d/f");initial.WriteRange("d/f",0,"base"u8);initial.FlushAsync().GetAwaiter().GetResult();}using var a=Open(root,"a");using var b=Open(root,"b");a.Delete("d",true);b.WriteRange("d/f",0,"edit"u8);a.FlushAsync().GetAwaiter().GetResult();b.FlushAsync().GetAwaiter().GetResult();a.SyncAsync().GetAwaiter().GetResult();b.SyncAsync().GetAwaiter().GetResult();Assert(a.Enumerate("").Any(i=>i.Name=="d"),"Surviving edit parent is missing.");Equal("edit"u8.ToArray(),Read(a,"d/f"));Equal(Read(a,"d/f"),Read(b,"d/f"));}finally{Directory.Delete(root,true);}}
static void RemoteOpen() {var root=Temp();try{using(var initial=Create(root)){initial.CreateFile("open");initial.WriteRange("open",0,"open bytes"u8);initial.FlushAsync().GetAwaiter().GetResult();}using var a=Open(root,"a");using var b=Open(root,"b");var id=a.GetInfo("open")!.EntryId;using var lease=a.AcquireOpenById(id);b.Delete("open");b.FlushAsync().GetAwaiter().GetResult();a.SyncAsync().GetAwaiter().GetResult();Assert(a.GetInfo("open")==null);var bytes=new byte[10];Assert(a.ReadRangeById(id,0,bytes)==10);Equal("open bytes"u8.ToArray(),bytes);}finally{Directory.Delete(root,true);}}
static void Links() {var root=Temp();try{Directory.CreateDirectory(Path.Combine(root,"source"));Directory.CreateSymbolicLink(Path.Combine(root,"cache"),Path.Combine(root,"source"));Throws<ArgumentException>(()=>Create(root));Directory.Delete(Path.Combine(root,"cache"));Directory.CreateDirectory(Path.Combine(root,"cache"));Directory.CreateDirectory(Path.Combine(root,"source","parts"));Directory.CreateSymbolicLink(Path.Combine(root,"cache","parts"),Path.Combine(root,"source","parts"));Throws<ArgumentException>(()=>Create(root));}finally{Directory.Delete(root,true);}}
static void FolderPin() {var root=Temp();try{using var v=Create(root);v.CreateDirectory("p");v.SetPinnedAsync("p",true).GetAwaiter().GetResult();v.CreateFile("p/new");v.WriteRange("p/new",0,"pinned child"u8);v.SetLength("p/new",1L<<40);Assert(v.GetInfo("p/new")!.IsPinned);var tail=new byte[20];Assert(v.ReadRange("p/new",(1L<<40)-20,tail)==20);Assert(tail.All(b=>b==0));v.FlushAsync().GetAwaiter().GetResult();Assert(v.EvictCache(long.MaxValue)==0);v.SetPinnedAsync("p",false).GetAwaiter().GetResult();Assert(!v.GetInfo("p/new")!.IsPinned);}finally{Directory.Delete(root,true);}}
