/** Public source copy inventory. Values are Cantonese, not generated placeholders. */
export const APPEARANCE_COPY = Object.freeze({
 'Appearance':'外觀','Element appearance':'元素外觀','Close':'關閉','Search appearance controls':'搜尋外觀設定','The application search adapter is unavailable.':'應用程式搜尋介面暫時未能使用。','The operation could not be completed.':'未能完成操作，請檢查輸入再試。',
 'normal':'一般','hover':'滑鼠停留','focus':'焦點','active':'按下','selected':'已選取','disabled':'停用','dragged':'拖動中','invalid':'無效','loading':'載入中','success':'成功','warning':'警告','error':'錯誤','none':'不繼承',
 'Base':'基本','Layer':'圖層','Group':'群組','Adjustment':'調整','Hide':'隱藏','Show':'顯示','Unlock layer':'解鎖圖層','Lock layer':'鎖定圖層','Open group':'開啟群組','Unlock this group before editing its children.':'請先解鎖群組，先至可以編輯入面嘅圖層。','Back to parent group':'返回上一層群組','Add group':'新增群組','Add adjustment layer':'新增調整圖層','Preview':'預覽','before':'修改前','after':'修改後','Show before':'顯示修改前','Show after':'顯示修改後','Inherit state':'繼承狀態',
 'Selection mask':'選取遮罩','rectangle':'矩形','ellipse':'橢圓形','polygon':'多邊形','luminance-range':'亮度範圍','color-range':'顏色範圍','SVG path':'SVG 路徑','Clear selection':'清除選取範圍','SVG path numeric geometry':'SVG 路徑數值幾何','coordinate':'座標',
 'Enable RGBA channels':'啟用 RGBA 色彩通道','Reset channels':'重設色彩通道','Red':'紅色','Green':'綠色','Blue':'藍色','Alpha':'透明度','channel gain':'通道增益','Add':'新增','Remove effect':'移除效果','Move effect up':'將效果上移',
 'blur':'模糊','brightness':'亮度','contrast':'對比','saturate':'飽和度','grayscale':'灰階','sepia':'懷舊棕色','invert':'反相','hue-rotate':'色相旋轉','opacity':'不透明度',
 'Superscript':'上標','Subscript':'下標','Normal baseline':'一般基線','Single underline':'單底線','Double underline':'雙底線','Wavy underline':'波浪底線','Strikethrough':'刪除線','Double strikethrough':'雙刪除線','Overline':'頂線','Small caps':'小型大寫字','Text outline':'文字外框','Text glow':'文字光暈','Layered shadow':'多重陰影',
 'Add layer':'新增圖層','Duplicate layer':'複製圖層','Move layer up':'將圖層上移','Move layer down':'將圖層下移','Remove layer':'移除圖層','Layer name':'圖層名稱','Load installed fonts':'載入已安裝字型','Reset':'重設','Lock property':'鎖定屬性','continuous spectrum':'連續色譜','Animated rainbow':'動態彩虹','Rainbow':'彩虹','Undo':'復原','Redo':'取消復原','Reset layer':'重設圖層','Reset state':'重設狀態','Reset element':'重設元素','Copy style':'複製樣式','Paste style':'貼上樣式','Preset name':'預設組合名稱','Save preset':'儲存預設組合','Apply':'套用','Export appearance':'匯出外觀','Import appearance JSON':'匯入外觀 JSON','Reset all appearance':'重設全部外觀','Edit appearance…':'編輯外觀…','Lock this element…':'鎖定呢個元素…',
 'color':'文字顏色','backgroundColor':'背景顏色','fontFamily':'字型','fontSize':'字體大小','fontWeight':'字重','fontStyle':'字體樣式','fontVariant':'字體變體','fontVariationSettings':'可變字型設定','textDecorationLine':'文字裝飾線','textDecorationStyle':'裝飾線樣式','textDecorationColor':'裝飾線顏色','textTransform':'大小寫轉換','textAlign':'文字對齊','direction':'文字方向','letterSpacing':'字元間距','wordSpacing':'字詞間距','lineHeight':'行高','verticalAlign':'垂直對齊','webkitTextStroke':'文字描邊','textShadow':'文字陰影','border':'邊框','borderRadius':'圓角半徑','padding':'內邊距','margin':'外邊距','width':'闊度','height':'高度','minWidth':'最小闊度','maxWidth':'最大闊度','boxShadow':'方框陰影','backgroundImage':'背景圖像','backgroundSize':'背景大小','backgroundPosition':'背景位置','mixBlendMode':'混合模式','filter':'濾鏡','backdropFilter':'背景濾鏡','transform':'變形','transformOrigin':'變形原點','clipPath':'裁剪路徑','maskImage':'遮罩圖像','transition':'過渡效果',
 'Numeric control is outside its bounds.':'數值超出允許範圍。','Rectangle exceeds element bounds.':'矩形超出元素邊界。','Polygon needs 3–32 points.':'多邊形需要 3 至 32 個點。','Invalid bounded SVG path.':'SVG 路徑無效或超出限制。','Range minimum exceeds maximum.':'範圍最小值大過最大值。','Color range needs red, green, blue and tolerance.':'顏色範圍需要紅、綠、藍同容差數值。','Unknown selection type.':'未能辨認選取類型。','Invalid layer or group depth.':'圖層無效或群組層數超出限制。','Unsupported property':'未支援嘅屬性','Unsafe appearance value.':'外觀數值未通過安全檢查。','Invalid group children.':'群組入面嘅圖層無效。','Unknown layer kind.':'未能辨認圖層種類。','Channels require RGBA gains.':'色彩通道需要 RGBA 增益數值。','Too many effects.':'效果數目太多。','Unsupported effect.':'未支援呢種效果。','Appearance nesting exceeds bounds.':'外觀設定層數超出限制。','Unsafe appearance key.':'外觀設定鍵未通過安全檢查。','Invalid or oversized appearance file.':'外觀檔案無效或太大。','Too many appearance targets.':'外觀目標數目太多。','Invalid element.':'元素無效。','Invalid state layers.':'狀態圖層無效。','Too many presets.':'預設組合數目太多。','Inheritance target is missing.':'搵唔到繼承目標。','Invalid state inheritance.':'狀態繼承設定無效。','State inheritance cycle.':'狀態繼承出現循環。','Saved appearance could not be loaded.':'未能載入已儲存嘅外觀。','Appearance could not be saved.':'未能儲存外觀。','Installed font discovery is unavailable.':'暫時未能取得已安裝字型。','Value is unsupported by this renderer.':'目前嘅顯示引擎未支援呢個數值。','Invalid copied style.':'複製嘅樣式無效。','Appearance file is too large.':'外觀檔案太大。',
 'Use #RRGGBB or #RRGGBBAA.':'請輸入 #RRGGBB 或 #RRGGBBAA。','Use HEX, RGB, HSL, Lab, LCH, OKLab or OKLCH.':'請使用 HEX、RGB、HSL、Lab、LCH、OKLab 或 OKLCH。','Invalid color channels.':'色彩通道數值無效。','Color is outside the sRGB gamut or alpha range.':'顏色超出 sRGB 色域或透明度範圍。',
 'Application logo':'應用程式標誌','Choose a local logo':'選擇本機標誌圖像','Logo preview':'標誌預覽','Fit':'配合方式','contain':'完整顯示','cover':'填滿範圍','Horizontal focal point':'水平焦點','Vertical focal point':'垂直焦點','Converting locally…':'正在本機轉換…','Converted to 128 × 128 PNG locally. Metadata and color profile are flattened.':'已在本機轉成 128 × 128 PNG。中繼資料同色彩描述檔已扁平化。','Reset logo':'重設標誌','Original logo restored.':'已還原原本標誌。','Saved logo unavailable.':'未能讀取已儲存嘅標誌。','Image exceeds 4 MiB.':'圖像超過 4 MiB。','Malformed PNG.':'PNG 格式損壞。','Animated images are unsupported.':'未支援動態圖像。','Only static PNG, JPEG and WebP images are supported.':'只支援靜態 PNG、JPEG 同 WebP 圖像。','Isolated image decoding is unavailable.':'隔離圖像解碼暫時未能使用。','Decoded image exceeds size bounds.':'解碼後嘅圖像超出大小限制。','Canvas conversion unavailable.':'畫布轉換暫時未能使用。','PNG conversion failed.':'PNG 轉換失敗。',
 'Unavailable: freehand pointer drawing, perceptual color-distance selections, smart objects, warp mesh and image layer import. Color-range masks select an axis-aligned RGB tolerance range, not perceptual distance. Groups organize and cascade child styles; they do not create independent pixel surfaces. Luminance range masks use SVG alpha filtering. CSS masks, transforms and effects apply to the entire target.':'暫未提供徒手繪畫、感知色差選取、智慧物件、網格扭曲同圖像圖層匯入。顏色遮罩按 RGB 通道容差選取，唔係感知色差。群組會整理同依次套用子圖層樣式，唔會建立獨立像素畫面。亮度遮罩使用 SVG 透明度濾鏡。CSS 遮罩、變形同效果會套用到整個目標。'
});
export const APPEARANCE_COPY_KEYS=Object.freeze(Object.keys(APPEARANCE_COPY));
export function appearanceTranslator(translate){return (source,options={})=>{
 if(source.startsWith('Unsupported property: '))return `${translate?.('Unsupported property',options)||'Unsupported property'}: ${source.slice(22)}`;
 const numbered=/^(Layer|Group) (\d+)$/.exec(source);if(numbered)return `${translate?.(numbered[1],options)||numbered[1]} ${numbered[2]}`;
 if(options.message&&!Object.hasOwn(APPEARANCE_COPY,source)){const explanation='The operation could not be completed.';return `${translate?.(explanation,options)||explanation} ${source}`;}
 return translate?.(source,options)||source;
};}
