import { RAINBOW, parseColor, parseColorEntry, colorRepresentations, contrastRatio, rainbowDuration } from './color.js';
export const STATES=['normal','hover','focus','active','selected','disabled','dragged','invalid','loading','success','warning','error'];
export const PROPERTIES={color:'#202020',backgroundColor:'#ffffff',opacity:'1',fontFamily:'Arial, sans-serif',fontSize:'16px',fontWeight:'400',fontStyle:'normal',fontVariant:'normal',fontVariationSettings:'normal',textDecorationLine:'none',textDecorationStyle:'solid',textDecorationColor:'#202020',textTransform:'none',textAlign:'start',direction:'ltr',letterSpacing:'0px',wordSpacing:'0px',lineHeight:'1.5',verticalAlign:'baseline',webkitTextStroke:'0px transparent',textShadow:'none',border:'0px solid transparent',borderRadius:'0px',padding:'0px',margin:'0px',width:'auto',height:'auto',minWidth:'0px',maxWidth:'none',boxShadow:'none',backgroundImage:'none',backgroundSize:'auto',backgroundPosition:'center',mixBlendMode:'normal',filter:'none',backdropFilter:'none',transform:'none',transformOrigin:'center',clipPath:'none',maskImage:'none',transition:'none'};
export function defaultAppearance(){return {version:1,elements:{},presets:{},rainbowLevel:5};}
export function newLayer(name='Layer'){return {name:String(name).slice(0,80),visible:true,locked:false,properties:{}};}
export function validateAppearance(value){
 const inspect=(node,depth=0)=>{if(depth>12)throw new Error('Appearance nesting exceeds bounds.');if(node&&typeof node==='object')for(const key of Object.keys(node)){if(['__proto__','constructor','prototype'].includes(key))throw new Error('Unsafe appearance key.');inspect(node[key],depth+1);}};inspect(value);
 if(!value||value.version!==1||!value.elements||typeof value.elements!=='object'||Array.isArray(value.elements)||JSON.stringify(value).length>300000)throw new Error('Invalid or oversized appearance file.');
 const out=defaultAppearance();out.rainbowLevel=Math.max(1,Math.min(10,Number(value.rainbowLevel)||5));
 if(Object.keys(value.elements).length>1000)throw new Error('Too many appearance targets.');
 for(const [id,states]of Object.entries(value.elements)){if(!id.length||id.length>500||/[\x00-\x1f\x7f]/.test(id)||!states||typeof states!=='object'||Array.isArray(states))throw new Error('Invalid element.');out.elements[id]={};for(const [state,layers]of Object.entries(states)){if(!STATES.includes(state)||!Array.isArray(layers)||!layers.length||layers.length>32)throw new Error('Invalid state layers.');out.elements[id][state]=layers.map(layer=>{if(!layer||typeof layer!=='object'||Array.isArray(layer))throw new Error('Invalid layer.');const result=newLayer(layer.name);result.visible=layer.visible!==false;result.locked=layer.locked===true;for(const [key,val]of Object.entries(layer.properties||{})){if(!Object.hasOwn(PROPERTIES,key))throw new Error(`Unsupported property: ${key}`);if(val?.kind==='rainbow'&&(key==='color'||key==='backgroundColor'))result.properties[key]={...RAINBOW};else if(typeof val==='string'&&val.length<=500&&!/[{};<>]|url\s*\(|expression\s*\(|@import/i.test(val))result.properties[key]=val;else throw new Error('Unsafe appearance value.');}return result;});}}
 for(const [name,layers] of Object.entries(value.presets||{})){if(name.length>80||Object.keys(out.presets).length>=50)throw new Error('Too many presets.');const validated=validateAppearance({version:1,elements:{preset:{normal:layers}}});out.presets[name]=validated.elements.preset.normal;}
 return out;
}
export function mergedProperties(layers=[]){return Object.assign({},...layers.filter(l=>l.visible).map(l=>l.properties));}
const kebab=s=>s.replace(/[A-Z]/g,c=>`-${c.toLowerCase()}`);
export function mountAppearanceEditor(root,services={}) {
 const doc=root.ownerDocument||document, storage=services.storage||globalThis.localStorage,key='m4e.appearance.v1',disposers=[];let state=defaultAppearance(),target,selectedState='normal',layerIndex=0,undo=[],redo=[],counter=0;
 try{const saved=storage?.getItem(key);if(saved)state=validateAppearance(JSON.parse(saved));}catch{services.notify?.('Saved appearance could not be loaded.');}
 const style=doc.createElement('style');style.dataset.appearanceRules='true';doc.head.append(style);
 const panel=doc.createElement('section');panel.className='appearance-editor';panel.hidden=true;panel.setAttribute('role','dialog');panel.setAttribute('aria-modal','false');panel.setAttribute('aria-label','Element appearance');doc.body.append(panel);
 function idFor(el){if(!el.dataset.appearanceId){const path=[];let node=el;while(node&&node!==root){path.unshift(`${node.tagName.toLowerCase()}:${Array.from(node.parentElement?.children||[]).indexOf(node)}`);node=node.parentElement;}el.dataset.appearanceId=el.id?`id:${el.id}`:`path:${path.join('/')}`;}return el.dataset.appearanceId;}
 function apply(){const rules=[];for(const [id,states]of Object.entries(state.elements)){const selector=`[data-appearance-id="${CSS.escape(id)}"]`;for(const [s,layers]of Object.entries(states)){const pseudo={normal:'',hover:':hover',focus:':focus-visible',active:':active',selected:'[aria-selected="true"]',disabled:':is(:disabled,[aria-disabled="true"])',dragged:'[aria-grabbed="true"]',invalid:':is(:invalid,[aria-invalid="true"])',loading:'[aria-busy="true"]',success:'[data-state="success"]',warning:'[data-state="warning"]',error:'[data-state="error"]'}[s];const properties=mergedProperties(layers);const declarations=[];for(const [k,v]of Object.entries(properties)){if(v?.kind==='rainbow'){declarations.push(`${kebab(k)}:var(--appearance-rainbow) !important`,`animation:appearance-rainbow var(--appearance-rainbow-duration) linear infinite !important`);}else declarations.push(`${kebab(k)}:${v} !important`);}rules.push(`${selector}${pseudo}{${declarations.join(';')}}`);}}style.textContent=rules.join('\n');doc.documentElement.style.setProperty('--appearance-rainbow-duration',rainbowDuration(state.rainbowLevel));}
 function save(){try{storage?.setItem(key,JSON.stringify(state));services.onChange?.(structuredClone(state));apply();}catch{services.notify?.('Appearance could not be saved.');}}
 function mutate(fn){undo.push(JSON.stringify(state));if(undo.length>50)undo.shift();redo=[];fn();save();render();}
 function button(label,action){const b=doc.createElement('button');b.type='button';b.textContent=services.translate?.(label,label)||label;b.onclick=action;return b;}
 function search(parent,scope){const input=doc.createElement('input');input.type='search';input.placeholder='Search appearance controls';input.setAttribute('aria-label',input.placeholder);parent.append(input);if(services.attachSearch){const cleanup=services.attachSearch(input,scope);if(typeof cleanup==='function')disposers.push(cleanup);}else{input.disabled=true;input.title='The application search adapter is unavailable.';}return input;}
 function layers(){const id=idFor(target);state.elements[id]??={};state.elements[id][selectedState]??=[newLayer('Base')];return state.elements[id][selectedState];}
 function close(){panel.hidden=true;target?.focus?.({preventScroll:true});}
 function position(){if(panel.hidden||!target)return;const r=target.getBoundingClientRect(),w=Math.min(450,innerWidth-24),h=Math.min(650,innerHeight-24);panel.style.width=`${w}px`;panel.style.maxHeight=`${h}px`;panel.style.left=`${Math.max(12,Math.min(innerWidth-w-12,r.right+8))}px`;panel.style.top=`${Math.max(12,Math.min(innerHeight-h-12,r.top))}px`;}
 function render(){if(!target)return;panel.replaceChildren();const heading=doc.createElement('h2');heading.textContent=`Appearance: ${target.getAttribute('aria-label')||target.id||target.tagName.toLowerCase()}`;panel.append(heading,button('Close',close));const content=doc.createElement('div');search(panel,content);panel.append(content);
 const states=doc.createElement('div');states.className='appearance-state-tabs';states.setAttribute('role','tablist');for(const s of STATES){const b=button(s,()=>{selectedState=s;layerIndex=0;render();});b.setAttribute('role','tab');b.setAttribute('aria-selected',String(s===selectedState));states.append(b);}content.append(states);
 const current=layers();layerIndex=Math.min(layerIndex,current.length-1);const selected=current[layerIndex];const list=doc.createElement('div');list.className='appearance-layers';for(const [i,l]of current.entries()){const row=doc.createElement('div');row.append(button(`${i+1}. ${l.name}`,()=>{layerIndex=i;render();}),button(l.visible?'Hide':'Show',()=>mutate(()=>l.visible=!l.visible)),button(l.locked?'Unlock layer':'Lock layer',()=>mutate(()=>l.locked=!l.locked)));list.append(row);}content.append(list);
 content.append(button('Add layer',()=>mutate(()=>{if(current.length<32){current.push(newLayer(`Layer ${current.length+1}`));layerIndex=current.length-1;}})),button('Duplicate layer',()=>mutate(()=>{if(current.length<32){current.splice(layerIndex+1,0,structuredClone(selected));layerIndex++;}})),button('Move layer up',()=>mutate(()=>{if(layerIndex>0){[current[layerIndex-1],current[layerIndex]]=[current[layerIndex],current[layerIndex-1]];layerIndex--;}})),button('Move layer down',()=>mutate(()=>{if(layerIndex<current.length-1){[current[layerIndex+1],current[layerIndex]]=[current[layerIndex],current[layerIndex+1]];layerIndex++;}})));
 content.append(button('Remove layer',()=>mutate(()=>{if(!selected.locked&&current.length>1){current.splice(layerIndex,1);layerIndex=Math.max(0,layerIndex-1);}})));const name=doc.createElement('input');name.disabled=selected.locked;name.value=selected.name;name.setAttribute('aria-label','Layer name');name.onchange=()=>mutate(()=>selected.name=name.value.slice(0,80));content.append(name);
 content.append(button('Load installed fonts',async()=>{try{const fonts=services.listFonts?await services.listFonts():globalThis.queryLocalFonts?await globalThis.queryLocalFonts():null;if(!fonts)throw new Error('Installed font discovery is unavailable.');const families=[...new Set(fonts.map(f=>typeof f==='string'?f:f.family))].sort();const fontBox=doc.createElement('div');search(fontBox,fontBox);for(const family of families){const b=button(family,()=>mutate(()=>{if(!selected.locked)selected.properties.fontFamily=JSON.stringify(family)+', sans-serif';}));b.style.fontFamily=JSON.stringify(family)+', sans-serif';fontBox.append(b);}content.append(fontBox);}catch(e){services.notify?.(e.message);}}));for(const [property,fallback]of Object.entries(PROPERTIES)){const row=doc.createElement('label');row.className='appearance-property';row.dataset.searchText=property;row.append(doc.createTextNode(property));const input=doc.createElement('input');input.value=typeof selected.properties[property]==='string'?selected.properties[property]:fallback;input.disabled=selected.locked;input.setAttribute('aria-label',property);input.onchange=()=>{try{if(property==='color'||property==='backgroundColor'||property==='textDecorationColor')input.value=parseColorEntry(input.value);const candidate=structuredClone(state);candidate.elements[idFor(target)][selectedState][layerIndex].properties[property]=input.value;validateAppearance(candidate);if(globalThis.CSS?.supports&&!CSS.supports(kebab(property),input.value))throw new Error('Value is unsupported by this renderer.');mutate(()=>selected.properties[property]=input.value);}catch(e){input.setCustomValidity(e.message);input.reportValidity();}};row.append(input,button('Reset',()=>mutate(()=>{if(!selected.locked)delete selected.properties[property];})),button('Lock property',()=>services.onLock?.(target,{property,state:selectedState,layer:layerIndex})));
 if(property==='color'||property==='backgroundColor'){const picker=doc.createElement('input');picker.type='color';try{parseColor(input.value);picker.value=input.value.slice(0,7);}catch{picker.value=fallback;}picker.disabled=selected.locked;picker.setAttribute('aria-label',`${property} continuous spectrum`);picker.oninput=()=>{input.value=picker.value;};picker.onchange=()=>input.onchange();const readout=doc.createElement('output');try{const reps=colorRepresentations(input.value);readout.textContent=`${reps.rgb}; ${reps.hsl}; Lab ${reps.lab.map(n=>n.toFixed(3)).join(' ')}; OKLCH ${reps.oklch.map(n=>n.toFixed(3)).join(' ')}; contrast ${contrastRatio(input.value,property==='color'?'#ffffff':'#202020').toFixed(2)}:1`;}catch{readout.textContent='Animated rainbow';}row.append(picker,button('Rainbow',()=>mutate(()=>{if(!selected.locked)selected.properties[property]={...RAINBOW};})),readout);}content.append(row);}
 content.append(button('Undo',()=>{if(undo.length){redo.push(JSON.stringify(state));state=JSON.parse(undo.pop());save();render();}}),button('Redo',()=>{if(redo.length){undo.push(JSON.stringify(state));state=JSON.parse(redo.pop());save();render();}}),button('Reset layer',()=>mutate(()=>{if(!selected.locked)selected.properties={};})),button('Reset state',()=>mutate(()=>delete state.elements[idFor(target)][selectedState])),button('Reset element',()=>mutate(()=>delete state.elements[idFor(target)])),button('Copy style',()=>{services.clipboard=JSON.stringify(current);}),button('Paste style',()=>{if(services.clipboard)try{const c=defaultAppearance();c.elements.x={normal:JSON.parse(services.clipboard)};const valid=validateAppearance(c);mutate(()=>state.elements[idFor(target)][selectedState]=valid.elements.x.normal);}catch{services.notify?.('Invalid copied style.');}}));
 const presetName=doc.createElement('input');presetName.placeholder='Preset name';presetName.setAttribute('aria-label','Preset name');content.append(presetName,button('Save preset',()=>{const n=presetName.value.trim().slice(0,80);if(n&&Object.keys(state.presets).length<50){state.presets[n]=structuredClone(current);save();render();}}));for(const [n,preset]of Object.entries(state.presets))content.append(button(`Apply ${n}`,()=>mutate(()=>state.elements[idFor(target)][selectedState]=structuredClone(preset))));
 content.append(button('Export appearance',()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=doc.createElement('a');link.href=url;link.download='appearance.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}));const upload=doc.createElement('input');upload.type='file';upload.accept='application/json';upload.setAttribute('aria-label','Import appearance JSON');upload.onchange=async()=>{const file=upload.files?.[0];if(!file)return;try{if(file.size>300000)throw new Error('Appearance file is too large.');const imported=validateAppearance(JSON.parse(await file.text()));mutate(()=>state=imported);}catch(e){services.notify?.(e.message);}};content.append(upload,button('Reset all appearance',()=>mutate(()=>state=defaultAppearance())));
 const capability=doc.createElement('p');capability.textContent='Unavailable: freehand/path selection drawing, channels, smart objects, warp mesh, font discovery, LAB/OKLAB color entry, and image layer import. CSS gradients, masks, transforms and effects accept validated CSS values above.';content.append(capability);position();}
 function open(el){if(!el||!root.contains(el))return;target=el;selectedState='normal';layerIndex=0;idFor(el);panel.hidden=false;render();panel.querySelector('button')?.focus();}
 const menu=doc.createElement('div');menu.className='appearance-context';menu.hidden=true;menu.setAttribute('role','menu');doc.body.append(menu);
 function context(event){event.preventDefault();if(event.shiftKey){open(event.target);return;}target=event.target;menu.replaceChildren();const actions=doc.createElement('div');search(menu,actions);actions.append(button('Edit appearance…',()=>{menu.hidden=true;open(target);}),button('Lock this element…',()=>{menu.hidden=true;services.onLock?.(target);}));menu.append(actions);menu.hidden=false;menu.style.left=`${Math.max(0,Math.min(innerWidth-280,event.clientX))}px`;menu.style.top=`${Math.max(0,Math.min(innerHeight-150,event.clientY))}px`;menu.querySelector('input,button')?.focus();}
 const keyboard=e=>{if(e.key==='Escape'){menu.hidden=true;close();}else if(e.shiftKey&&e.key==='F10'){context({target:e.target,clientX:e.target.getBoundingClientRect().left,clientY:e.target.getBoundingClientRect().bottom,preventDefault:()=>e.preventDefault()});}else if(e.ctrlKey&&e.altKey&&e.key.toLowerCase()==='a'){e.preventDefault();open(e.target);}};
 root.addEventListener('contextmenu',context);panel.addEventListener('contextmenu',event=>{event.preventDefault();open(event.target);});doc.addEventListener('keydown',keyboard);globalThis.addEventListener('resize',position);doc.addEventListener('scroll',position,true);
 for(const el of root.querySelectorAll('*'))idFor(el);apply();
 return {open,apply,getState:()=>structuredClone(state),setState:value=>{state=validateAppearance(value);save();if(target)render();},reset:()=>{state=defaultAppearance();save();},destroy:()=>{root.removeEventListener('contextmenu',context);root.removeEventListener('keydown',keyboard);doc.removeEventListener('keydown',keyboard);globalThis.removeEventListener('resize',position);doc.removeEventListener('scroll',position,true);disposers.forEach(fn=>fn());panel.remove();menu.remove();style.remove();}};
}
