/** Public source copy inventory. Values are Cantonese, not generated placeholders. */
const BASE_COPY = Object.freeze({
 'Add local image layer':'新增本機圖像圖層','Image':'圖像','Too many image layers.':'圖像圖層數目太多。','Non-destructive image transform':'保留原圖嘅圖像變形','Image blend mode':'圖像混合模式','Reset image transform':'重設圖像變形',
 'x':'水平位置','y':'垂直位置','scaleX':'水平縮放','scaleY':'垂直縮放','rotate':'旋轉角度','skewX':'水平斜切','skewY':'垂直斜切','Crop left':'裁剪左邊','Crop top':'裁剪頂部','Crop width':'裁剪闊度','Crop height':'裁剪高度','multiply':'色彩增值','screen':'濾色','overlay':'疊加','darken':'變暗','lighten':'變亮','difference':'差異',
 'Invalid static PNG image.':'靜態 PNG 圖像無效。','PNG exceeds 4 MiB.':'PNG 超過 4 MiB。','PNG dimensions exceed the supported bounds.':'PNG 尺寸超出支援範圍。','Animated PNG images are unsupported.':'未支援動態 PNG 圖像。','Normalized PNG exceeds 1 MiB.':'轉換後嘅 PNG 超過 1 MiB。','PNG source metadata does not match the image.':'PNG 原始資料同圖像內容唔相符。','Image decoding is unavailable.':'圖像解碼暫時未能使用。','Decoded PNG dimensions do not match its header.':'解碼後嘅 PNG 尺寸同檔頭唔相符。','Canvas conversion is unavailable.':'畫布轉換暫時未能使用。','Normalized PNG dimensions changed.':'轉換後嘅 PNG 尺寸有變。','Unsafe export key.':'匯出設定鍵未通過安全檢查。','Image transform is outside its bounds.':'圖像變形數值超出允許範圍。','Invalid image blend mode.':'圖像混合模式無效。','Invalid image crop.':'圖像裁剪設定無效。',
 'Search drawing tools':'搜尋繪畫工具','Search state previews':'搜尋狀態預覽',
 'Draw selection…':'繪畫選取範圍…','Compare all states':'比較全部狀態','Selection workbench':'選取工作區','Draw with a pointer, or use arrows and Space to add points. Enter applies the selection; Escape clears it.':'用滑鼠繪畫，或者用方向鍵移動再按空白鍵加點。按 Enter 套用選取範圍，按 Escape 清除。','Selection drawing surface':'選取範圍畫布','Draw at least three points.':'請畫至少三個點。','Use at most twenty guides.':'最多可以加二十條參考線。','Invalid guide.':'參考線設定無效。','Selection applied.':'已套用選取範圍。','Apply freehand selection':'套用徒手選取範圍','Clear drawing':'清除繪畫','Vertical guide':'垂直參考線','Horizontal guide':'水平參考線','Remove guide':'移除參考線','Add vertical guide':'新增垂直參考線','Add horizontal guide':'新增水平參考線','State previews':'狀態預覽','Appearance samples only. Actions and private field values are not copied.':'呢度只係外觀樣本，唔會複製操作或者私人欄位內容。','Sample text':'文字樣本',
 'Appearance':'外觀','Element appearance':'元素外觀','Close':'關閉','Search appearance controls':'搜尋外觀設定','The application search adapter is unavailable.':'應用程式搜尋介面暫時未能使用。','The operation could not be completed.':'未能完成操作，請檢查輸入再試。',
 'normal':'一般','hover':'滑鼠停留','focus':'焦點','active':'按下','selected':'已選取','disabled':'停用','dragged':'拖動中','invalid':'無效','loading':'載入中','success':'成功','warning':'警告','error':'錯誤','none':'不繼承',
 'Base':'基本','Layer':'圖層','Group':'群組','Adjustment':'調整','Hide':'隱藏','Show':'顯示','Unlock layer':'解鎖圖層','Lock layer':'鎖定圖層','Open group':'開啟群組','Unlock this group before editing its children.':'請先解鎖群組，先至可以編輯入面嘅圖層。','Back to parent group':'返回上一層群組','Add group':'新增群組','Add adjustment layer':'新增調整圖層','Preview':'預覽','before':'修改前','after':'修改後','Show before':'顯示修改前','Show after':'顯示修改後','Inherit state':'繼承狀態',
 'Selection mask':'選取遮罩','rectangle':'矩形','ellipse':'橢圓形','polygon':'多邊形','luminance-range':'亮度範圍','color-range':'顏色範圍','SVG path':'SVG 路徑','Clear selection':'清除選取範圍','SVG path numeric geometry':'SVG 路徑數值幾何','coordinate':'座標',
 'Enable RGBA channels':'啟用 RGBA 色彩通道','Reset channels':'重設色彩通道','Red':'紅色','Green':'綠色','Blue':'藍色','Alpha':'透明度','channel gain':'通道增益','Add':'新增','Remove effect':'移除效果','Move effect up':'將效果上移',
 'blur':'模糊','brightness':'亮度','contrast':'對比','saturate':'飽和度','grayscale':'灰階','sepia':'懷舊棕色','invert':'反相','hue-rotate':'色相旋轉','opacity':'不透明度',
 'Superscript':'上標','Subscript':'下標','Normal baseline':'一般基線','Single underline':'單底線','Double underline':'雙底線','Wavy underline':'波浪底線','Strikethrough':'刪除線','Double strikethrough':'雙刪除線','Overline':'頂線','Small caps':'小型大寫字','Text outline':'文字外框','Text glow':'文字光暈','Layered shadow':'多重陰影',
 'Add layer':'新增圖層','Duplicate layer':'複製圖層','Move layer up':'將圖層上移','Move layer down':'將圖層下移','Remove layer':'移除圖層','Layer name':'圖層名稱','Load installed fonts':'載入已安裝字型','Reset':'重設','Lock property':'鎖定屬性','continuous spectrum':'連續色譜','Animated rainbow':'動態彩虹','Rainbow':'彩虹','Undo':'復原','Redo':'取消復原','Reset layer':'重設圖層','Reset state':'重設狀態','Reset element':'重設元素','Copy style':'複製樣式','Paste style':'貼上樣式','Preset name':'預設組合名稱','Save preset':'儲存預設組合','Apply':'套用','Export appearance':'匯出外觀','Import appearance JSON':'匯入外觀 JSON','Reset all appearance':'重設全部外觀','Edit appearance…':'編輯外觀…','Lock this element…':'鎖定呢個元素…',
 'color':'文字顏色','backgroundColor':'背景顏色','fontFamily':'字型','fontSize':'字體大小','fontWeight':'字重','fontStyle':'字體樣式','fontVariant':'字體變體','fontVariationSettings':'可變字型設定','textDecorationLine':'文字裝飾線','textDecorationStyle':'裝飾線樣式','textDecorationColor':'裝飾線顏色','textTransform':'大小寫轉換','textAlign':'文字對齊','direction':'文字方向','letterSpacing':'字元間距','wordSpacing':'字詞間距','lineHeight':'行高','verticalAlign':'垂直對齊','webkitTextStroke':'文字描邊','textShadow':'文字陰影','border':'邊框','borderRadius':'圓角半徑','padding':'內邊距','margin':'外邊距','width':'闊度','height':'高度','minWidth':'最小闊度','maxWidth':'最大闊度','boxShadow':'方框陰影','backgroundImage':'背景圖像','backgroundSize':'背景大小','backgroundPosition':'背景位置','mixBlendMode':'混合模式','filter':'濾鏡','backdropFilter':'背景濾鏡','transform':'變形','transformOrigin':'變形原點','clipPath':'裁剪路徑','maskImage':'遮罩圖像','transition':'過渡效果',
 'Numeric control is outside its bounds.':'數值超出允許範圍。','Rectangle exceeds element bounds.':'矩形超出元素邊界。','Polygon needs 3–32 points.':'多邊形需要 3 至 32 個點。','Invalid bounded SVG path.':'SVG 路徑無效或超出限制。','Range minimum exceeds maximum.':'範圍最小值大過最大值。','Color range needs red, green, blue and tolerance.':'顏色範圍需要紅、綠、藍同容差數值。','Unknown selection type.':'未能辨認選取類型。','Invalid layer or group depth.':'圖層無效或群組層數超出限制。','Unsupported property':'未支援嘅屬性','Unsafe appearance value.':'外觀數值未通過安全檢查。','Invalid group children.':'群組入面嘅圖層無效。','Unknown layer kind.':'未能辨認圖層種類。','Channels require RGBA gains.':'色彩通道需要 RGBA 增益數值。','Too many effects.':'效果數目太多。','Unsupported effect.':'未支援呢種效果。','Appearance nesting exceeds bounds.':'外觀設定層數超出限制。','Unsafe appearance key.':'外觀設定鍵未通過安全檢查。','Invalid or oversized appearance file.':'外觀檔案無效或太大。','Too many appearance targets.':'外觀目標數目太多。','Invalid element.':'元素無效。','Invalid state layers.':'狀態圖層無效。','Too many presets.':'預設組合數目太多。','Inheritance target is missing.':'搵唔到繼承目標。','Invalid state inheritance.':'狀態繼承設定無效。','State inheritance cycle.':'狀態繼承出現循環。','Saved appearance could not be loaded.':'未能載入已儲存嘅外觀。','Appearance could not be saved.':'未能儲存外觀。','Installed font discovery is unavailable.':'暫時未能取得已安裝字型。','Value is unsupported by this renderer.':'目前嘅顯示引擎未支援呢個數值。','Invalid copied style.':'複製嘅樣式無效。','Appearance file is too large.':'外觀檔案太大。',
 'Use #RRGGBB or #RRGGBBAA.':'請輸入 #RRGGBB 或 #RRGGBBAA。','Use HEX, RGB, HSL, Lab, LCH, OKLab or OKLCH.':'請使用 HEX、RGB、HSL、Lab、LCH、OKLab 或 OKLCH。','Invalid color channels.':'色彩通道數值無效。','Color is outside the sRGB gamut or alpha range.':'顏色超出 sRGB 色域或透明度範圍。',
 'Application logo':'應用程式標誌','Choose a local logo':'選擇本機標誌圖像','Logo preview':'標誌預覽','Fit':'配合方式','contain':'完整顯示','cover':'填滿範圍','Horizontal focal point':'水平焦點','Vertical focal point':'垂直焦點','Converting locally…':'正在本機轉換…','Converted to 128 × 128 PNG locally. Metadata and color profile are flattened.':'已在本機轉成 128 × 128 PNG。中繼資料同色彩描述檔已扁平化。','Reset logo':'重設標誌','Original logo restored.':'已還原原本標誌。','Saved logo unavailable.':'未能讀取已儲存嘅標誌。','Image exceeds 4 MiB.':'圖像超過 4 MiB。','Malformed PNG.':'PNG 格式損壞。','Animated images are unsupported.':'未支援動態圖像。','Only static PNG, JPEG and WebP images are supported.':'只支援靜態 PNG、JPEG 同 WebP 圖像。','Isolated image decoding is unavailable.':'隔離圖像解碼暫時未能使用。','Decoded image exceeds size bounds.':'解碼後嘅圖像超出大小限制。','Canvas conversion unavailable.':'畫布轉換暫時未能使用。','PNG conversion failed.':'PNG 轉換失敗。',
 'Unavailable: perceptual color-distance selections and mesh warp. Local PNG image layers preserve their normalized source; skew is an affine approximation, not mesh deformation. Image bytes are omitted from exported appearance files. Color-range masks select an axis-aligned RGB tolerance range, not perceptual distance. Groups organize and cascade child styles; they do not create independent pixel surfaces. Luminance range masks use SVG alpha filtering. CSS masks, transforms and effects apply to the entire target.':'暫未提供感知色差選取同網格扭曲。本機 PNG 圖像圖層會保留轉換後嘅原圖；斜切係仿射變形嘅近似效果，唔係網格扭曲。匯出外觀檔案唔會包含圖像資料。顏色遮罩按 RGB 通道容差選取，唔係感知色差。群組會整理同依次套用子圖層樣式，唔會建立獨立像素畫面。亮度遮罩使用 SVG 透明度濾鏡。CSS 遮罩、變形同效果會套用到整個目標。'
});
const EXTRA_COPY={
'Appearance storage rollback failed. Export the current style and reload before editing.':'外觀儲存回復失敗。請先匯出目前樣式，再重新載入後繼續編輯。','Appearance storage requires recovery.':'外觀儲存需要修復。',
'Rasterize group':'將群組轉成點陣預覽','Embed immutable source':'嵌入不可變更嘅來源','Show editable group':'顯示可編輯群組','Restore embedded source':'還原嵌入來源','Detach embedded copy':'分離嵌入副本','Triangle mesh warp':'三角網格扭曲','Mesh point':'網格點','Apply mesh warp':'套用網格扭曲','Reset mesh warp':'重設網格扭曲','Local appearance revisions':'本機外觀版本','Local revisions omit image pixels. Restoring creates a new revision.':'本機版本唔會記錄圖像像素。還原會建立新版本。','Detach the embedded copy before editing its source.':'請先分離嵌入副本，先可以編輯來源。','Invalid embedded source.':'嵌入來源無效。','Invalid bounded warp mesh.':'網格扭曲資料無效或超出限制。','Warp mesh contains a collapsed triangle.':'扭曲網格有塌縮嘅三角形。','Unsupported raster operation.':'未支援呢種點陣操作。','Raster dimensions exceed bounds.':'點陣尺寸超出限制。','Raster layer nesting exceeds bounds.':'點陣圖層層數超出限制。','Raster layer count exceeds bounds.':'點陣圖層數量超出限制。','Rasterization does not support channel gains.':'點陣預覽未支援通道增益。','Unsupported raster effect.':'未支援呢種點陣效果。','Invalid raster path.':'點陣路徑無效。','Rasterization does not support this selection type.':'點陣預覽未支援呢種選取方式。','Raster source bytes exceed bounds.':'點陣來源資料超出限制。','Rasterization supports background fills only; target typography remains live.':'點陣預覽只支援背景填色；目標文字仍然保留即時樣式。','Isolated image processing is unavailable.':'隔離圖像處理暫時未能使用。','Image processing was cancelled.':'圖像處理已取消。','Image processing exceeded its time limit.':'圖像處理超時。','Isolated image processing failed.':'隔離圖像處理失敗。','Raster fill requires a static HEX color.':'點陣填色需要靜態 HEX 顏色。','Appearance history index is invalid.':'外觀歷史索引無效。','Local appearance history is unavailable.':'本機外觀歷史暫時未能使用。','Local appearance history is full.':'本機外觀歷史已滿。','Appearance history revision already exists.':'外觀歷史版本已存在。','Appearance history revision exceeds bounds.':'外觀歷史版本超出限制。','Appearance history revision is missing.':'搵唔到外觀歷史版本。','Appearance history chain is invalid.':'外觀歷史連結無效。',
'Local raster groups support static fills, image layers, geometric masks, ordered effects and transforms. Embedded sources remain local and immutable until detached. Mesh warp uses a 2D triangle grid and may show sampling seams; it is not a 3D deformation. Rasterization rejects unsupported channel and color-range operations. Decoding runs in a dedicated Chromium worker with a time limit, not an operating-system process. Local revisions and exports omit image pixels. Editable CSS groups still cascade styles onto the target.':'本機點陣群組支援靜態填色、圖像圖層、幾何遮罩、依次效果同變形。嵌入來源會留喺本機，分離前不可變更。網格扭曲使用二維三角網格，可能出現取樣接縫，唔係三維變形。點陣預覽會拒絕未支援嘅通道同色彩範圍操作。解碼喺設有時限嘅獨立 Chromium worker 執行，唔係獨立作業系統程序。本機版本同匯出檔唔會包含圖像像素。可編輯 CSS 群組仍會依次將樣式套用到目標。'
};
export const APPEARANCE_COPY=Object.freeze({...BASE_COPY,...EXTRA_COPY});
export const APPEARANCE_COPY_KEYS=Object.freeze(Object.keys(APPEARANCE_COPY));
export function appearanceTranslator(translate){return (source,options={})=>{
 if(source.startsWith('Unsupported property: '))return `${translate?.('Unsupported property',options)||'Unsupported property'}: ${source.slice(22)}`;
 const numbered=/^(Layer|Group) (\d+)$/.exec(source);if(numbered)return `${translate?.(numbered[1],options)||numbered[1]} ${numbered[2]}`;
 if(options.message&&!Object.hasOwn(APPEARANCE_COPY,source)){const explanation='The operation could not be completed.';return `${translate?.(explanation,options)||explanation} ${source}`;}
 return translate?.(source,options)||source;
};}
