import {inspectPngSource,validateImageSource,IMAGE_SOURCE_LIMITS} from './image-source.js';
import {validateImageTransform} from './image-layers.js';

export const RASTER_LIMITS=Object.freeze({dimension:1024,pixels:1048576,layers:128,depth:4,timeout:10000,meshCells:64});
export function defaultMesh(){return {columns:2,rows:2,points:Array.from({length:9},(_,i)=>[i%3*50,Math.floor(i/3)*50])};}
export function validateMesh(value){
 if(!value||!Number.isInteger(value.columns)||!Number.isInteger(value.rows)||value.columns<1||value.rows<1||value.columns*value.rows>64||!Array.isArray(value.points)||value.points.length!==(value.columns+1)*(value.rows+1))throw Error('Invalid bounded warp mesh.');
 const points=value.points.map(p=>{if(!Array.isArray(p)||p.length!==2||p.some(n=>!Number.isFinite(n)||n< -100||n>200))throw Error('Invalid bounded warp mesh.');return [...p];});
 const result={columns:value.columns,rows:value.rows,points};for(const triangle of meshTriangles(result))if(Math.abs(triangle.destination.reduce((sum,p,i,a)=>sum+p[0]*a[(i+1)%3][1]-p[1]*a[(i+1)%3][0],0))<.001)throw Error('Warp mesh contains a collapsed triangle.');return result;
}
export function meshTriangles(mesh){const out=[],{columns:c,rows:r,points:p}=mesh;for(let y=0;y<r;y++)for(let x=0;x<c;x++){const a=y*(c+1)+x,b=a+1,d=a+c+1,e=d+1;const s=[[x*100/c,y*100/r],[(x+1)*100/c,y*100/r],[x*100/c,(y+1)*100/r],[(x+1)*100/c,(y+1)*100/r]];out.push({source:[s[0],s[1],s[3]],destination:[p[a],p[b],p[e]]},{source:[s[0],s[3],s[2]],destination:[p[a],p[e],p[d]]});}return out;}
export function triangleTransform(source,destination){const [[x0,y0],[x1,y1],[x2,y2]]=source,[[u0,v0],[u1,v1],[u2,v2]]=destination,det=(x1-x0)*(y2-y0)-(x2-x0)*(y1-y0);if(Math.abs(det)<1e-9)throw Error('Warp mesh contains a collapsed triangle.');const a=((u1-u0)*(y2-y0)-(u2-u0)*(y1-y0))/det,c=((x1-x0)*(u2-u0)-(x2-x0)*(u1-u0))/det,b=((v1-v0)*(y2-y0)-(v2-v0)*(y1-y0))/det,d=((x1-x0)*(v2-v0)-(x2-x0)*(v1-v0))/det;return[a,b,c,d,u0-a*x0-c*y0,v0-b*x0-d*y0];}
export function validateRasterRequest(request){
 if(!request||!['normalize','composite','warp'].includes(request.operation))throw Error('Unsupported raster operation.');
 if(request.operation==='normalize'){const bytes=new Uint8Array(request.bytes),metadata=inspectPngSource(bytes);return {operation:'normalize',bytes,metadata};}
 const width=request.width??512,height=request.height??512;if(!Number.isInteger(width)||!Number.isInteger(height)||width<1||height<1||width>1024||height>1024||width*height>RASTER_LIMITS.pixels)throw Error('Raster dimensions exceed bounds.');
 let count=0,totalBytes=0;function visit(layers,depth=0){if(!Array.isArray(layers)||depth>4)throw Error('Raster layer nesting exceeds bounds.');return layers.map(layer=>{if(++count>128)throw Error('Raster layer count exceeds bounds.');const result={...layer,imageTransform:validateImageTransform(layer.imageTransform)};if(layer.channels)throw Error('Rasterization does not support channel gains.');if(layer.effects?.some(e=>!['blur','brightness','contrast','saturate','grayscale','sepia','invert','hue-rotate','opacity'].includes(e.type)||!Number.isFinite(e.value)||e.value<0||e.value>(e.type==='hue-rotate'?360:e.type==='blur'?100:2)))throw Error('Unsupported raster effect.');if(layer.selection){const s=layer.selection;if(s.kind==='path'){if(typeof s.path!=='string'||s.path.length>1000||!/^[MmLlHhVvCcSsQqTtAaZz0-9.,\s+-]+$/.test(s.path))throw Error('Invalid raster path.');}else if(!['rectangle','ellipse','polygon'].includes(s.kind)||!Array.isArray(s.values)||s.values.length>64||s.values.some(n=>!Number.isFinite(n)||n<0||n>100))throw Error('Rasterization does not support this selection type.');}if(layer.imageSource){result.imageSource=validateImageSource(layer.imageSource);totalBytes+=result.imageSource.bytes;if(totalBytes>IMAGE_SOURCE_LIMITS.bytes)throw Error('Raster source bytes exceed bounds.');}if(layer.children)result.children=visit(layer.children,depth+1);return result;});}
 const layers=visit(request.layers??[]);const verifyFill=list=>{for(const layer of list){if(Object.keys(layer.properties||{}).some(key=>key!=='backgroundColor'))throw Error('Rasterization supports background fills only; target typography remains live.');if(layer.children)verifyFill(layer.children);}};verifyFill(layers);return {...request,width,height,layers,...(request.mesh?{mesh:validateMesh(request.mesh)}:{})};
}
/** One dedicated worker per operation. No DOM access; the worker disables ambient network APIs. */
export function runRasterOperation(request,{WorkerClass=globalThis.Worker,timeout=RASTER_LIMITS.timeout,signal}={}){
 const checked=validateRasterRequest(request);if(typeof WorkerClass!=='function')return Promise.reject(Error('Isolated image processing is unavailable.'));
 return new Promise((resolve,reject)=>{let done=false;const worker=new WorkerClass(new URL('./appearance-raster-worker.js',import.meta.url),{type:'module'});const finish=(error,value)=>{if(done)return;done=true;clearTimeout(timer);signal?.removeEventListener('abort',abort);worker.terminate();error?reject(error):resolve(value);};const abort=()=>finish(Error('Image processing was cancelled.'));const timer=setTimeout(()=>finish(Error('Image processing exceeded its time limit.')),timeout);worker.onmessage=event=>{try{if(event.data?.error)throw Error(event.data.error);finish(null,validateImageSource(event.data?.source));}catch(error){finish(error);}};worker.onerror=()=>finish(Error('Isolated image processing failed.'));signal?.addEventListener('abort',abort,{once:true});if(signal?.aborted)return abort();worker.postMessage(checked);});
}
