export function mountPrivateHistory(container,{manager,restore,attachSearch,notify=()=>{},confirmDestructive,t=s=>s}={}){
 const doc=container.ownerDocument;let disposed=false;const root=doc.createElement('section');root.className='local-ux-history';container.append(root);
 const el=(tag,text)=>{const node=doc.createElement(tag);if(text)node.textContent=text;return node;};
 const button=(text,run,parent=root)=>{const node=el('button',t(text));node.type='button';node.onclick=()=>Promise.resolve().then(run).catch(error=>notify(error.message));parent.append(node);return node;};
 const field=(label,type='text',parent=root)=>{const row=el('label',t(label)),input=el('input');input.type=type;row.append(input);if(['text','password','search'].includes(type))button('Clear',()=>{input.value='';input.dispatchEvent(new Event('input'));input.focus();},row);parent.append(row);return input;};
 const title=el('h3',t('Private local history'));root.append(title,el('p',t('History uses its own password. Credentials, personal vocabulary and custom images are omitted. Forgotten history passwords require clearing local history; they cannot be recovered.',{message:true})));
 const secret=field('History password','password');secret.autocomplete='current-password';
 const status=el('p');status.setAttribute('role','status');root.append(status);
 const workspace=el('section');workspace.hidden=true;root.append(workspace);
 const search=field('Search history','search',workspace),from=field('From date','date',workspace),to=field('To date','date',workspace),action=field('Action filter','text',workspace),list=el('div');workspace.append(list);
 const compare=el('output');workspace.append(compare);let selected=[];
 async function refresh(){if(disposed)return;workspace.hidden=!manager.unlocked;status.textContent=t(manager.unlocked?'History unlocked':'History locked',{message:true});if(!manager.unlocked){list.replaceChildren();return;}const records=await manager.list({query:search.value,from:from.value,to:to.value?`${to.value}T23:59:59.999Z`:'',action:action.value});if(disposed)return;list.replaceChildren();for(const record of records){const row=el('article');row.className='local-ux-field';const check=el('input');check.type='checkbox';check.setAttribute('aria-label',`${t('Select history entry')} ${record.at}`);check.checked=selected.includes(record.id);check.onchange=()=>{selected=check.checked?[...selected,record.id].slice(-2):selected.filter(id=>id!==record.id);};row.append(check,el('strong',t(record.action)),el('time',record.at));if(record.metadata?.label)row.append(el('span',record.metadata.label));button('Restore',async()=>{await manager.restore(record.id,restore);await refresh();},row);const label=field('Entry label','text',row);button('Save label',async()=>{await manager.label(record.id,label.value);await refresh();},row);list.append(row);}}
 button('Set up history password',async()=>{await manager.setup(secret.value);secret.value='';await refresh();});button('Unlock history',async()=>{await manager.unlock(secret.value);secret.value='';await refresh();});button('Lock history',()=>{manager.lock();secret.value='';refresh();});
 button('Compare selected entries',async()=>{if(selected.length!==2)throw Error('Select exactly two entries to compare.');compare.textContent=JSON.stringify(await manager.diff(selected[0],selected[1]),null,2);},workspace);
 button('Export redacted history',async()=>{const text=await manager.export(),url=URL.createObjectURL(new Blob([text],{type:'application/json'})),link=el('a');link.download='local-history-redacted.json';link.href=url;link.click();setTimeout(()=>URL.revokeObjectURL(url),0);},workspace);
 const retention=field('Retention days','number',workspace);retention.min='1';retention.max='3650';retention.value='365';button('Set retention',async()=>{await manager.setRetention(Number(retention.value));await refresh();},workspace);
 const prune=button('Prune expired entries',async()=>{if(!confirmDestructive)throw Error('The destructive-action confirmation adapter is unavailable.');if(await confirmDestructive({action:t('Prune expired local history'),description:t('Remove entries older than the selected retention period.',{message:true})})){await manager.prune({confirmed:true});await refresh();}},workspace);if(!confirmDestructive){prune.disabled=true;prune.title=t('The two-key destructive confirmation adapter is unavailable.',{message:true});}
 for(const input of [search,from,to,action])input.addEventListener('input',()=>refresh().catch(e=>notify(e.message)));const off=attachSearch?.(search,list),unsubscribe=manager.subscribe(()=>refresh().catch(e=>notify(e.message)));refresh();return{refresh,destroy(){disposed=true;if(typeof off==='function')off();unsubscribe();root.remove();}};
}
