const finite=(value,min,max)=>{const n=Number(value);if(!Number.isFinite(n)||n<min||n>max)throw new Error('Image transform is outside its bounds.');return n;};
export function defaultImageTransform(){return {x:0,y:0,scaleX:1,scaleY:1,rotate:0,skewX:0,skewY:0,crop:[0,0,100,100],opacity:1,blend:'normal'};}
export function validateImageTransform(value={}){const t={...defaultImageTransform(),...value};for(const key of ['x','y'])t[key]=finite(t[key],-200,200);for(const key of ['scaleX','scaleY'])t[key]=finite(t[key],.01,10);for(const key of ['rotate'])t[key]=finite(t[key],-360,360);for(const key of ['skewX','skewY'])t[key]=finite(t[key],-80,80);t.opacity=finite(t.opacity,0,1);if(!['normal','multiply','screen','overlay','darken','lighten','difference'].includes(t.blend))throw new Error('Invalid image blend mode.');if(!Array.isArray(t.crop)||t.crop.length!==4)throw new Error('Invalid image crop.');t.crop=t.crop.map(n=>finite(n,0,100));if(t.crop[2]<=0||t.crop[3]<=0||t.crop[0]+t.crop[2]>100||t.crop[1]+t.crop[3]>100)throw new Error('Invalid image crop.');return t;}
let sequence=0;
/** All SVG nodes are generated locally; uploaded SVG and external resource URLs are unsupported. */
export function renderImageLayers(target,layers,resolveImage){
 const hasImage=list=>(list||[]).some(layer=>layer.visible!==false&&(layer.imageSource||layer.kind==='group'&&hasImage(layer.children)));if(!hasImage(layers))return null;
 const doc=target.ownerDocument,ns='http://www.w3.org/2000/svg';const make=tag=>doc.createElementNS(ns,tag),svg=make('svg');svg.setAttribute('viewBox','0 0 100 100');svg.setAttribute('preserveAspectRatio','none');svg.setAttribute('aria-hidden','true');svg.dataset.appearanceImageOverlay='';Object.assign(svg.style,{position:'absolute',inset:'0',width:'100%',height:'100%',pointerEvents:'none',overflow:'hidden',isolation:'isolate'});
 const defs=make('defs');svg.append(defs);let count=0;
 function append(list,parent){for(const layer of list||[]){if(layer.visible===false)continue;const group=make('g');group.style.isolation='isolate';parent.append(group);const transform=validateImageTransform(layer.imageTransform);group.setAttribute('opacity',transform.opacity);group.style.mixBlendMode=transform.blend;group.setAttribute('transform',`translate(${transform.x} ${transform.y}) translate(50 50) rotate(${transform.rotate}) skewX(${transform.skewX}) skewY(${transform.skewY}) scale(${transform.scaleX} ${transform.scaleY}) translate(-50 -50)`);
 if(layer.selection&&['rectangle','ellipse','polygon','path'].includes(layer.selection.kind)){const clip=make('clipPath'),id=`appearance-image-mask-${++sequence}`;clip.id=id;const s=layer.selection;let shape;if(s.kind==='rectangle'){shape=make('rect');for(const [i,k]of ['x','y','width','height'].entries())shape.setAttribute(k,s.values[i]);}else if(s.kind==='ellipse'){shape=make('ellipse');for(const [i,k]of ['cx','cy','rx','ry'].entries())shape.setAttribute(k,s.values[i]);}else if(s.kind==='polygon'){shape=make('polygon');shape.setAttribute('points',s.values.reduce((a,n,i)=>{if(i%2===0)a.push(`${n},${s.values[i+1]}`);return a;},[]).join(' '));}else{shape=make('path');shape.setAttribute('d',s.path);}clip.append(shape);defs.append(clip);group.setAttribute('clip-path',`url(#${id})`);}
 if(layer.imageSource){const source=resolveImage(layer.imageSource);const viewport=make('svg'),[x,y,w,h]=transform.crop;viewport.setAttribute('x','0');viewport.setAttribute('y','0');viewport.setAttribute('width','100');viewport.setAttribute('height','100');viewport.setAttribute('viewBox',`${source.width*x/100} ${source.height*y/100} ${source.width*w/100} ${source.height*h/100}`);viewport.setAttribute('preserveAspectRatio','xMidYMid meet');const image=make('image');image.setAttribute('href',source.dataUrl);image.setAttribute('width',source.width);image.setAttribute('height',source.height);viewport.append(image);group.append(viewport);count++;}
 if(layer.kind==='group')append(layer.children,group);
 }}append(layers,svg);if(!count)return null;const rect=target.getBoundingClientRect();Object.assign(svg.style,{position:'fixed',left:rect.left+'px',top:rect.top+'px',width:rect.width+'px',height:rect.height+'px',zIndex:'1'});doc.body.append(svg);return svg;
}
