import {createPrivateHistory} from '../../../shared/local-ux/history.js';
import {mountPrivateHistory} from './history.js';
import {createSettingsStore,DEFAULTS,effectiveSettings,validateSettings} from '../../../shared/local-ux/store.js';
import {validateRule,resolveSchedules,createExternalScheduleResolver,SCHEDULE_FIELDS} from '../../../shared/local-ux/schedules.js';
import {createNarrator} from '../../../shared/local-ux/narrator.js';
import {createTranslator} from '../../../shared/local-ux/language.js';
import {mountAppearanceEditor} from './appearance.js';
import {mountLogoEditor} from './logo.js';

/** Host adapters: sharedSettings.read/write/subscribe, verifySharedCredential,
 * setSharedCredential, attachSearch, notify, history, onChange, vocabulary. */
export function mountPersonalization(container,services={}){
 const doc=container.ownerDocument, win=doc.defaultView;let destroyed=false,active='language',effective,sharedStatus='',lastChange=Date.now();const started=Date.now(),disposers=[],renderDisposers=[];
 const notify=(message)=>services.notify?.(message);
 const localHistory=services.historyManager||createPrivateHistory({storage:services.storage||win.localStorage,credentialStore:services.historyCredentialStore});
 const recordChange=record=>{services.history?.(record);if(localHistory.unlocked)localHistory.append(record.action,record.after||{}, {at:record.at}).catch(e=>notify(e.message));};
 const store=services.store||createSettingsStore({storage:services.storage||win.localStorage,history:recordChange,onError:e=>notify(e.message)});
 const t=createTranslator(()=>effective||store.get(),{vocabulary:services.vocabulary});
 const external=createExternalScheduleResolver({fetchSource:services.fetchScheduleSource,onError:(e,r)=>notify(`${r.label}: ${e.message}`)});
 const narrator=createNarrator({getSettings:()=>effective.narrator,synthesis:win.speechSynthesis,Utterance:win.SpeechSynthesisUtterance,isScreenReaderActive:services.isScreenReaderActive,onVoices:()=>{if(!destroyed&&active==='language')render();}});
 const appearance=mountAppearanceEditor(services.surfaceRoot||doc.body,{...services,translate:(key,fallback)=>t(fallback||key),onChange:(snapshot,metadata)=>{services.history?.({action:'appearance changed',at:new Date().toISOString(),metadata});if(localHistory.unlocked)localHistory.append('appearance changed',snapshot,metadata).catch(e=>notify(e.message));}});
 function node(tag,text,attrs={}){const n=doc.createElement(tag);if(text)n.textContent=text;for(const[k,v]of Object.entries(attrs))n.setAttribute(k,v);return n;}
 const button=(label,action)=>{const b=node('button',t(label),{type:'button'});b.addEventListener('click',()=>Promise.resolve(action()).catch(e=>notify(e.message)));return b;};
 function update(patch,action){store.update(patch,action);lastChange=Date.now();}
 function field(section,label,value,kind,onChange,description,options){const row=node('div','',{class:'local-ux-field','data-setting':label});let control;
  if(kind==='select'){control=node('select');for(const [val,title]of options){const option=node('option',t(title),{value:val});control.append(option);}control.value=value;}
  else{control=node('input');control.type=kind;if(kind==='checkbox')control.checked=value;else control.value=value??'';}
  const id=`local-ux-${label.toLowerCase().replace(/[^a-z0-9]+/g,'-')}`;control.id=id;row.append(node('label',t(label),{for:id}),control);control.addEventListener('change',()=>{try{onChange(kind==='checkbox'?control.checked:control.value);}catch(e){notify(e.message);}});
  if(!['checkbox','range','color','select','file'].includes(kind))row.append(button('Clear',()=>{control.value='';onChange('');control.focus();}));
  const detail=node('details');detail.append(node('summary',t('Help')),node('p',t(description||label)));row.append(detail,node('small',`${t(store.provenance==='saved'?'Saved':'Default')}: ${kind==='checkbox'?t(value?'On':'Off'):String(value??'')}`));section.append(row);return control;
 }
 function section(title){const root=node('section','',{class:'local-ux-section'});root.append(node('h3',t(title)));return root;}
 function apply(){const base=store.get();effective=effectiveSettings(base,resolveSchedules(base.schedules,new Date(),external.values));const root=services.surfaceRoot||doc.documentElement;root.dataset.theme=effective.theme==='system'?(win.matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):effective.theme;root.dataset.density=effective.density;root.dataset.motion=effective.motion;root.dataset.focusMode=String(effective.attention.focus);root.dataset.lowStimulation=String(effective.attention.lowStimulation);root.dataset.oneThing=String(effective.attention.oneThing);root.style.setProperty('--local-ux-seed',effective.seed);root.style.setProperty('--local-ux-font',`${effective.fontFamily}, 'Noto Sans CJK TC', sans-serif`);root.style.setProperty('--local-ux-font-scale',effective.fontScale);root.style.setProperty('--local-ux-font-weight',effective.fontWeight);doc.documentElement.lang=effective.language==='yue'?'yue-Hant':'en';services.onChange?.(structuredClone(effective));updateAttention();return effective;}
 function updateAttention(){if(!effective)return;let status=doc.getElementById('local-ux-attention-status');if(!status){status=node('aside','',{id:'local-ux-attention-status',class:'local-ux-attention-status','aria-live':'polite'});(services.attentionHost||doc.body).append(status);}status.replaceChildren();const a=effective.attention;if(a.timeAwareness){status.append(node('span',`${t('Session elapsed')}: ${Math.floor((Date.now()-started)/60000)} min. ${t('Since last change')}: ${Math.floor((Date.now()-lastChange)/60000)} min.`));}if(a.oneThing)status.append(node('p',`${t('Next action')}: ${a.nextAction||t('No action chosen')}`));if(a.momentum&&Date.now()-lastChange>20*60000&&Date.now()>a.snoozedUntil){status.append(node('p',t('Nothing has changed here for 20 minutes.')),button('Not now (one hour)',()=>update({attention:{...a,snoozedUntil:Date.now()+3600000}},'attention reminder postponed')));}status.hidden=!status.childNodes.length;}
 function render(){if(destroyed)return;renderDisposers.splice(0).forEach(f=>f());container.replaceChildren();container.classList.add('local-ux');const state=store.get();container.append(node('h2',t('Personalization')));const tabs=node('div','',{role:'tablist','aria-label':t('Personalization')});const sections=[['language','Language and voice'],['appearance','Appearance'],['schedules','Schedules'],['attention','Attention'],['history','Private local history']];for(const[id,label]of sections){const b=button(label,()=>{active=id;render();});b.setAttribute('role','tab');b.setAttribute('aria-selected',String(id===active));b.tabIndex=id===active?0:-1;b.addEventListener('keydown',e=>{if(['ArrowRight','ArrowLeft'].includes(e.key)){e.preventDefault();active=sections[(sections.findIndex(v=>v[0]===active)+(e.key==='ArrowRight'?1:sections.length-1))%sections.length][0];render();container.querySelector('[aria-selected="true"]').focus();}});tabs.append(b);}container.append(tabs);
  const content=node('div','',{role:'tabpanel'});container.append(content);const search=node('input','',{type:'search','aria-label':t('Search settings'),placeholder:t('Search settings')});content.append(search);const area=node('div');content.append(area);if(services.attachSearch){const off=services.attachSearch(search,area);if(typeof off==='function')renderDisposers.push(off);}else search.addEventListener('input',()=>{for(const row of area.querySelectorAll('.local-ux-field'))row.hidden=!row.textContent.toLocaleLowerCase().includes(search.value.toLocaleLowerCase());});
  if(active==='language'){
   const mode=section(state.school.name);field(mode,'Mode name',state.school.name,'text',value=>changeSchool({...state.school,name:value.trim()||state.school.name}),'This name appears everywhere this mode is offered.');mode.append(node('p',t('This is a user-experience lock, not a security boundary. Deleting the shared local record resets it.')));if(sharedStatus)mode.append(node('p',sharedStatus));
   const secret=field(mode,'Local unlock credential','','password',()=>{},'Enter the local credential only here. It is never exported.');secret.autocomplete='current-password';
   mode.append(button('Set local credential',async()=>{if(!services.setSharedCredential)throw Error('Shared credential storage is unavailable.');await services.setSharedCredential(secret.value);secret.value='';notify(t('Saved',{message:true}));}));mode.append(button(state.school.enabled?'Turn off mode':'Enable mode',async()=>{if(state.school.enabled){if(!services.verifySharedCredential||!await services.verifySharedCredential(secret.value))throw Error('The credential did not match. Use the local record recovery route.');}await changeSchool({...state.school,enabled:!state.school.enabled});secret.value='';}));area.append(mode);
   if(!state.school.enabled){const language=section('Language and voice');field(language,'Language',state.language,'select',value=>update({language:value},'language changed'),'', [['en','English'],['yue','Cantonese'],['bilingual','Bilingual']]);for(const[key,label]of [['funnyEnglish','English playfulness'],['funnyCantonese','Cantonese playfulness']]){const control=field(language,label,state[key],'range',value=>update({[key]:Number(value)},'message style changed'),'Styles all messages, including errors and warnings. Facts never change. Default: 5.');control.min=1;control.max=5;control.step=1;language.append(button(`Reset ${label.toLowerCase()}`,()=>update({[key]:5},'message style reset')));}field(language,'Show emojis in dialogs and message boxes',state.emoji,'checkbox',value=>update({emoji:value},'dialog decoration changed'),'Decorative emojis do not change labels, facts or accessible names.');area.append(language);}
   const voice=section('Narrator');field(voice,'Narrator',state.narrator.enabled,'checkbox',value=>update({narrator:{...state.narrator,enabled:value}},'narration changed'),'Off by default. Events are spoken one at a time and yield to active assistive technology.');field(voice,'Narration language',effective.narrator.language,'select',value=>update({narrator:{...state.narrator,language:value}},'narration language changed'),'',state.school.enabled?[['en','English']]:[['en','English'],['yue','Cantonese'],['both','Both']]);
   for(const[lang,key,label]of [['en','englishVoice','English voice'],['yue','cantoneseVoice','Cantonese voice']]){if(state.school.enabled&&lang==='yue')continue;const resolved=narrator.resolve(lang);field(voice,label,state.narrator[key],'select',value=>update({narrator:{...state.narrator,[key]:value}},'narration voice changed'),'', [['','Choose automatically'],...resolved.available.map(v=>[v.voiceURI,`${v.name} (${v.lang})`])]);voice.append(node('p',!narrator.available?'Speech synthesis is unavailable.':!resolved.voice?'No installed voice can speak this language.':`${resolved.missing?'The selected voice is not installed. Falling back to ':''}${resolved.voice.name}${resolved.voice.localService?'':' (network voice, may be unavailable offline)'}`));}
   for(const[key,label,min,max]of [['rate','Rate',.1,3],['pitch','Pitch',0,2]]){const input=field(voice,label,state.narrator[key],'range',value=>update({narrator:{...state.narrator,[key]:Number(value)}},'narration delivery changed'));input.min=min;input.max=max;input.step=.1;}voice.append(button('Test narration',()=>narrator.speak({english:'Narration is ready.',cantonese:state.school.enabled?null:'語音旁白準備好。',urgent:true})));area.append(voice);
  }
  if(active==='appearance'){const look=section('Appearance');field(look,'Theme',state.theme,'select',v=>update({theme:v},'theme changed'),'', [['system','System'],['light','Light'],['dark','Dark']]);field(look,'Density',state.density,'select',v=>update({density:v},'density changed'),'', [['compact','Compact'],['comfortable','Comfortable'],['spacious','Spacious']]);field(look,'Accent color',state.seed,'color',v=>update({seed:v},'accent changed'));field(look,'Font family',state.fontFamily,'text',v=>update({fontFamily:v||'system-ui'},'font changed'),'Choose a family installed on this device. Missing families use the bundled fallback.');const scale=field(look,'Font scale',state.fontScale,'range',v=>update({fontScale:Number(v)},'font scale changed'));scale.min=.75;scale.max=2;scale.step=.05;const weight=field(look,'Font weight',state.fontWeight,'range',v=>update({fontWeight:Number(v)},'font weight changed'));weight.min=100;weight.max=900;weight.step=100;field(look,'Motion',state.motion,'select',v=>update({motion:v},'motion changed'),'', [['system','System'],['full','Full'],['reduced','Reduced']]);field(look,'Display name',state.displayName,'text',v=>update({displayName:v||DEFAULTS.displayName},'display name changed'),'Changes presentation only. Diagnostics, storage, update feeds and installed identity keep the original name.');look.append(button('Reset name',()=>update({displayName:DEFAULTS.displayName},'display name reset')),button('Edit this surface',()=>appearance.open(container)));area.append(look);const logo=mountLogoEditor(area,{storage:services.storage||win.localStorage,onChange:services.onLogoChange});renderDisposers.push(()=>logo.destroy());}
  if(active==='attention'){const attention=section('Attention');for(const[key,label]of [['focus','Focus'],['lowStimulation','Low stimulation'],['timeAwareness','Time awareness'],['oneThing','One thing at a time'],['momentum','Momentum']])field(attention,label,state.attention[key],'checkbox',v=>update({attention:{...state.attention,[key]:v}},'attention mode changed'),'An optional interface accommodation, off by default.');field(attention,'Next action',state.attention.nextAction,'text',v=>update({attention:{...state.attention,nextAction:v}},'next action changed'),'Your chosen next action persists across sessions.');area.append(attention);}
  if(active==='schedules')renderSchedules(area,state);
  if(active==='history'){const historyView=mountPrivateHistory(area,{manager:localHistory,restore:snapshot=>{if(snapshot?.elements)appearance.setState(snapshot);else if(snapshot?.version===1&&Object.hasOwn(snapshot,'language'))update(validateSettings(snapshot),'settings restored');else throw Error('This metadata-only entry has no restorable snapshot.');},attachSearch:services.attachSearch,notify,confirmDestructive:services.confirmDestructive,t});renderDisposers.push(()=>historyView.destroy());}
  const footer=node('footer');footer.append(button('Export settings',()=>download(store.export(),'settings.json')),button('Reset',()=>update(structuredClone(DEFAULTS),'settings reset')));const file=node('input','',{type:'file',accept:'application/json','aria-label':t('Import settings')});file.addEventListener('change',async()=>{try{const f=file.files[0];if(!f||f.size>262144)throw Error('Choose a settings file smaller than 256 KiB.');const parsed=JSON.parse(await f.text());update(validateSettings(parsed.settings||parsed),'settings imported');}catch(e){notify(e.message);}finally{file.value='';}});footer.append(file);container.append(footer);
 }
 async function changeSchool(value){if(services.sharedSettings?.write)await services.sharedSettings.write(value);else sharedStatus='Browser storage applies to this origin only. A shared desktop record adapter is not available.';update({school:value},'shared mode changed');}
 function download(text,name){const blob=new Blob([text],{type:'application/json'}),url=URL.createObjectURL(blob),a=node('a','',{href:url,download:name});a.click();setTimeout(()=>URL.revokeObjectURL(url),0);}
 function renderSchedules(area,state){const sec=section('Schedules');sec.append(node('p',t('Time windows use the selected timezone. Repeated daylight-saving times both match; missing times do not run. Equal start and end means the whole day. Cross-midnight rules belong to their starting weekday. Higher priority wins, then lexical rule id.')));for(const rule of state.schedules){if(state.school.enabled&&Object.keys(rule.values).some(key=>['language','funnyEnglish','funnyCantonese'].includes(key)))continue;const row=node('article','',{class:'local-ux-field'});row.append(node('h4',rule.label),node('p',`${rule.timezone}: ${rule.start}–${rule.end}, ${rule.weekdays.join(', ')}; ${Object.keys(rule.values).join(', ')}`));row.append(button(rule.enabled?'Disable':'Enable',()=>update({schedules:state.schedules.map(r=>r.id===rule.id?{...r,enabled:!r.enabled}:r)},'schedule toggled')),button('Remove',()=>update({schedules:state.schedules.filter(r=>r.id!==rule.id)},'schedule removed')));sec.append(row);}const draft={id:crypto.randomUUID(),label:'',enabled:true,start:'09:00',end:'17:00',startDate:'',endDate:'',timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,weekdays:[0,1,2,3,4,5,6],priority:0,values:{theme:'dark'},source:{type:'local'}};let setting='theme',value='dark';field(sec,'Schedule name','','text',v=>draft.label=v);for(const[key,label,kind]of [['startDate','Start date','date'],['endDate','End date','date'],['start','Start time','time'],['end','End time','time'],['timezone','Timezone','text'],['priority','Priority','number']])field(sec,label,draft[key],kind,v=>draft[key]=key==='priority'?Number(v):v);const days=node('fieldset');days.append(node('legend',t('Weekdays')));for(const[index,label]of ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].entries())field(days,label,true,'checkbox',v=>draft.weekdays=v?[...draft.weekdays,index]:draft.weekdays.filter(d=>d!==index));sec.append(days);field(sec,'Setting',setting,'select',v=>{setting=v;value=String(DEFAULTS[v]);valueInput.value=value;},'',SCHEDULE_FIELDS.filter(k=>!state.school.enabled||!['language','funnyEnglish','funnyCantonese'].includes(k)).map(k=>[k,k]));const valueInput=field(sec,'Value',value,'text',v=>value=v);field(sec,'Source','local','select',v=>draft.source.type=v,'External sources require the host credential-vault adapter. No access token is stored here.',[['local','Local'],['api','HTTPS API'],['home-assistant','Home Assistant']]);field(sec,'Endpoint','','url',v=>draft.source.url=v);field(sec,'Entity','','text',v=>draft.source.entity=v);sec.append(button('Add schedule',()=>{draft.values={[setting]:typeof DEFAULTS[setting]==='number'?Number(value):typeof DEFAULTS[setting]==='boolean'?value==='true':value};validateRule(draft);update({schedules:[...state.schedules,draft]},'schedule added');}));area.append(sec);}
 const unsubscribe=store.subscribe(()=>{apply();render();});disposers.push(unsubscribe);const storageListener=e=>{if(e.key===store.key||e.key==='material-file-encryptor.local-ux.v1')store.refresh();};win.addEventListener('storage',storageListener);disposers.push(()=>win.removeEventListener('storage',storageListener));
 if(services.sharedSettings){Promise.resolve(services.sharedSettings.read()).then(value=>{if(value&&!destroyed)update({school:value},'shared mode synchronized');}).catch(e=>{sharedStatus=`Shared mode record unavailable: ${e.message}`;render();});const off=services.sharedSettings.subscribe?.(value=>{if(!destroyed)update({school:value},'shared mode synchronized');});if(off)disposers.push(off);}
 apply();render();const timer=win.setInterval(()=>{apply();},30000);const refresh=win.setInterval(()=>external.refresh(store.get().schedules).then(apply),60000);external.refresh(store.get().schedules).then(apply);
 return{store,apply,narrator,appearance,history:localHistory,translate:t,open(sectionId){active=sectionId;render();},destroy(){destroyed=true;renderDisposers.splice(0).forEach(f=>f());disposers.splice(0).forEach(f=>f());win.clearInterval(timer);win.clearInterval(refresh);external.cancel();localHistory.destroy();narrator.destroy();appearance.destroy();doc.getElementById('local-ux-attention-status')?.remove();container.replaceChildren();}};
}
