export function createNarrator({synthesis=globalThis.speechSynthesis,Utterance=globalThis.SpeechSynthesisUtterance,getSettings,isScreenReaderActive=()=>false,now=()=>Date.now(),onVoices=()=>{}}={}) {
 let queue=[],speaking=false,disposed=false;const last=new Map();
 const voices=()=>synthesis?.getVoices?.()||[];
 const compatible=(voice,lang)=>lang==='yue'?/^(yue|zh[-_]HK)/i.test(voice.lang):/^en(?:[-_]|$)/i.test(voice.lang);
 const resolve=lang=>{const settings=getSettings();const id=settings[lang==='en'?'englishVoice':'cantoneseVoice'];const available=voices().filter(v=>compatible(v,lang));return{voice:available.find(v=>v.voiceURI===id)||available.find(v=>v.localService)||available[0],missing:!!id&&!available.some(v=>v.voiceURI===id),available};};
 const drain=()=>{if(disposed||speaking||!queue.length||!synthesis||!Utterance)return;const settings=getSettings();if(!settings.enabled||isScreenReaderActive()){queue=[];return;}const item=queue.shift();const selected=resolve(item.language);if(!selected.voice){drain();return;}speaking=true;const utterance=new Utterance(item.text);utterance.voice=selected.voice;utterance.lang=selected.voice.lang;utterance.rate=Math.max(.1,Math.min(3,settings.rate));utterance.pitch=Math.max(0,Math.min(2,settings.pitch));utterance.onend=utterance.onerror=()=>{speaking=false;drain();};synthesis.speak(utterance);};
 const changed=()=>onVoices(voices());synthesis?.addEventListener?.('voiceschanged',changed);
 return {voices,resolve,available:!!synthesis&&!!Utterance,speak({english,cantonese,category='general',urgent=false}){if(!getSettings().enabled||isScreenReaderActive())return false;const time=now();if(!urgent&&time-(last.get(category)||-Infinity)<2500)return false;last.set(category,time);queue=queue.filter(item=>item.category!==category);const lang=getSettings().language;if((lang==='en'||lang==='both')&&english)queue.push({text:String(english).slice(0,2000),language:'en',category});if((lang==='yue'||lang==='both')&&cantonese)queue.push({text:String(cantonese).slice(0,2000),language:'yue',category});queue=queue.slice(-20);drain();return true;},cancel(){queue=[];synthesis?.cancel();speaking=false;},destroy(){disposed=true;queue=[];synthesis?.cancel();synthesis?.removeEventListener?.('voiceschanged',changed);}};
}
