import {safeRecord,DEFAULTS,validateSettings} from './store.js';
export const SCHEDULE_FIELDS=['language','theme','density','seed','fontFamily','fontScale','fontWeight','motion','displayName','emoji','funnyEnglish','funnyCantonese'];
const TIME=/^(?:[01]\d|2[0-3]):[0-5]\d$/;const DATE=/^\d{4}-\d{2}-\d{2}$/;
export function validateRule(rule){safeRecord(rule);if(!rule||typeof rule.id!=='string'||rule.id.length>80||!rule.id||typeof rule.label!=='string'||rule.label.length>120)throw Error('A schedule needs a bounded id and label.');if(!TIME.test(rule.start)||!TIME.test(rule.end))throw Error('Choose complete start and end times.');for(const k of ['startDate','endDate'])if(rule[k]&&!DATE.test(rule[k]))throw Error('Choose a valid date.');if(rule.startDate&&rule.endDate&&rule.startDate>rule.endDate)throw Error('End date must follow start date.');if(!Array.isArray(rule.weekdays)||!rule.weekdays.length||rule.weekdays.some(d=>!Number.isInteger(d)||d<0||d>6)||new Set(rule.weekdays).size!==rule.weekdays.length)throw Error('Select at least one distinct weekday.');try{new Intl.DateTimeFormat('en',{timeZone:rule.timezone}).format();}catch{throw Error('Choose a valid timezone.');}if(!rule.values||Object.keys(rule.values).some(k=>!SCHEDULE_FIELDS.includes(k)))throw Error('Schedule contains unsupported settings.');validateSettingValues(rule.values);if(!Number.isInteger(rule.priority)||Math.abs(rule.priority)>1000)throw Error('Priority must be between -1000 and 1000.');if(rule.source&&!['local','api','home-assistant'].includes(rule.source.type))throw Error('Unknown schedule source.');return structuredClone(rule);}
export function clockParts(now,timezone){const parts=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(now).map(p=>[p.type,p.value]));const date=`${parts.year}-${parts.month}-${parts.day}`;return{date,minutes:Number(parts.hour)*60+Number(parts.minute),weekday:new Date(`${date}T12:00:00Z`).getUTCDay()};}
const minutes=s=>Number(s.slice(0,2))*60+Number(s.slice(3));
export function ruleMatches(rule,now=new Date()){if(!rule.enabled)return false;validateRule(rule);let p=clockParts(now,rule.timezone);const start=minutes(rule.start),end=minutes(rule.end);if(start>end&&p.minutes<end){const previous=new Date(`${p.date}T12:00:00Z`);previous.setUTCDate(previous.getUTCDate()-1);p={...p,date:previous.toISOString().slice(0,10),weekday:previous.getUTCDay()};}if(rule.startDate&&p.date<rule.startDate||rule.endDate&&p.date>rule.endDate||!rule.weekdays.includes(p.weekday))return false;return start===end||start<end&&p.minutes>=start&&p.minutes<end||start>end&&(p.minutes>=start||p.minutes<end);}
export function resolveSchedules(rules,now=new Date(),external=new Map()){const result={};for(const rule of [...rules].sort((a,b)=>a.priority-b.priority||a.id.localeCompare(b.id))){if(!ruleMatches(rule,now))continue;const type=rule.source?.type||'local';if(type==='local')Object.assign(result,rule.values);else{const data=external.get(rule.id);if(type==='home-assistant'){if(data===true)Object.assign(result,rule.values);}else if(data)Object.assign(result,data);}}return result;}
export function validateExternalResponse(value){safeRecord(value);if(!value||value.version!==1||!value.settings||Object.keys(value.settings).some(k=>!SCHEDULE_FIELDS.includes(k)))throw Error('Expected a version 1 settings response.');for(const [key,v]of Object.entries(value.settings)){if(typeof v!==typeof DEFAULTS[key])throw Error('An external setting has the wrong type.');if(typeof v==='string'&&v.length>160)throw Error('External value too long.');}validateSettingValues(value.settings);return structuredClone(value.settings);}
export function createExternalScheduleResolver({fetchSource,onError=()=>{}}={}){let generation=0;const values=new Map();return{values,async refresh(rules){const current=++generation;await Promise.all(rules.filter(r=>r.enabled&&r.source?.type!=='local'&&r.source?.type).map(async rule=>{try{if(!fetchSource)throw Error('A privileged external-settings adapter is not available.');const response=await fetchSource(structuredClone(rule.source),{timeout:5000,maxBytes:32768,redirect:'error'});if(current!==generation)return;if(rule.source.type==='home-assistant'){if(!['on','off'].includes(response?.state))throw Error('Home Assistant did not return on or off.');values.set(rule.id,response.state==='on');}else values.set(rule.id,validateExternalResponse(response));}catch(error){if(current===generation){values.delete(rule.id);onError(error,rule);}}}));},cancel(){generation++;}};}

export function validateSettingValues(values){
 const validated=validateSettings({...DEFAULTS,...values});
 for(const[key,value]of Object.entries(values)){
  if(!SCHEDULE_FIELDS.includes(key)||typeof value!==typeof DEFAULTS[key]||validated[key]!==value)throw Error('A scheduled value is outside the supported setting range.');
 }
 return values;
}