import fs from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import {spawn} from 'node:child_process';import {randomBytes,createHash} from 'node:crypto';
import {safeArchiveName,crc32} from './archive.mjs';
const hash=async p=>createHash('sha256').update(await fs.readFile(p)).digest('hex');
export const ARCHIVE_IDS=['7z-list','7z-extract','rar-list','rar-extract'];
export function parseArchiveList(bytes){
 if(bytes.length>1048576)throw new Error('Archive index exceeds 1 MiB.');const text=new TextDecoder('utf-8',{fatal:true}).decode(bytes).replace(/\r\n/g,'\n');const entries=[],seen=new Set();let total=0;
 for(const block of text.replace(/^\n+|\n+$/g,'').split(/\n\n+/)){if(!block.trim())continue;const fields={};for(const line of block.split('\n')){const match=/^([^=]+?) = (.*)$/.exec(line);if(!match||Object.hasOwn(fields,match[1]))throw new Error('Ambiguous archive index.');fields[match[1]]=match[2];}
 const raw=fields.Path;if(!raw||raw.includes('_'))throw new Error('Archive names containing underscores are unsupported because console normalization is ambiguous.');const name=safeArchiveName(raw),directory=Boolean(fields.Folder==='+'||fields.Attributes?.startsWith('D'));
 if(seen.has(name.toLowerCase()))throw new Error('Duplicate archive path.');seen.add(name.toLowerCase());if(fields.Encrypted==='+'||fields['Split Before']==='+'||fields['Split After']==='+'||fields.Anti==='+'||fields.Commented==='+'||Object.keys(fields).some(k=>/link|reparse|stream/i.test(k))||/[a-z]/.test(fields.Attributes||'')||Boolean(fields.Mode))throw new Error('Encrypted archives, links and streams are unsupported.');
 const size=Number(fields.Size);if(!Number.isSafeInteger(size)||size<0||size>16777216||directory&&size!==0||(total+=size)>67108864||entries.length>=1000)throw new Error('Archive expansion limit exceeded.');
 if(!directory&&fields.CRC&&!/^[0-9a-f]{8}$/i.test(fields.CRC))throw new Error('Invalid archive CRC.');entries.push({name:name.replace(/\/$/,'')+(directory?'/':''),bytes:size,directory,crc32:fields.CRC?.toLowerCase()});
 }
 for(const e of entries){const parts=e.name.replace(/\/$/,'').split('/');for(let i=1;i<parts.length;i++)if(entries.some(other=>!other.directory&&other.name.toLowerCase()===parts.slice(0,i).join('/').toLowerCase()))throw new Error('Conflicting archive destinations.');}
 return entries;
}
export async function createArchiveLauncher({launcherPath,launcherSha256,launcherCompanionHashes={},sevenZipPath,sevenZipSha256,sevenZipDllPath,sevenZipDllSha256}){
 const files=[[launcherPath,launcherSha256],[sevenZipPath,sevenZipSha256],[sevenZipDllPath,sevenZipDllSha256]];for(const suffix of ['.dll','.runtimeconfig.json','.deps.json']){const p=launcherPath.slice(0,-4)+suffix;if(await fs.access(p).then(()=>true,()=>false))files.push([p,launcherCompanionHashes[path.basename(p)]]);}
 async function verify(){for(const[p,h]of files)if(!path.isAbsolute(p)||!/^[a-f0-9]{64}$/.test(h)||await hash(p)!==h)throw new Error('Archive executable verification failed.');}await verify();
 function stage(operation,bytes,format,entry){let child,root,stopped=false;const nonce=randomBytes(32).toString('hex');
 const result=(async()=>{try{await verify();if(stopped)throw new Error('Cancelled.');if(bytes.length<1||bytes.length>67108864)throw new Error('Archive input byte limit exceeded.');const capacity=await fs.statfs(os.tmpdir());if(Number(capacity.bavail)*Number(capacity.bsize)<384*1024*1024)throw new Error('Insufficient archive temporary capacity.');root=await fs.mkdtemp(path.join(os.tmpdir(),'converter-archive-'));const payload=path.join(root,'payload'),work=path.join(root,'work');await fs.mkdir(payload);await fs.mkdir(work);const executable='7z.exe';await fs.copyFile(sevenZipPath,path.join(payload,executable));await fs.copyFile(sevenZipDllPath,path.join(payload,'7z.dll'));await fs.writeFile(path.join(work,'input-0.bin'),bytes,{flag:'wx'});const request=path.join(root,'launcher.json');await fs.writeFile(request,JSON.stringify({schema:1,nonce,runtime:path.join(payload,executable),directory:root,timeoutMs:30000,memoryBytes:268435456,archive:{operation,format,entry}}),{flag:'wx'});if(stopped)throw new Error('Cancelled.');
 const receipt=await new Promise((resolve,reject)=>{child=spawn(launcherPath,['--request',request],{windowsHide:true,stdio:['ignore','pipe','ignore'],env:{SystemRoot:process.env.SystemRoot,WINDIR:process.env.WINDIR,TEMP:os.tmpdir(),TMP:os.tmpdir()}});let text='';const timer=setTimeout(()=>{child.kill();reject(new Error('Archive sandbox timeout.'));},40000);child.stdout.on('data',b=>{text+=b;if(text.length>8192){child.kill();reject(new Error('Archive receipt too large.'));}});child.once('error',e=>{clearTimeout(timer);reject(e);});child.once('exit',code=>{clearTimeout(timer);try{const r=JSON.parse(text);if(code!==0||r.schema!==1||r.nonce!==nonce||r.isolated!==true||r.exitCode!==0||r.timedOut||r.cancelled||r.killedForStorage||r.profileDeleted!==true||r.networkCapabilities!==0||r.activeProcessLimit!==1||r.memoryBytes!==268435456||r.timeoutMs!==30000||r.appContainerVerified!==true||r.capabilityCount!==0||r.jobLimitsVerified!==true)throw new Error('Archive isolation or conversion failed.');resolve(r);}catch(e){reject(e);}});});
 if(stopped)throw new Error('Cancelled.');const p=path.join(work,'result.json'),st=await fs.lstat(p);if(!st.isFile()||st.isSymbolicLink()||st.size>1048576||await hash(p)!==receipt.resultSha256)throw new Error('Invalid archive result receipt.');const value=JSON.parse(await fs.readFile(p,'utf8'));if(value.schema!==1||value.nonce!==nonce||!Array.isArray(value.outputs)||value.outputs.length>1)throw new Error('Invalid archive result.');const outputs=[];for(const o of value.outputs){if(o.filename!=='result-0.bin')throw new Error('Invalid archive filename.');const file=path.join(work,o.filename),stat=await fs.lstat(file);if(!stat.isFile()||stat.isSymbolicLink()||stat.size!==o.bytes||stat.size<0||stat.size>67108864)throw new Error('Invalid archive output size.');outputs.push({name:o.name,bytes:await fs.readFile(file)});}return {outputs,details:value.details};
 }finally{if(root)await fs.rm(root,{recursive:true,force:true,maxRetries:3});}})();return {result,terminate:async()=>{stopped=true;if(root&&child)await fs.writeFile(path.join(root,'work','cancel.signal'),'cancel').catch(()=>{});}};}

 const provider={stage,launch({adapterId,inputs}){let current,stopped=false;const format=adapterId.split('-')[0];const timer=setTimeout(()=>{stopped=true;void current?.terminate();},30000);const result=(async()=>{if(!ARCHIVE_IDS.includes(adapterId)||inputs.length!==1)throw new Error('Unsupported archive request.');current=stage('list',inputs[0],format);const listed=await current.result;if(stopped)throw new Error('Archive conversion cancelled or timed out.');const entries=parseArchiveList(listed.outputs[0].bytes);const total=entries.reduce((sum,e)=>sum+e.bytes,0);if(total>Math.max(1,inputs[0].length)*100)throw new Error('Archive compression ratio exceeds limits.');if(adapterId.endsWith('-list'))return{outputs:[{name:'archive-index.json',bytes:Buffer.from(JSON.stringify(entries,null,2))}],details:{entries:entries.length,expandedBytes:total}};
 if(entries.filter(e=>!e.directory).length>128)throw new Error('Extraction is limited to 128 files per archive.');const outputs=[];for(const e of entries){if(e.directory)continue;if(stopped)throw new Error('Archive conversion cancelled or timed out.');current=stage('extract-stream',inputs[0],format,e.name);const extracted=await current.result;if(stopped)throw new Error('Archive conversion cancelled or timed out.');const bytes=extracted.outputs[0].bytes;if(bytes.length!==e.bytes)throw new Error('Archive member length mismatch.');if(e.crc32&&crc32(bytes).toString(16).padStart(8,'0')!==e.crc32)throw new Error('Archive CRC validation failed.');outputs.push({name:e.name,bytes});}return{outputs,details:{entries:entries.length,expandedBytes:total,warnings:['Archive metadata and empty directories are not restored.']}};})().finally(()=>clearTimeout(timer));return{result,terminate:async()=>{stopped=true;await current?.terminate();}};}};
 await provider.launch({adapterId:'7z-list',inputs:[Buffer.from('N3q8ryccAASNLh8ZBQAAAAAAAAA6AAAAAAAAADHAsQ5oZWxsbwEEBgABCQUKAYamEDYABwsBAAEBAAwFCgGGphA2AAAFAREVAGgAZQBsAGwAbwAuAHQAeAB0AAAAAAA=','base64')]}).result;
 await provider.launch({adapterId:'rar-list',inputs:[Buffer.from('UmFyIRoHAM+QcwAADQAAAAAAAADjk3QAgCkABQAAAAUAAAAChqYQNgAAAAAUMAkAIAAAAGhlbGxvLnR4dGhlbGxvxD17AEAHAA==','base64')]}).result;
 return provider;
}
