import fs from 'node:fs/promises';
import path from 'node:path';
import { randomUUID, createHash } from 'node:crypto';
import { catalog, detectFormat, LIMITS } from './registry.mjs';
import { outputLocation } from './output-path.mjs';
const digest=bytes=>createHash('sha256').update(bytes).digest('hex');
const samePath=(a,b)=>process.platform==='win32'?path.resolve(a).toLowerCase()===path.resolve(b).toLowerCase():path.resolve(a)===path.resolve(b);
export function createConverterService({stateDirectory,resolveGrant,bundledProof={},sandboxProvider}) {
 if(typeof resolveGrant!=='function')throw new Error('A trusted file grant resolver is required.');
 const isolated=sandboxProvider?.verifiedOsIsolation===true&&typeof sandboxProvider.launch==='function';
 const adapters=()=>catalog({...bundledProof,media:sandboxProvider?.verifiedMediaRuntime===true}).map(item=>!item.enabled&&/^(image|audio|video)-/.test(item.id)&&sandboxProvider?.mediaUnavailableReason?{...item,disabledReason:sandboxProvider.mediaUnavailableReason}:item).map(item=>!isolated&&item.enabled?{...item,enabled:false,disabledReason:'Verified operating-system isolation is unavailable. Conversion is disabled.'}:item);
 let running=false,closed=false,requested=false,cancelling=false,admissionEpoch=0;let runFinished=Promise.resolve(),settleRun,cancellationFinished;const workers=new Map(),previewWorkers=new Map(),locks=new Map(),admissions=new Set();
 const recordPath=id=>{if(!/^[0-9a-f-]{36}$/.test(id))throw new Error('Invalid queue identifier.');return path.join(stateDirectory,id+'.json');};
 const save=async record=>{const p=recordPath(record.id),tmp=p+'.tmp';await fs.writeFile(tmp,JSON.stringify(record),{mode:0o600});await fs.rename(tmp,p);};
 const load=async id=>JSON.parse(await fs.readFile(recordPath(id),'utf8'));
 const init=fs.mkdir(stateDirectory,{recursive:true});
 async function locked(id,action){const previous=locks.get(id)||Promise.resolve();let release;const next=new Promise(resolve=>release=resolve);locks.set(id,next);await previous;try{return await action(await load(id));}finally{release();if(locks.get(id)===next)locks.delete(id);}}
 async function* records(){await init;const dir=await fs.opendir(stateDirectory);for await(const entry of dir){if(entry.name.endsWith('.json'))yield JSON.parse(await fs.readFile(path.join(stateDirectory,entry.name),'utf8'));}}
 async function readSources(ids){let total=0;const inputs=[];for(const id of ids){const p=await resolveGrant(id,'read');const h=await fs.open(p,'r');try{const stat=await h.stat();total+=stat.size;if(!stat.isFile()||total>LIMITS.inputBytes)throw new Error('Source exceeds the safety limit.');const buffer=Buffer.alloc(stat.size+1);let used=0;while(used<buffer.length){const chunk=await h.read(buffer,used,buffer.length-used,null);if(!chunk.bytesRead)break;used+=chunk.bytesRead;}const bytes=buffer.subarray(0,used);if(bytes.length!==stat.size)throw new Error('Source changed while reading.');inputs.push(bytes);}finally{await h.close();}}return inputs;}
 async function inspect({sourceIds}){const epoch=admissionEpoch;if(closed||cancelling)throw new Error('The converter is stopping.');if(!Array.isArray(sourceIds)||sourceIds.length<1||sourceIds.length>32)throw new Error('Select between one and 32 files per batch.');const inputs=await readSources(sourceIds);const result=[];for(let i=0;i<inputs.length;i++){const b=inputs[i],type=detectFormat(b);let media;const adapter={png:'image-png',jpeg:'image-jpeg',wav:'audio-wav',flac:'audio-flac',mp3:'audio-mp3',mp4:'video-mp4'}[type];if(adapter&&sandboxProvider?.previewMedia){if(closed||cancelling||epoch!==admissionEpoch)throw new Error('The converter is stopping.');const id=randomUUID(),worker=sandboxProvider.previewMedia(b,adapter);previewWorkers.set(id,worker);try{media=await worker.result;}finally{previewWorkers.delete(id);}}result.push({id:sourceIds[i],type,bytes:b.length,sha256:digest(b),media,preview:['text','json'].includes(type)?b.subarray(0,2048).toString('utf8'):null});}return result;}
 async function destinationRoot(request){return request.destinationDirectoryId?await fs.realpath(await resolveGrant(request.destinationDirectoryId,'directory')):await fs.realpath(path.dirname(await resolveGrant(request.destinationId,'write')));}
 async function enqueueWork(request){await init;const epoch=admissionEpoch;if(cancelling||closed)throw new Error('The converter is stopping.');const {sourceIds,destinationId,destinationDirectoryId,adapterId,options={},overwriteConfirmed=false,lossyConfirmed=false}=request;const adapter=adapters().find(a=>a.id===adapterId);if(!adapter?.enabled)throw new Error(adapter?.disabledReason||'Unknown adapter.');if(adapter.lossy&&!lossyConfirmed)throw new Error('Confirm the metadata or encoding change before converting.');const previews=await inspect({sourceIds});if(previews.some(p=>!adapter.sources.includes('*')&&!adapter.sources.includes(p.type)))throw new Error('The adapter does not support this detected source.');if(adapterId==='pdf-merge'&&sourceIds.length<2)throw new Error('Merge requires two or more PDF files.');if(!adapterId.startsWith('pdf-')&&sourceIds.length!==1)throw new Error('This adapter accepts one file per queue item.');if(['pdf-split','zip-extract'].includes(adapterId)&&!destinationDirectoryId)throw new Error('This operation requires an approved destination folder.');if(destinationDirectoryId&&overwriteConfirmed)throw new Error('Folder outputs never replace existing files.');
 const parent=await destinationRoot(request),capacity=await fs.statfs(parent);if(Number(capacity.bavail)*Number(capacity.bsize)<LIMITS.outputBytes+LIMITS.inputBytes)throw new Error('Insufficient free destination capacity.');
 if(!destinationDirectoryId){const destination=await resolveGrant(destinationId,'write');for(const id of sourceIds)if(samePath(await resolveGrant(id,'read'),destination))throw new Error('The destination must differ from every source.');if(!overwriteConfirmed){try{await fs.lstat(destination);throw new Error('Explicit overwrite confirmation is required.');}catch(e){if(e.code!=='ENOENT')throw e;}}}
 const record={id:randomUUID(),sourceIds:[...sourceIds],sourceHashes:previews.map(p=>p.sha256),destinationId,destinationDirectoryId,adapterId,options,overwriteConfirmed,state:'queued',createdAt:new Date().toISOString(),progress:0};if(cancelling||closed||epoch!==admissionEpoch)throw new Error('The converter stopped before this item was admitted.');await save(record);if(cancelling||closed||epoch!==admissionEpoch){await locked(record.id,async current=>{current.state='cancelled';await save(current);});throw new Error('The converter stopped before this item was admitted.');}void run();return publicRecord(record);}
 function enqueue(request){const promise=enqueueWork(request);admissions.add(promise);promise.finally(()=>admissions.delete(promise)).catch(()=>{});return promise;}
 const publicRecord=r=>({id:r.id,adapterId:r.adapterId,state:r.state,progress:r.progress,createdAt:r.createdAt,error:r.error,outputs:r.outputs,details:r.details});
 async function list({offset=0,limit=50}={}){if(!Number.isSafeInteger(offset)||offset<0||!Number.isSafeInteger(limit)||limit<1||limit>LIMITS.queuePage)throw new Error('Invalid queue page.');const rows=[];let index=0;for await(const r of records()){if(index++>=offset&&rows.length<limit)rows.push(publicRecord(r));if(rows.length===limit)break;}return rows;}
 async function control({id,action}){if(action==='resume'&&(cancelling||closed))throw new Error('The converter is stopping.');if(!['pause','resume','cancel'].includes(action))throw new Error('Invalid queue action.');const result=await locked(id,async r=>{if(['completed','failed','cancelled'].includes(r.state))return publicRecord(r);r.state=action==='pause'?'paused':action==='cancel'?'cancelled':'queued';await save(r);return publicRecord(r);});if(action!=='resume')await workers.get(id)?.terminate();else void run();return result;}
 async function publish(r,result){const staged=[],published=[];let total=0;const root=await destinationRoot(r);const sourcePaths=[];for(const id of r.sourceIds)sourcePaths.push(await resolveGrant(id,'read'));
 try{for(let i=0;i<result.outputs.length;i++){const output=result.outputs[i];total+=output.bytes.length;if(total>LIMITS.outputBytes||result.outputs.length>LIMITS.pages)throw new Error('Output budget exceeded.');let target;if(r.destinationDirectoryId){target=await outputLocation(root,output.name);}else{if(result.outputs.length!==1)throw new Error('Multiple outputs require a folder grant.');target=await resolveGrant(r.destinationId,'write');if(!samePath(await fs.realpath(path.dirname(target)),root))throw new Error('Destination changed.');}if(sourcePaths.some(p=>samePath(p,target)))throw new Error('Output would replace a source.');if(!r.overwriteConfirmed){try{await fs.lstat(target);throw new Error('Output already exists.');}catch(e){if(e.code!=='ENOENT')throw e;}}staged.push({target,tmp:target+'.'+r.id+'.tmp',bytes:output.bytes});}
 // Validate the complete destination set before creating or publishing any output.
 if(new Set(staged.map(x=>process.platform==='win32'?x.target.toLowerCase():x.target)).size!==staged.length)throw new Error('Duplicate output names.');
 for(const item of staged){if(r.destinationDirectoryId)await outputLocation(root,path.relative(root,item.target).split(path.sep).join('/'),{createParents:true});await fs.writeFile(item.tmp,item.bytes,{flag:'wx',mode:0o600});}
 for(const item of staged){if(r.overwriteConfirmed)await fs.rename(item.tmp,item.target);else{await fs.link(item.tmp,item.target);published.push(item);await fs.unlink(item.tmp);}}
 r.state='completed';r.progress=100;r.outputs=staged.map(x=>path.basename(x.target));r.details=result.details;await save(r);
 }catch(error){for(const item of published){try{const stat=await fs.lstat(item.target);const temporary=await fs.lstat(item.tmp).catch(()=>null);if(temporary&&stat.ino===temporary.ino)await fs.unlink(item.target);}catch{}}
 if(published.length){r.outputs=published.map(x=>path.basename(x.target));r.error='Publication stopped after one or more complete outputs; inspect the listed output files.';await save(r);}throw error;
 }finally{for(const item of staged)await fs.rm(item.tmp,{force:true});}}
 async function execute(r){const inputs=await readSources(r.sourceIds);if(inputs.some((b,i)=>digest(b)!==r.sourceHashes?.[i]))throw new Error('Source changed since admission.');const admitted=await locked(r.id,async current=>{if(current.state!=='queued'||closed||cancelling)return false;current.state='running';current.progress=10;await save(current);return true;});if(!admitted)return;
 const worker=sandboxProvider.launch({inputs,adapterId:r.adapterId,options:r.options,timeout:LIMITS.milliseconds});workers.set(r.id,worker);const result=await worker.result.finally(()=>workers.delete(r.id));
 await locked(r.id,async current=>{if(current.state!=='running'||closed)return;await publish(current,result);});}
 async function run(){if(closed||cancelling)return;if(running){requested=true;return;}running=true;requested=false;runFinished=new Promise(resolve=>settleRun=resolve);try{for await(const record of records()){if(closed||cancelling)break;if(record.state==='running'){await locked(record.id,async current=>{if(current.state==='running'){current.state='paused';current.error='Interrupted conversion recovered. Resume to revalidate the source and restart.';await save(current);}});continue;}if(record.state!=='queued'||!isolated)continue;try{await execute(record);}catch{await locked(record.id,async current=>{if(['running','queued'].includes(current.state)){current.state='failed';current.error=current.error||'Conversion could not complete. Check the source format, capacity, and adapter limits.';await save(current);}});}}}finally{running=false;settleRun?.();if(requested&&!closed&&!cancelling)void run();}}
 async function pending(){let count=previewWorkers.size;for await(const record of records())if(record.state==='queued'||record.state==='running')count++;return count;}
 async function cancelAll(){if(cancellationFinished)return cancellationFinished;const action=(async()=>{cancelling=true;admissionEpoch++;let cancelled=0;try{await Promise.allSettled([...previewWorkers.values()].map(async worker=>{await worker.terminate();await worker.result.catch(()=>{});}));await Promise.allSettled([...admissions]);for await(const record of records())if(record.state==='queued'||record.state==='running'){const outcome=await control({id:record.id,action:'cancel'});if(outcome.state==='cancelled')cancelled++;}await runFinished;return {cancelled,remaining:await pending()};}finally{cancelling=false;}})();cancellationFinished=action;try{return await action;}finally{cancellationFinished=undefined;}}
 return {pending,cancelAll,catalog:adapters,inspect,enqueue,list,control,run,close:async()=>{closed=true;await cancelAll();}};
}
