import fs from 'node:fs/promises';
import path from 'node:path';
import { randomUUID, createHash } from 'node:crypto';
import { Worker } from 'node:worker_threads';
import { catalog, detectFormat, LIMITS } from './registry.mjs';
export function createConverterService({stateDirectory,resolveGrant,bundledProof={}}) {
 if(typeof resolveGrant!=='function')throw new Error('A trusted file grant resolver is required.');
 let running=false,closed=false;const workers=new Map();
 const recordPath=id=>{if(!/^[0-9a-f-]{36}$/.test(id))throw new Error('Invalid queue identifier.');return path.join(stateDirectory,id+'.json');};
 const save=async record=>{const p=recordPath(record.id),tmp=p+'.tmp';await fs.writeFile(tmp,JSON.stringify(record),{mode:0o600});await fs.rename(tmp,p);};
 const load=async id=>JSON.parse(await fs.readFile(recordPath(id),'utf8'));
 const init=fs.mkdir(stateDirectory,{recursive:true});
 async function* records(){await init;const dir=await fs.opendir(stateDirectory);for await(const entry of dir){if(entry.name.endsWith('.json'))yield JSON.parse(await fs.readFile(path.join(stateDirectory,entry.name),'utf8'));}}
 async function readSources(ids){let total=0;const inputs=[];for(const id of ids){const p=await resolveGrant(id,'read');const h=await fs.open(p,'r');try{const stat=await h.stat();total+=stat.size;if(!stat.isFile()||total>LIMITS.inputBytes)throw new Error('Source exceeds the safety limit.');const buffer=Buffer.alloc(stat.size+1);let used=0;while(used<buffer.length){const chunk=await h.read(buffer,used,buffer.length-used,null);if(!chunk.bytesRead)break;used+=chunk.bytesRead;}const bytes=buffer.subarray(0,used);if(bytes.length!==stat.size)throw new Error('Source changed while reading.');inputs.push(bytes);}finally{await h.close();}}return inputs;}
 async function inspect({sourceIds}){if(!Array.isArray(sourceIds)||sourceIds.length<1||sourceIds.length>32)throw new Error('Select between one and 32 files per batch.');const inputs=await readSources(sourceIds);return inputs.map((b,i)=>({id:sourceIds[i],type:detectFormat(b),bytes:b.length,sha256:createHash('sha256').update(b).digest('hex'),preview:['text','json'].includes(detectFormat(b))?b.subarray(0,2048).toString('utf8'):null}));}
 async function enqueue(request){await init;const {sourceIds,destinationId,adapterId,options={},overwriteConfirmed=false,lossyConfirmed=false}=request;const adapter=catalog(bundledProof).find(a=>a.id===adapterId);if(!adapter?.enabled)throw new Error(adapter?.disabledReason||'Unknown adapter.');if(adapter.lossy&&!lossyConfirmed)throw new Error('Confirm the metadata or encoding change before converting.');const previews=await inspect({sourceIds});if(previews.some(p=>!adapter.sources.includes('*')&&!adapter.sources.includes(p.type)))throw new Error('The adapter does not support this detected source.');if(adapterId==='pdf-merge'&&sourceIds.length<2)throw new Error('Merge requires two or more PDF files.');if(!adapterId.startsWith('pdf-')&&sourceIds.length!==1)throw new Error('This adapter accepts one file per queue item.');
 const destination=await resolveGrant(destinationId,'write');const parent=await fs.realpath(path.dirname(destination));const capacity=await fs.statfs(parent);if(Number(capacity.bavail)*Number(capacity.bsize)<LIMITS.outputBytes+LIMITS.inputBytes)throw new Error('Insufficient free destination capacity.');for(const id of sourceIds){if(path.resolve(await resolveGrant(id,'read'))===path.resolve(destination))throw new Error('The destination must differ from every source.');}if(!overwriteConfirmed){try{await fs.lstat(destination);throw new Error('Explicit overwrite confirmation is required.');}catch(e){if(e.code!=='ENOENT')throw e;}}
 const record={id:randomUUID(),sourceIds:[...sourceIds],sourceHashes:previews.map(p=>p.sha256),destinationId,adapterId,options,overwriteConfirmed,state:'queued',createdAt:new Date().toISOString(),progress:0};await save(record);void run();return publicRecord(record);}
 const publicRecord=r=>({id:r.id,adapterId:r.adapterId,state:r.state,progress:r.progress,createdAt:r.createdAt,error:r.error,outputs:r.outputs,details:r.details});
 async function list({offset=0,limit=50}={}){if(!Number.isSafeInteger(offset)||offset<0||!Number.isSafeInteger(limit)||limit<1||limit>LIMITS.queuePage)throw new Error('Invalid queue page.');const rows=[];let index=0;for await(const r of records()){if(index++>=offset&&rows.length<limit)rows.push(publicRecord(r));if(rows.length===limit)break;}return rows;}
 async function control({id,action}){const r=await load(id);if(!['pause','resume','cancel'].includes(action))throw new Error('Invalid queue action.');if(['completed','failed','cancelled'].includes(r.state))return publicRecord(r);r.state=action==='pause'?'paused':action==='cancel'?'cancelled':'queued';await save(r);if(action!=='resume')await workers.get(id)?.terminate();else void run();return publicRecord(r);}
 async function execute(r){const inputs=await readSources(r.sourceIds);if(inputs.some((b,i)=>createHash('sha256').update(b).digest('hex')!==r.sourceHashes?.[i]))throw new Error('Source changed since admission.');r.state='running';r.progress=10;await save(r);const worker=new Worker(new URL('./worker.mjs',import.meta.url),{workerData:{adapterId:r.adapterId,options:r.options,inputs},resourceLimits:{maxOldGenerationSizeMb:256,maxYoungGenerationSizeMb:32,stackSizeMb:4}});workers.set(r.id,worker);let timer;const result=await new Promise((resolve,reject)=>{timer=setTimeout(()=>{void worker.terminate();reject(new Error('Conversion time limit exceeded.'));},LIMITS.milliseconds);worker.once('message',m=>m.ok?resolve(m.result):reject(new Error(m.error)));worker.once('error',()=>reject(new Error('Conversion worker failed.')));worker.once('exit',()=>reject(new Error('Conversion interrupted.')));}).finally(()=>{clearTimeout(timer);workers.delete(r.id);void worker.terminate();});
 const current=await load(r.id);if(current.state!=='running')return;const destination=await resolveGrant(r.destinationId,'write');let total=0;const staged=[];try{for(let i=0;i<result.outputs.length;i++){const output=result.outputs[i];total+=output.bytes.length;if(total>LIMITS.outputBytes)throw new Error('Output byte budget exceeded.');const target=result.outputs.length===1?destination:path.join(path.dirname(destination),path.parse(destination).name+'-'+String(i+1)+path.extname(destination));for(const sourceId of r.sourceIds)if(path.resolve(await resolveGrant(sourceId,'read'))===path.resolve(target))throw new Error('Output would overwrite a source.');const tmp=target+'.'+r.id+'.tmp';await fs.writeFile(tmp,output.bytes,{flag:'wx',mode:0o600});staged.push({tmp,target});}
 if((await load(r.id)).state!=='running')throw new Error('Conversion cancelled before publication.');for(const item of staged){if(r.overwriteConfirmed)await fs.rename(item.tmp,item.target);else{await fs.link(item.tmp,item.target);await fs.unlink(item.tmp);}}r.state='completed';r.progress=100;r.outputs=staged.map(x=>path.basename(x.target));r.details=result.details;await save(r);}finally{for(const item of staged)await fs.rm(item.tmp,{force:true});}}
 async function run(){if(running||closed)return;running=true;try{for await(const record of records()){if(closed)break;if(record.state==='running'){record.state='paused';record.error='Interrupted conversion recovered. Resume to revalidate the source and restart.';await save(record);}if(record.state!=='queued')continue;try{await execute(record);}catch{const current=await load(record.id);if(['running','queued'].includes(current.state)){current.state='failed';current.error='Conversion could not complete. Check the source format, capacity, and adapter limits.';await save(current);}}}}finally{running=false;}}
 return {catalog:()=>catalog(bundledProof),inspect,enqueue,list,control,run,close:async()=>{closed=true;await Promise.all([...workers.values()].map(w=>w.terminate()));}};
}



