import {readZip,writeZip} from './archive.mjs';
import {convertData} from './data.mjs';
const S='http://schemas.openxmlformats.org/spreadsheetml/2006/main', R='http://schemas.openxmlformats.org/officeDocument/2006/relationships', P='http://schemas.openxmlformats.org/package/2006/relationships';
const O='urn:oasis:names:tc:opendocument:xmlns:office:1.0', T='urn:oasis:names:tc:opendocument:xmlns:table:1.0', X='urn:oasis:names:tc:opendocument:xmlns:text:1.0';
export const TABLE_LIMITS=Object.freeze({bytes:8*1024*1024,rows:10000,columns:256,cells:100000,nodes:300000,depth:32});
const invalid=/[\u0000-\u0008\u000b\u000c\u000e-\u001f\ufffe\uffff]|\p{Surrogate}/u;
function decode(s){if(!/^(?:[^&]|&(?:amp|lt|gt|quot|apos|#[0-9]+|#x[0-9a-f]+);)*$/i.test(s))throw new Error('Malformed XML entity.');return s.replace(/&([^;]+);/g,(_,entity)=>{if(entity==='amp')return '&';if(entity==='lt')return '<';if(entity==='gt')return '>';if(entity==='quot')return '"';if(entity==='apos')return "'";if(/^#(?:[0-9]+|x[0-9a-f]+)$/i.test(entity)){const n=entity[1].toLowerCase()==='x'?parseInt(entity.slice(2),16):Number(entity.slice(1));if(n>0x10ffff||n===0||n>=0xd800&&n<=0xdfff)throw new Error('Invalid XML character.');return String.fromCodePoint(n);}throw new Error('XML entities are not supported.');});}
const escape=s=>{if(invalid.test(s))throw new Error('Unsupported XML character.');return s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&apos;').replaceAll('\r','&#13;');};
/** Small namespace-aware XML reader: no DTD, entity declarations or external loading. */
export function readTableXml(bytes){
 if(bytes.length>TABLE_LIMITS.bytes)throw new Error('Workbook XML exceeds 8 MiB.');
 const text=new TextDecoder('utf-8',{fatal:true}).decode(bytes).replace(/^\uFEFF/,'').replace(/\r\n?/g,'\n');if(invalid.test(text)||/<!DOCTYPE|<!ENTITY/i.test(text))throw new Error('Unsafe XML declaration or character.');
 const document={children:[],ns:{xml:'http://www.w3.org/XML/1998/namespace'}},stack=[document];let i=0,count=0;
 const addText=s=>{if(s.includes('&')&&!/^(?:[^&]|&(?:amp|lt|gt|quot|apos|#[0-9]+|#x[0-9a-f]+);)*$/i.test(s))throw new Error('Malformed XML entity.');if(s){const d=decode(s);if(invalid.test(d))throw new Error('Invalid XML character.');stack.at(-1).children.push(d);}};
 while(i<text.length){if(text[i]!=='<'){const end=text.indexOf('<',i);addText(text.slice(i,end<0?text.length:end));i=end<0?text.length:end;continue;}if(text.startsWith('<!--',i)){const end=text.indexOf('-->',i+4);if(end<0||text.slice(i+4,end).includes('--'))throw new Error('Malformed XML comment.');i=end+3;continue;}if(text.startsWith('<?xml ',i)&&i===0){const end=text.indexOf('?>',i);if(end<0)throw new Error('Malformed XML declaration.');i=end+2;continue;}if(text.startsWith('<![CDATA[',i)){const end=text.indexOf(']]>',i+9);if(end<0)throw new Error('Malformed CDATA.');stack.at(-1).children.push(text.slice(i+9,end));i=end+3;continue;}
 const match=/^<([/]?)([A-Za-z_][\w.:-]*)([^<>]*)>/u.exec(text.slice(i));if(!match)throw new Error('Unsupported XML syntax.');i+=match[0].length;
 if(match[1]){if(match[3].trim()||stack.length===1||stack.at(-1).qualified!==match[2])throw new Error('Mismatched XML element.');stack.pop();continue;}
 let tail=match[3],self=/\/\s*$/.test(tail);if(self)tail=tail.replace(/\/\s*$/,'');const raw={},ns={...stack.at(-1).ns};while(tail.trim()){const a=/^\s+([A-Za-z_][\w.:-]*)\s*=\s*(?:"([^"<]*)"|'([^'<]*)')/u.exec(tail);if(!a||Object.hasOwn(raw,a[1]))throw new Error('Malformed XML attribute.');raw[a[1]]=decode(a[2]??a[3]);tail=tail.slice(a[0].length);}
 for(const [k,v]of Object.entries(raw)){if(k==='xmlns')ns['']=v;else if(k.startsWith('xmlns:'))ns[k.slice(6)]=v;}
 const qualify=(name,attribute=false)=>{const parts=name.split(':');if(parts.length>2||parts.length===2&&!ns[parts[0]])throw new Error('Unbound XML prefix.');return (parts.length===2?ns[parts[0]]:attribute?'':ns['']||'')+'|'+parts.at(-1);};
 const node={name:qualify(match[2]),qualified:match[2],attrs:{},children:[],ns};for(const [k,v]of Object.entries(raw))if(k!=='xmlns'&&!k.startsWith('xmlns:')){const key=qualify(k,true);if(Object.hasOwn(node.attrs,key))throw new Error('Duplicate XML attribute.');node.attrs[key]=v;}
 if(++count>TABLE_LIMITS.nodes||stack.length>TABLE_LIMITS.depth)throw new Error('Workbook XML structure limit exceeded.');stack.at(-1).children.push(node);if(!self)stack.push(node);
 }
 const roots=document.children.filter(n=>typeof n!=='string');if(stack.length!==1||roots.length!==1||document.children.some(n=>typeof n==='string'&&n.trim()))throw new Error('Malformed XML document.');return roots[0];
}
const children=(n,uri,name)=>n.children.filter(c=>typeof c!=='string'&&c.name===uri+'|'+name);
const child=(n,uri,name)=>{const found=children(n,uri,name);if(found.length!==1)throw new Error('Required workbook element missing or duplicated: '+name);return found[0];};
const descendants=(n,uri,name)=>{const result=[];const visit=node=>{if(node.name===uri+'|'+name)result.push(node);for(const c of node.children)if(typeof c!=='string')visit(c);};visit(n);return result;};
const textContent=n=>n.children.map(c=>typeof c==='string'?c:textContent(c)).join('');
const attr=(n,name,uri='')=>n.attrs[uri+'|'+name];
function checkTable(rows){if(!Array.isArray(rows)||rows.some(row=>!Array.isArray(row)))throw new Error('Table must contain string rows.');if(rows.length>TABLE_LIMITS.rows)throw new Error('Table row limit exceeded.');let count=0,totalBytes=0,width=rows[0]?.length||0;if(rows.length&&width===0)throw new Error('Table rows must not be empty.');for(const row of rows){if(row.length!==width||width>TABLE_LIMITS.columns||(count+=row.length)>TABLE_LIMITS.cells)throw new Error('Table shape or cell limit exceeded.');for(const value of row){if(typeof value!=='string'||invalid.test(value))throw new Error('Unsupported table value.');totalBytes+=Buffer.byteLength(value);if(totalBytes>TABLE_LIMITS.bytes)throw new Error('Table byte limit exceeded.');}}if(Buffer.byteLength(JSON.stringify(rows))>TABLE_LIMITS.bytes)throw new Error('Table byte limit exceeded.');return rows;}
function dense(rows){let width=0;for(const row of rows)if(row)width=Math.max(width,row.length);if(width*rows.length>TABLE_LIMITS.cells)throw new Error('Dense table cell limit exceeded.');for(let i=0;i<rows.length;i++){rows[i]||=[];for(let j=0;j<width;j++)rows[i][j]??='';}return checkTable(rows);}
function filesOf(bytes){const entries=readZip(bytes);if(entries.some(e=>/vbaProject|externalLinks|embeddings|activeX/i.test(e.name)))throw new Error('Macros, external links and embedded objects are unsupported.');return new Map(entries.map(e=>[e.name,e.bytes]));}
function xmlFile(files,name){if(!files.has(name))throw new Error('Required workbook part missing: '+name);return readTableXml(files.get(name));}
function readXlsx(bytes){const files=filesOf(bytes);for(const [name,data]of files)if(name.endsWith('.rels')){const rels=readTableXml(data);if(rels.name!==P+'|Relationships')throw new Error('Invalid relationships.');for(const r of children(rels,P,'Relationship'))if(attr(r,'TargetMode'))throw new Error('External workbook relationships are unsupported.');}
 const workbook=xmlFile(files,'xl/workbook.xml');if(workbook.name!==S+'|workbook')throw new Error('Invalid XLSX workbook.');const sheets=children(child(workbook,S,'sheets'),S,'sheet');if(sheets.length!==1)throw new Error('Select a workbook containing exactly one sheet.');if(attr(sheets[0],'state')&&attr(sheets[0],'state')!=='visible')throw new Error('Hidden sheets are unsupported.');
 const rels=xmlFile(files,'xl/_rels/workbook.xml.rels');const rel=children(rels,P,'Relationship').find(r=>attr(r,'Id')===attr(sheets[0],'id',R));if(!rel||!attr(rel,'Type')?.endsWith('/worksheet'))throw new Error('Worksheet relationship missing.');const target=attr(rel,'Target');if(!target||target.includes('..')||target.includes('\\')||target.includes(':')||target.startsWith('//'))throw new Error('Unsafe worksheet target.');const name=target.startsWith('/')?target.slice(1):'xl/'+target;
 let strings=[];if(files.has('xl/sharedStrings.xml')){const shared=xmlFile(files,'xl/sharedStrings.xml');if(shared.name!==S+'|sst')throw new Error('Invalid shared strings.');strings=children(shared,S,'si').map(si=>descendants(si,S,'t').map(textContent).join(''));}
 const sheet=xmlFile(files,name);if(sheet.name!==S+'|worksheet')throw new Error('Invalid worksheet.');for(const tag of ['mergeCells','drawing','legacyDrawing','hyperlinks','oleObjects'])if(descendants(sheet,S,tag).length)throw new Error('Merged cells, drawings and hyperlinks are unsupported.');
 const rows=[],seen=new Set();for(const row of children(child(sheet,S,'sheetData'),S,'row')){if(attr(row,'hidden')==='1'||attr(row,'hidden')==='true')throw new Error('Hidden rows are unsupported.');for(const c of children(row,S,'c')){if(children(c,S,'f').length)throw new Error('Formula cells are unsupported.');const ref=/^([A-Z]{1,3})([1-9][0-9]*)$/.exec(attr(c,'r')||'');if(!ref||seen.has(ref[0]))throw new Error('Invalid or duplicate cell reference.');seen.add(ref[0]);let column=0;for(const letter of ref[1])column=column*26+letter.charCodeAt(0)-64;const r=Number(ref[2])-1;if(r>=TABLE_LIMITS.rows||column>TABLE_LIMITS.columns||seen.size>TABLE_LIMITS.cells)throw new Error('Table dimensions exceed limits.');rows[r]||=[];const type=attr(c,'t'),values=children(c,S,'v');let value='';if(type==='inlineStr')value=descendants(child(c,S,'is'),S,'t').map(textContent).join('');else if(type==='s'){const index=textContent(child(c,S,'v'));if(!/^(0|[1-9][0-9]*)$/.test(index)||Number(index)>=strings.length)throw new Error('Invalid shared string index.');value=strings[Number(index)];}else if([undefined,'n','b','str','d'].includes(type)){if(values.length>1)throw new Error('Duplicate cell value.');value=values.length?textContent(values[0]):'';if(type==='b'&&!['0','1'].includes(value))throw new Error('Invalid boolean cell.');}else throw new Error('Unsupported cell type.');rows[r][column-1]=value;}}
 return dense(rows);
}
function odsText(node){return node.children.map(c=>{if(typeof c==='string')return c;if(c.name===X+'|s'){const count=Number(attr(c,'c',X)||1);if(!Number.isSafeInteger(count)||count<1||count>65536)throw new Error('Repeated whitespace limit exceeded.');return ' '.repeat(count);}if(c.name===X+'|tab')return '\t';if(c.name===X+'|line-break')return '\n';if(c.name===X+'|span')return odsText(c);throw new Error('Unsupported ODS text content.');}).join('');}
function readOds(bytes){const files=filesOf(bytes);if(files.get('mimetype')?.toString()!=='application/vnd.oasis.opendocument.spreadsheet')throw new Error('Invalid ODS media type.');const document=xmlFile(files,'content.xml');if(document.name!==O+'|document-content')throw new Error('Invalid ODS content.');const spreadsheet=child(child(document,O,'body'),O,'spreadsheet'),tables=children(spreadsheet,T,'table');if(tables.length!==1)throw new Error('Select a workbook containing exactly one table.');const rows=[];for(const row of children(tables[0],T,'table-row')){const repeat=Number(attr(row,'number-rows-repeated',T)||1);if(!Number.isSafeInteger(repeat)||repeat<1||rows.length+repeat>TABLE_LIMITS.rows)throw new Error('Repeated row limit exceeded.');const cells=[];for(const c of row.children.filter(n=>typeof n!=='string')){if(c.name!==T+'|table-cell'||attr(c,'formula',T)||attr(c,'number-columns-spanned',T)||attr(c,'number-rows-spanned',T)||descendants(c,T,'table').length)throw new Error('Formulas, merged cells and nested tables are unsupported.');const count=Number(attr(c,'number-columns-repeated',T)||1);if(!Number.isSafeInteger(count)||count<1||cells.length+count>TABLE_LIMITS.columns)throw new Error('Repeated column limit exceeded.');const type=attr(c,'value-type',O);let value;if(!type||type==='string')value=attr(c,'string-value',O)??children(c,X,'p').map(odsText).join('\n');else if(['float','percentage','currency'].includes(type))value=attr(c,'value',O);else if(type==='boolean')value=attr(c,'boolean-value',O);else if(type==='date')value=attr(c,'date-value',O);else if(type==='time')value=attr(c,'time-value',O);else throw new Error('Unsupported ODS value type.');if(value===undefined)throw new Error('Missing ODS value.');for(let i=0;i<count;i++)cells.push(value);}if((rows.length+repeat)*cells.length>TABLE_LIMITS.cells)throw new Error('Table cell limit exceeded.');for(let i=0;i<repeat;i++)rows.push([...cells]);}return dense(rows);}
const xml=body=>Buffer.from('<?xml version="1.0" encoding="UTF-8"?>'+body);
function writeXlsx(rows){let body='';for(let r=0;r<rows.length;r++){body+='<row r="'+(r+1)+'">';for(let c=0;c<rows[r].length;c++){let col='',n=c+1;while(n){n--;col=String.fromCharCode(65+n%26)+col;n=Math.floor(n/26);}body+='<c r="'+col+(r+1)+'" t="inlineStr"><is><t xml:space="preserve">'+escape(rows[r][c])+'</t></is></c>';}body+='</row>';}
 return writeZip([{name:'[Content_Types].xml',bytes:xml('<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>')},{name:'_rels/.rels',bytes:xml('<Relationships xmlns="'+P+'"><Relationship Id="r1" Type="'+R+'/officeDocument" Target="xl/workbook.xml"/></Relationships>')},{name:'xl/workbook.xml',bytes:xml('<workbook xmlns="'+S+'" xmlns:r="'+R+'"><sheets><sheet name="Table" sheetId="1" r:id="r1"/></sheets></workbook>')},{name:'xl/_rels/workbook.xml.rels',bytes:xml('<Relationships xmlns="'+P+'"><Relationship Id="r1" Type="'+R+'/worksheet" Target="worksheets/sheet1.xml"/></Relationships>')},{name:'xl/worksheets/sheet1.xml',bytes:xml('<worksheet xmlns="'+S+'"><sheetData>'+body+'</sheetData></worksheet>')}]);
}
function writeOds(rows){const content='<office:document-content xmlns:office="'+O+'" xmlns:table="'+T+'" xmlns:text="'+X+'" office:version="1.3"><office:body><office:spreadsheet><table:table table:name="Table">'+rows.map(row=>'<table:table-row>'+row.map(value=>'<table:table-cell office:value-type="string"><text:p>'+escape(value)+'</text:p></table:table-cell>').join('')+'</table:table-row>').join('')+'</table:table></office:spreadsheet></office:body></office:document-content>';return writeZip([{name:'mimetype',bytes:Buffer.from('application/vnd.oasis.opendocument.spreadsheet')},{name:'content.xml',bytes:xml(content)},{name:'META-INF/manifest.xml',bytes:xml('<manifest:manifest xmlns:manifest="urn:oasis:names:tc:opendocument:xmlns:manifest:1.0" manifest:version="1.3"><manifest:file-entry manifest:full-path="/" manifest:media-type="application/vnd.oasis.opendocument.spreadsheet"/><manifest:file-entry manifest:full-path="content.xml" manifest:media-type="text/xml"/></manifest:manifest>')}]);}
export function convertTable(id,inputs,options={}){const match=/^(xlsx|ods|csv|tsv|json)-to-(xlsx|ods|csv|tsv|json)$/.exec(id);if(!match||match[1]===match[2]||!['xlsx','ods'].some(x=>match.slice(1).includes(x))||inputs.length!==1||inputs[0].length>TABLE_LIMITS.bytes)throw new Error('Unsupported workbook conversion or input limit.');const [source,target]=match.slice(1);let rows;if(source==='xlsx')rows=readXlsx(inputs[0]);else if(source==='ods')rows=readOds(inputs[0]);else if(source==='json')rows=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(inputs[0]));else rows=JSON.parse(Buffer.from(convertData(source+'-to-json',inputs,{...options,formulaPolicy:'preserve'}).outputs[0].bytes));checkTable(rows);
 const policy=options.formulaPolicy??'reject';if(!['preserve','escape','reject'].includes(policy))throw new Error('Invalid formula policy.');let formulaCells=0;rows=rows.map(row=>row.map(cell=>{if(/^\s*[=+\-@\t\r]/u.test(cell)){formulaCells++;if(policy==='reject')throw new Error('Formula-like cell rejected by selected policy.');if(policy==='escape')return "'"+cell;}return cell;}));checkTable(rows);
 let bytes;if(target==='xlsx'||target==='ods'){bytes=target==='xlsx'?writeXlsx(rows):writeOds(rows);const decoded=target==='xlsx'?readXlsx(bytes):readOds(bytes);if(JSON.stringify(decoded)!==JSON.stringify(rows))throw new Error('Workbook round-trip validation failed.');}else if(target==='json')bytes=Buffer.from(JSON.stringify(rows));else bytes=convertData('json-to-'+target,[Buffer.from(JSON.stringify(rows))],{...options,formulaPolicy:'preserve'}).outputs[0].bytes;
 if(bytes.length>TABLE_LIMITS.bytes)throw new Error('Workbook output exceeds 8 MiB.');return{outputs:[{name:'converted.'+target,bytes}],details:{rows:rows.length,columns:rows[0]?.length||0,formulaCells,formulaPolicy:policy,warnings:['Single-sheet table only. Formatting, formulas, workbook metadata and original value types are not preserved. Numeric, date and boolean cells become their stored text values.']}};
}
