import {createArchiveLauncher,ARCHIVE_IDS} from './archive-runtime.mjs';
import {createMediaLauncher, MEDIA_IDS} from './media.mjs';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import { spawn } from 'node:child_process';
import { randomBytes, createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
const require=createRequire(import.meta.url);
const codeDirectory=path.dirname(fileURLToPath(import.meta.url));
async function hash(filename){return createHash('sha256').update(await fs.readFile(filename)).digest('hex');}
async function packageRoot(name){let root=path.dirname(require.resolve(name));while(root!==path.dirname(root)){try{const manifest=JSON.parse(await fs.readFile(path.join(root,'package.json'),'utf8'));if(manifest.name===name)return root;}catch{}root=path.dirname(root);}throw new Error('Bundled PDF package unavailable.');}
/** Call only with package-owned executables whose hashes were verified by the build manifest. */
async function createWindowsSandboxProviderInternal({launcherPath,launcherSha256,runtimePath,runtimeSha256,launcherCompanionHashes={},mediaRuntime,archiveRuntime,onDiagnostic}) {
 if(process.platform!=='win32')throw new Error('AppContainer conversion is supported only on Windows.');
 const companions=[];for(const suffix of ['.dll','.runtimeconfig.json','.deps.json']){const filename=launcherPath.slice(0,-4)+suffix;if(await fs.access(filename).then(()=>true,()=>false)){const expected=launcherCompanionHashes[path.basename(filename)];if(!/^[0-9a-f]{64}$/.test(expected)||await hash(filename)!==expected)throw new Error('Sandbox companion verification failed.');companions.push([filename,expected]);}}
 for(const [filename,expected] of [[launcherPath,launcherSha256],[runtimePath,runtimeSha256]])if(!path.isAbsolute(filename)||!/^[0-9a-f]{64}$/.test(expected)||await hash(filename)!==expected)throw new Error('Sandbox executable verification failed.');
 const initializationDiagnostics=[];const report=(error,component)=>{const diagnostic=safeConverterDiagnostic(error,component);initializationDiagnostics.push(diagnostic);try{onDiagnostic?.(diagnostic);}catch{}};
 let media=null,mediaUnavailableReason='Verified bundled FFmpeg 9.0.2 runtime is unavailable.';if(mediaRuntime){try{media=await createMediaLauncher({launcherPath,launcherSha256,launcherCompanionHashes,...mediaRuntime});}catch(error){report(error,'media');mediaUnavailableReason='Bundled media runtime could not pass executable and AppContainer startup verification.';}}
 let archive=null,archiveUnavailableReason='Verified bundled 7-Zip 26.04 runtime is unavailable.';if(archiveRuntime){try{archive=await createArchiveLauncher({launcherPath,launcherSha256,launcherCompanionHashes,...archiveRuntime});}catch(error){report(error,'archive');archiveUnavailableReason='Bundled archive runtime did not pass executable and AppContainer startup verification.';}}
 const provider={initializationDiagnostics,verifiedOsIsolation:false,verifiedArchiveRuntime:Boolean(archive),archiveUnavailableReason,verifiedMediaRuntime:Boolean(media),verifiedMediaProfile:mediaRuntime?.profile||'default',mediaUnavailableReason,previewMedia:media?.preview,launch({inputs,adapterId,options,timeout=30000}) {
 if(ARCHIVE_IDS.includes(adapterId)){if(!archive)throw new Error(archiveUnavailableReason);return archive.launch({inputs,adapterId});}
 if(MEDIA_IDS.includes(adapterId)){if(!media)throw new Error('Bundled media runtime verification is missing.');return media.launch({inputs,adapterId,options});}
 let child,staging,stopped=false;const nonce=randomBytes(32).toString('hex');
 const result=(async()=>{try{if((await Promise.all(companions.map(async([p,h])=>await hash(p)===h))).some(ok=>!ok)||await hash(launcherPath)!==launcherSha256||await hash(runtimePath)!==runtimeSha256)throw new Error('Sandbox executable changed.');if(!Array.isArray(inputs)||inputs.reduce((n,b)=>n+b.length,0)>64*1024*1024)throw new Error('Input limit exceeded.');if(JSON.stringify(options||{}).length>65536)throw new Error('Options limit exceeded.');const capacity=await fs.statfs(os.tmpdir());if(Number(capacity.bavail)*Number(capacity.bsize)<384*1024*1024)throw new Error('Insufficient temporary capacity for isolated conversion.');staging=await fs.mkdtemp(path.join(os.tmpdir(),'converter-isolated-'));const payload=path.join(staging,'payload'),work=path.join(staging,'work');await fs.mkdir(path.join(payload,'code'),{recursive:true});await fs.mkdir(work);await fs.copyFile(runtimePath,path.join(payload,'node.exe'));await fs.copyFile(path.join(codeDirectory,'os-worker.mjs'),path.join(payload,'worker.mjs'));for(const name of ['registry.mjs','pdf.mjs','archive.mjs','data.mjs','table.mjs','convert.mjs'])await fs.copyFile(path.join(codeDirectory,name),path.join(payload,'code',name));
 if(adapterId.startsWith('pdf-'))for(const name of ['pdf-lib','@pdf-lib/standard-fonts','@pdf-lib/upng','pako','tslib'])await fs.cp(await packageRoot(name),path.join(payload,'node_modules',name),{recursive:true,dereference:true});
 const names=[];for(let i=0;i<inputs.length;i++){const name=`input-${i}.bin`;await fs.writeFile(path.join(work,name),inputs[i],{flag:'wx',mode:0o600});names.push(name);}await fs.writeFile(path.join(work,'request.json'),JSON.stringify({schema:1,nonce,inputs:names,adapterId,options}),{flag:'wx',mode:0o600});const manifest={schema:1,nonce,runtime:path.join(payload,'node.exe'),worker:path.join(payload,'worker.mjs'),directory:staging,timeoutMs:Math.min(timeout,30000),memoryBytes:268435456};const manifestPath=path.join(staging,'launcher.json');await fs.writeFile(manifestPath,JSON.stringify(manifest),{flag:'wx',mode:0o600});if(stopped)throw new Error('Cancelled.');
 const receipt=await new Promise((resolve,reject)=>{child=spawn(launcherPath,['--request',manifestPath],{windowsHide:true,stdio:['ignore','pipe','ignore'],env:{SystemRoot:process.env.SystemRoot,WINDIR:process.env.WINDIR,TEMP:os.tmpdir(),TMP:os.tmpdir(),LOCALAPPDATA:process.env.LOCALAPPDATA,APPDATA:process.env.APPDATA,USERPROFILE:process.env.USERPROFILE,HOMEDRIVE:process.env.HOMEDRIVE,HOMEPATH:process.env.HOMEPATH}});let output='';const timer=setTimeout(()=>{child.kill();reject(new Error('Sandbox timeout.'));},Math.min(timeout,30000)+10000);child.stdout.on('data',chunk=>{output+=chunk.toString();if(output.length>8192){child.kill();reject(new Error('Invalid sandbox receipt.'));}});child.once('error',()=>{clearTimeout(timer);reject(new Error('Sandbox launch failed.'));});child.once('exit',code=>{clearTimeout(timer);try{const value=JSON.parse(output);if(code!==0||value.schema!==1||value.nonce!==nonce||value.isolated!==true||value.exitCode!==0||value.timedOut||value.profileDeleted!==true||value.networkCapabilities!==0||value.activeProcessLimit!==1||value.memoryBytes!==268435456||value.timeoutMs!==30000||value.appContainerVerified!==true||value.capabilityCount!==0||value.jobLimitsVerified!==true)throw new Error('Native sandbox exit '+code+', worker '+value.exitCode+', native '+value.nativeError+', '+value.error);resolve(value);}catch(error){reject(new Error('Sandbox did not return verified success. '+error.message));}});});
 if(!receipt||stopped)throw new Error('Cancelled.');const resultFile=path.join(work,'result.json');if((await fs.stat(resultFile)).size>1024*1024)throw new Error('Result metadata limit.');if(await hash(resultFile)!==receipt.resultSha256)throw new Error('Sandbox result hash mismatch.');const decoded=JSON.parse(await fs.readFile(resultFile,'utf8'));if(decoded.schema!==1||decoded.nonce!==nonce||!Array.isArray(decoded.outputs)||decoded.outputs.length>1000)throw new Error('Invalid sandbox output.');let total=0;const outputs=[];for(const output of decoded.outputs){if(!/^result-\d+\.bin$/.test(output.filename))throw new Error('Invalid sandbox output name.');const p=path.join(work,output.filename),stat=await fs.lstat(p);total+=stat.size;if(!stat.isFile()||stat.isSymbolicLink()||stat.size!==output.bytes||total>128*1024*1024)throw new Error('Sandbox output limit.');outputs.push({name:output.name,bytes:await fs.readFile(p)});}return {outputs,details:decoded.details};
 }catch(error){let diagnostic;try{diagnostic=JSON.parse(await fs.readFile(path.join(staging,'work','error.json'),'utf8'));}catch{}if(diagnostic)throw new Error(error.message+' Worker '+diagnostic.name+': '+diagnostic.code);throw error;}finally{if(staging)await fs.rm(staging,{recursive:true,force:true,maxRetries:3});}})();
 return {result,terminate:async()=>{stopped=true;if(staging&&child)await fs.writeFile(path.join(staging,'work','cancel.signal'),'cancel',{flag:'w'}).catch(()=>{});}};
 }};
 const probe=await provider.launch({inputs:[Buffer.from('sandbox')],adapterId:'hex',options:{}}).result;
 if(probe.outputs.length!==1||probe.outputs[0].bytes.toString()!=='73616e64626f78')throw new Error('Sandbox startup verification failed.');
 provider.verifiedOsIsolation=true;return provider;
}

export function safeConverterDiagnostic(error,component='provider'){
 const codes=new Set(['ENOENT','EACCES','EPERM','EINVAL','ENOTDIR','EISDIR','ENOSPC','ETIMEDOUT','ABORT_ERR']);
 const phases=new Set(['media-probe','media-encode','media-validate','media-initialize']);
 return Object.freeze({schema:1,component:['provider','media','archive'].includes(component)?component:'provider',phase:phases.has(error?.converterPhase)?error.converterPhase:'initialize',code:codes.has(error?.code)?error.code:'INITIALIZATION_FAILED',errorName:['Error','TypeError','RangeError','SyntaxError'].includes(error?.name)?error.name:'Error'});
}
export async function createWindowsSandboxProvider(config){try{return await createWindowsSandboxProviderInternal(config);}catch(error){const diagnostic=safeConverterDiagnostic(error,'provider');error.converterDiagnostic=diagnostic;try{config?.onDiagnostic?.(diagnostic);}catch{}throw error;}}
