export const ACCESS_COPY = Object.freeze({
 'Profile operation was cancelled.':'個人檔案操作已取消。',
 'Persistent waiting budget storage is unavailable.':'無法使用持續儲存的等候配額。','Persistent waiting budget is invalid.':'持續儲存的等候配額無效。','Atomic waiting budget storage is unavailable. Wait for the timer instead.':'無法以不可分割操作儲存等候配額，請等待計時結束。','Persistent waiting budget could not be verified.':'未能核實持續儲存的等候配額。',
  'Invalid protected-cache salt.':'受保護快取嘅鹽值無效。',
  'Authenticator registration QR code':'驗證器登記 QR 碼',
  'The verified dish catalog is unavailable. This challenge starts with arithmetic.':'已核實嘅點心目錄暫時未能使用。今次挑戰由算術開始。',
  'Local access':'本機存取',
  'These local convenience locks do not encrypt files. Reset them by clearing this application’s local data.':'呢啲本機便利鎖唔會加密檔案。清除呢個應用程式嘅本機資料就可以重設。',
  'Clear':'清除','PIN keypad':'PIN 數字鍵盤','Backspace':'刪除上一個字元','Local profile':'本機個人檔案','Profile password':'個人檔案密碼',
  'Private cache is locked.':'私人快取已鎖定。','Private cache is unlocked until logout or application close.':'私人快取已解鎖，登出或者關閉應用程式就會再鎖上。',
  'Set up local profile':'設定本機個人檔案','Unlock local profile':'解鎖本機個人檔案','Log out':'登出','Unlock':'解鎖','Lock again':'重新鎖定','Locked':'已鎖定','Remove lock':'移除鎖定',
  'This element is locked.':'呢個項目已鎖定。','The values did not match, or the waiting period is active.':'輸入資料唔吻合，或者仲喺等候時間內。','Cancel':'取消','Support Tickets':'支援單',
  'Lock an element':'鎖定一個項目','Element identifier':'項目識別碼','Credential policy':'驗證組合','Password':'密碼','Current code':'目前驗證碼','Authenticator URI':'驗證器 URI',
  'Unlock minutes (0 means until closing)':'解鎖分鐘數（0 代表直到關閉）','I understand the local reset route and convenience-only protection.':'我明白本機重設方法，同埋呢個鎖只提供便利保護。',
  'Create lock':'建立鎖定','Confirm the disclosure first.':'請先確認說明。','The local credential vault is unavailable.':'本機憑證保險庫未能使用。',
  'Authenticator':'驗證器','QR generation and decoding run locally. Reveal registration information only in a private setting.':'QR 碼產生同解讀都喺本機進行。請只喺私人環境顯示登記資料。',
  'Manual base32 secret':'手動輸入 base32 密鑰','Issuer':'發行者','Account':'帳戶','Group':'群組','Algorithm':'演算法','Digits':'位數','Period in seconds':'週期秒數',
  'Registration imported locally. Enter its current code to confirm.':'登記資料已匯入本機。請輸入目前驗證碼確認。','Generate registration secret':'產生登記密鑰','Reveal registration QR and manual secret':'顯示登記 QR 碼同手動密鑰','Hide registration details':'隱藏登記資料',
  'Import QR image':'匯入 QR 碼圖片','Read QR image from clipboard':'讀取剪貼簿嘅 QR 碼圖片','Clipboard image reading is unavailable.':'未能讀取剪貼簿圖片。','The clipboard has no supported image.':'剪貼簿冇支援嘅圖片。',
  'Scan QR with camera':'用鏡頭掃描 QR 碼','Camera access is unavailable.':'未能使用鏡頭。','Camera scan timed out.':'鏡頭掃描已逾時。','Stop camera':'停止鏡頭',
  'Search authenticators':'搜尋驗證器','Next code':'下一個驗證碼','Copy code':'複製驗證碼','Edit':'編輯','Move up':'上移','Move down':'下移','Remove':'移除','Save authenticator':'儲存驗證器','The code did not match.':'驗證碼唔吻合。','Cancel editing':'取消編輯',
  'Nothing is sent anywhere. No ticket exists outside this machine, no network request is made, no data is collected, and nobody is reading it.':'任何資料都唔會傳送出去。支援單只喺呢部電腦存在，唔會發出網絡請求，唔會收集資料，亦冇人睇緊。',
  'Category':'類別','Description':'描述','Search local tickets':'搜尋本機支援單','Local ticket storage is unavailable.':'本機支援單儲存未能使用。','Advance local ticket':'推進本機支援單狀態','Created locally':'已喺本機建立','Reviewed by the local automated desk':'本機自動支援台已檢視','Resolved: open the application data folder to reset local data':'已提供解決方法：開啟應用程式資料夾以重設本機資料',
  'Local ticket data could not be read.':'讀唔到本機支援單資料。','Create local ticket':'建立本機支援單','Remove a local ticket before creating another (limit 100).':'請先移除一張本機支援單先再建立（上限 100 張）。','Application data folder unavailable.':'應用程式資料夾未能使用。','Open application data folder':'開啟應用程式資料夾',
  'A credential is required.':'請輸入驗證資料。','Protected record exceeds the 1 MiB limit.':'受保護記錄超過 1 MiB 上限。','Unsupported protected record.':'唔支援呢種受保護記錄。','Protected record exceeds its limits.':'受保護記錄超過上限。','Invalid base32 secret.':'base32 密鑰無效。','Only TOTP registration is supported.':'只支援 TOTP 登記。','Invalid TOTP parameters.':'TOTP 參數無效。',
  'Legacy protected data used an exposed key derivation and is not treated as secure. Automatic migration is unavailable; reset or explicitly re-import from a trusted original.':'舊版受保護資料用咗已暴露嘅金鑰衍生方法，唔再視為安全。未能自動遷移；請重設，或者明確由可信原本重新匯入。',
  'Profile unlock was cancelled.':'個人檔案解鎖已取消。','Wait before trying another profile password.':'請等一陣先再試個人檔案密碼。','A local profile already exists. Unlock it instead.':'本機個人檔案已存在。請解鎖現有檔案。','The password did not match.':'密碼唔吻合。','Unlock the local profile first.':'請先解鎖本機個人檔案。',
  'Select a valid lock policy.':'請揀有效嘅鎖定驗證組合。','This element already has a lock. Unlock and remove that lock before creating a replacement.':'呢個項目已經有鎖。請先解鎖同移除原有鎖，再建立新鎖。','Confirm the authenticator code first.':'請先確認驗證器驗證碼。','Use a PIN of 4 to 12 digits.':'請用 4 至 12 位數字 PIN。',
  'Registration URI is too large.':'登記 URI 太長。','QR image exceeds the 4 megapixel limit.':'QR 碼圖片超過 400 萬像素上限。','No readable QR code was found.':'搵唔到讀得到嘅 QR 碼。','Choose a PNG, JPEG, WebP or GIF image smaller than 8 MiB.':'請揀小過 8 MiB 嘅 PNG、JPEG、WebP 或 GIF 圖片。',
  'Try the waiting ladder':'試吓等候階梯','Waiting ladder':'等候階梯','Winning ends the wait only. Your credentials are still required.':'完成只會結束等候，仍然要輸入驗證資料。','Wait remaining':'剩餘等候時間','Seconds':'秒','The waiting period is over. Enter your credentials again.':'等候已結束。請重新輸入驗證資料。','The clock is the only remaining route for this waiting period.':'今次等候只可以等時間過。','Submit answers':'提交答案','Choose the dumpling':'揀餃子','Steamed bun':'包子','Dumpling':'餃子','Rice roll':'腸粉','Egg tart':'蛋撻','Hit visible moles':'按出現嘅鼴鼠','Mole':'鼴鼠','Empty cell':'空格','Score':'得分','Round remaining':'回合剩餘時間','Finish round':'完成回合','Try the next challenge':'試下一個挑戰','Challenge expired or answer did not match.':'挑戰已逾時，或者答案唔吻合。','Close':'關閉'
});
