import {LocalProfile} from './profile.js';
import {LockController,LOCK_POLICIES} from './locks.js';
import {parseOtpUri,validateOtp,totp,verifyTotp,randomId,passwordVerifier,verifyPassword,deriveCacheKey,seal,unseal} from './crypto.js';
import {otpUri,qrSvg,decodeQrBlob,decodeQrPixels} from './qr.js';
export * from './crypto.js';
export * from './locks.js';

export function mountAccess(container,services={}) {
  const document=container.ownerDocument;const renderedTranslations=new Map();const t=(key,fallback,options={})=>{const value=services.translate?.(fallback,options)??services.t?.(key,fallback,options)??fallback;renderedTranslations.set(value,{key,fallback,options});return value;};const translate=(text,message=false)=>{const original=renderedTranslations.get(text);return t(original?.key||text,original?.fallback||text,{...original?.options,message});};const cleanups=[];const waitingClosers=new Set();const entries=new Map();const tickets=[];
  const controller=new LockController({store:services.credentialStore,getDishChallenge:services.getDishChallenge,onBlocked:id=>{services.notify?.(t('access.locked','This element is locked.'));openUnlock(id);}});
  const root=document.createElement('section');root.className='access-workspace';root.setAttribute('aria-label',t('access.title','Local access'));container.append(root);
  const heading=document.createElement('h2');heading.textContent=t('access.title','Local access');root.append(heading);
  const notice=document.createElement('p');notice.textContent=t('access.disclosure','These local convenience locks do not encrypt files. Reset them by clearing this application’s local data.');root.append(notice);
  function button(label,action,parent=root){const b=document.createElement('button');b.type='button';b.textContent=label;b.addEventListener('click',action);parent.append(b);return b;}
  function field(label,type='text',parent=root){const wrap=document.createElement('label');wrap.textContent=label;const input=document.createElement('input');input.type=type;input.autocomplete='off';wrap.append(input);button(t('access.clear','Clear')+' '+label,()=>{input.value='';input.dispatchEvent(new Event('input',{bubbles:true}));input.focus();},wrap);parent.append(wrap);return input;}
  function keypad(input,parent){const pad=document.createElement('div');pad.setAttribute('role','group');pad.setAttribute('aria-label',t('access.keypad','PIN keypad'));for(const digit of '1234567890')button(digit,()=>{input.value+=digit;input.dispatchEvent(new Event('input',{bubbles:true}));input.focus();},pad);button(t('access.backspace','Backspace'),()=>{input.value=input.value.slice(0,-1);input.focus();},pad);parent.append(pad);return pad;}
  const output=document.createElement('p');output.setAttribute('role','status');root.append(output);
  const report=error=>{output.textContent=translate(error?.message||String(error),true);};
  const profile=document.createElement('fieldset');root.append(profile);const pl=document.createElement('legend');pl.textContent=t('access.profile','Local profile');profile.append(pl);
  const profilePassword=field(t('access.profilePassword','Profile password'),'password',profile);
  const profileStatus=document.createElement('p');profileStatus.setAttribute('role','status');profileStatus.textContent=t('access.profileLocked','Private cache is locked.');profile.append(profileStatus);
  const profileSession=new LocalProfile({store:services.credentialStore,onAuthenticatedChange:authenticated=>{profileStatus.textContent=authenticated?t('access.profileUnlocked','Private cache is unlocked until logout or application close.'):t('access.profileLocked','Private cache is locked.');services.onAuthenticatedChange?.(authenticated);}});
  function endSession(){profileSession.logout();profilePassword.value='';stopCamera();qrPreview.replaceChildren();qrPreview.hidden=true;secret.value='';uri.value='';confirmation.value='';}
  async function unlockProfile(create=false){const password=profilePassword.value;profilePassword.value='';try{await profileSession.unlock(password,{create});}catch(e){report(e);}}
  button(t('access.setupProfile','Set up local profile'),()=>unlockProfile(true),profile);
  button(t('access.unlockProfile','Unlock local profile'),()=>unlockProfile(false),profile);
  button(t('access.logout','Log out'),endSession,profile);
  const encryptPrivateCache=(value,identity)=>profileSession.encrypt(value,identity);
  const decryptPrivateCache=(value,identity)=>profileSession.decrypt(value,identity);  const lockList=document.createElement('div');root.append(lockList);
  function refreshLocks(){lockList.replaceChildren();for(const record of controller.list()){const row=document.createElement('div');row.textContent=`${record.id}: ${record.policy}`;button(t('access.unlock','Unlock'),()=>openUnlock(record.id),row);button(t('access.relock','Lock again'),()=>{controller.lock(record.id);output.textContent=t('access.locked','Locked');},row);button(t('access.remove','Remove lock'),()=>openUnlock(record.id,true),row);lockList.append(row);}}
  function openWaiting(id,parent){
    const panel=document.createElement('fieldset');const legend=document.createElement('legend');legend.textContent=t('access.waitingLadder','Waiting ladder');panel.append(legend);parent.append(panel);
    const disclosure=document.createElement('p');disclosure.textContent=t('access.waitingDisclosure','Winning ends the wait only. Your credentials are still required.');panel.append(disclosure);
    const clock=document.createElement('p');clock.setAttribute('role','status');panel.append(clock);const challengeArea=document.createElement('div');panel.append(challengeArea);let roundTimer=null,closed=false;
    const clockTimer=setInterval(()=>{if(!panel.isConnected){clearInterval(clockTimer);if(roundTimer)clearInterval(roundTimer);closed=true;return;}clock.textContent=`${t('access.waitRemaining','Wait remaining')}: ${Math.ceil(controller.waiting(id)/1000)} ${t('access.seconds','Seconds')}`;if(!controller.waiting(id)){clearInterval(clockTimer);challengeArea.replaceChildren();clock.textContent=t('access.waitOver','The waiting period is over. Enter your credentials again.');}},250);
    const stop=()=>{closed=true;clearInterval(clockTimer);if(roundTimer)clearInterval(roundTimer);panel.remove();waitingClosers.delete(stop);};waitingClosers.add(stop);cleanups.push(stop);button(t('access.close','Close'),stop,panel);
    function next(){
      if(closed)return;if(roundTimer)clearInterval(roundTimer);challengeArea.replaceChildren();const challenge=controller.challengeWait(id,{schoolMode:Boolean(typeof services.schoolMode==='function'?services.schoolMode():services.schoolMode)});
      if(!challenge){challengeArea.textContent=t('access.clockOnly','The clock is the only remaining route for this waiting period.');return;}
      if(challenge.dishUnavailable){const unavailable=document.createElement('p');unavailable.textContent=t('access.dishUnavailable','The verified dish catalog is unavailable. This challenge starts with arithmetic.');challengeArea.append(unavailable);}
      const finish=value=>{if(closed)return;const won=controller.answerWait(id,challenge.nonce,value);challengeArea.replaceChildren();if(won){clock.textContent=t('access.waitOver','The waiting period is over. Enter your credentials again.');clearInterval(clockTimer);}else{const text=document.createElement('p');text.textContent=t('access.challengeWrong','Challenge expired or answer did not match.');challengeArea.append(text);button(t('access.nextChallenge','Try the next challenge'),next,challengeArea);}};
      if(challenge.rung==='dish'){const prompt=document.createElement('p');prompt.textContent=translate(challenge.question.prompt);challengeArea.append(prompt);challenge.question.choices.forEach((choice,index)=>button(translate(choice),()=>finish(index),challengeArea));}
      else if(challenge.rung==='sums'){const answers=challenge.question.map(({a,b})=>field(`${a} + ${b} =`,'number',challengeArea));button(t('access.submitAnswers','Submit answers'),()=>finish(answers.map(input=>input.value===''?null:Number(input.value))),challengeArea);}
      else {
        const prompt=document.createElement('p');prompt.textContent=t('access.hitMoles','Hit visible moles');challengeArea.append(prompt);const progress=document.createElement('p');progress.setAttribute('role','status');challengeArea.append(progress);const started=Date.now(),taps=[];const cells=Array.from({length:9},(_,cell)=>button(t('access.emptyCell','Empty cell'),()=>taps.push({cell,time:Date.now()-started}),challengeArea));
        const done=button(t('access.finishRound','Finish round'),()=>finish(taps),challengeArea);done.disabled=true;
        roundTimer=setInterval(()=>{const elapsed=Date.now()-started;for(let cell=0;cell<9;cell++){const active=challenge.question.some(mole=>mole.cell===cell&&elapsed>=mole.start&&elapsed<=mole.end);cells[cell].disabled=!active;cells[cell].textContent=`${cell+1}: ${active?t('access.mole','Mole'):t('access.emptyCell','Empty cell')}`;}progress.textContent=`${t('access.roundRemaining','Round remaining')}: ${Math.max(0,Math.ceil((challenge.duration-elapsed)/1000))} ${t('access.seconds','Seconds')}`;if(elapsed>=challenge.duration){clearInterval(roundTimer);done.disabled=false;}},60);
      }
    }next();
  }
  function openUnlock(id,remove=false){const panel=document.createElement('form');panel.setAttribute('aria-label',t('access.unlock','Unlock')+' '+id);const record=controller.describe(id);if(!record)return;
    let closed=false,busy=false;const origin=document.activeElement;
    const close=(cancelPending=true)=>{if(closed)return;closed=true;if(cancelPending)controller.cancel(id);Object.values(fields).forEach(input=>input.value='');panel.remove();origin?.focus?.();};
    const fields={};for(const factor of LOCK_POLICIES[record.policy])fields[factor]=field(factor==='password'?t('access.password','Password'):factor==='totp'?t('access.code','Current code'):'PIN',factor==='totp'?'text':'password',panel);
    if(fields.pin)keypad(fields.pin,panel);
    button(t('access.unlock','Unlock'),async()=>{if(closed||busy)return;busy=true;try{const pending=controller.unlock(id,Object.fromEntries(Object.entries(fields).map(([k,v])=>[k,v.value])));const generation=controller.generation(id);const ok=await pending;Object.values(fields).forEach(x=>x.value='');if(closed||controller.generation(id)!==generation)return;if(!ok){report(t('access.mismatch','The values did not match, or the waiting period is active.'));if(controller.waiting(id)&&!panel.querySelector('[data-wait-action]')){const action=button(t('access.tryLadder','Try the waiting ladder'),()=>openWaiting(id,panel),panel);action.dataset.waitAction='';}return;}if(remove){if(closed||controller.generation(id)!==generation)return;if(!await controller.remove(id,{expectedGeneration:generation}))return;}if(!closed){close(false);refreshLocks();}}catch(e){if(!closed)report(e);}finally{busy=false;}},panel);
    button(t('access.cancel','Cancel'),()=>close(),panel);panel.addEventListener('keydown',event=>{if(event.key==='Escape'){event.preventDefault();close();}});cleanups.push(()=>close());button(t('access.support','Support Tickets'),()=>support.hidden=false,panel);root.append(panel);fields[Object.keys(fields)[0]]?.focus();}
  const wizard=document.createElement('fieldset');root.append(wizard);const legend=document.createElement('legend');legend.textContent=t('access.create','Lock an element');wizard.append(legend);
  const target=field(t('access.target','Element identifier'),'text',wizard);const policy=document.createElement('select');policy.setAttribute('aria-label',t('access.policy','Credential policy'));for(const [key,factors]of Object.entries(LOCK_POLICIES)){const option=document.createElement('option');option.value=key;option.textContent=factors.join(' + ');policy.append(option);}wizard.append(policy);
  const pin=field('PIN','password',wizard),password=field(t('access.password','Password'),'password',wizard),otp=field(t('access.uri','Authenticator URI'),'password',wizard),code=field(t('access.code','Current code'),'text',wizard),duration=field(t('access.duration','Unlock minutes (0 means until closing)'),'number',wizard);duration.value='0';duration.min='0';duration.max='1440';
  const pinPad=keypad(pin,wizard);function updatePolicy(){const factors=LOCK_POLICIES[policy.value];pin.parentElement.hidden=!factors.includes('pin');pinPad.hidden=!factors.includes('pin');password.parentElement.hidden=!factors.includes('password');otp.parentElement.hidden=code.parentElement.hidden=!factors.includes('totp');}policy.addEventListener('change',updatePolicy);updatePolicy();
  let lockOrigin=null;function openLockWizard(id,origin){target.value=id;lockOrigin=origin||document.activeElement;wizard.hidden=false;wizard.scrollIntoView?.({block:'nearest'});policy.focus();}
  button(t('access.cancel','Cancel'),()=>{wizard.hidden=true;lockOrigin?.focus?.();},wizard);
  const consent=document.createElement('label');const check=document.createElement('input');check.type='checkbox';consent.append(check,document.createTextNode(t('access.consent','I understand the local reset route and convenience-only protection.')));wizard.append(consent);
  button(t('access.save','Create lock'),async()=>{try{if(!check.checked)throw new Error(t('access.confirm','Confirm the disclosure first.'));if(!services.credentialStore)throw new Error(t('access.vault','The local credential vault is unavailable.'));await controller.set(target.value,policy.value,{pin:pin.value,password:password.value,totp:otp.value?parseOtpUri(otp.value):null,code:code.value},duration.value);for(const input of [pin,password,otp,code])input.value='';services.history?.record?.({action:'lock-created',target:target.value});refreshLocks();}catch(e){report(e);}},wizard);
  const auth=document.createElement('fieldset');root.append(auth);const al=document.createElement('legend');al.textContent=t('access.authenticator','Authenticator');auth.append(al);
  const qrStatus=document.createElement('p');qrStatus.setAttribute('role','status');qrStatus.textContent=t('access.qrLocal','QR generation and decoding run locally. Reveal registration information only in a private setting.');auth.append(qrStatus);
  const uri=field(t('access.uri','Authenticator URI'),'password',auth),secret=field(t('access.secret','Manual base32 secret'),'password',auth),issuer=field(t('access.issuer','Issuer'),'text',auth),account=field(t('access.account','Account'),'text',auth),group=field(t('access.group','Group'),'text',auth),algorithm=document.createElement('select');algorithm.setAttribute('aria-label',t('access.algorithm','Algorithm'));for(const value of ['SHA1','SHA256','SHA512']){const option=document.createElement('option');option.value=option.textContent=value;algorithm.append(option);}auth.append(algorithm);
  const digits=field(t('access.digits','Digits'),'number',auth),period=field(t('access.period','Period in seconds'),'number',auth),confirmation=field(t('access.code','Current code'),'text',auth);digits.value='6';digits.min='6';digits.max='8';period.value='30';period.min='1';period.max='86400';
  const qrPreview=document.createElement('div');qrPreview.hidden=true;auth.append(qrPreview);let cameraStream=null,cameraTimer=null,cameraGeneration=0;const camera=document.createElement('video');camera.autoplay=true;camera.muted=true;camera.playsInline=true;camera.hidden=true;auth.append(camera);
  function stopCamera(){cameraGeneration++;if(cameraTimer)clearTimeout(cameraTimer);cameraTimer=null;cameraStream?.getTracks().forEach(track=>track.stop());cameraStream=null;camera.srcObject=null;camera.hidden=true;}
  cleanups.push(stopCamera);
  function importRegistration(value){parseOtpUri(value);uri.value=value;qrPreview.replaceChildren();qrPreview.hidden=true;qrStatus.textContent=t('access.qrImported','Registration imported locally. Enter its current code to confirm.');stopCamera();confirmation.focus();}
  button(t('access.generateSecret','Generate registration secret'),()=>{const random=crypto.getRandomValues(new Uint8Array(20));let bits=0,acc=0,value='';for(const byte of random){acc=(acc<<8)|byte;bits+=8;while(bits>=5){bits-=5;value+='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'[(acc>>bits)&31];}}secret.value=value;uri.value='';qrPreview.replaceChildren();qrPreview.hidden=true;},auth);
  button(t('access.revealQr','Reveal registration QR and manual secret'),()=>{try{const entry=uri.value?parseOtpUri(uri.value):{secret:secret.value,issuer:issuer.value,account:account.value,algorithm:algorithm.value,digits:Number(digits.value),period:Number(period.value)};validateOtp(entry);qrPreview.innerHTML=qrSvg(otpUri(entry));qrPreview.querySelector('svg').setAttribute('aria-label',t('access.qrLabel','Authenticator registration QR code'));const manual=document.createElement('p');manual.textContent=`${entry.secret.match(/.{1,4}/g)?.join(' ')} | ${entry.algorithm} | ${entry.digits} | ${entry.period} ${t('access.seconds','Seconds')}`;qrPreview.append(manual);qrPreview.hidden=false;}catch(e){report(e);}},auth);
  button(t('access.hideQr','Hide registration details'),()=>{qrPreview.replaceChildren();qrPreview.hidden=true;},auth);
  const imageInput=document.createElement('input');imageInput.type='file';imageInput.accept='image/png,image/jpeg,image/webp,image/gif';imageInput.setAttribute('aria-label',t('access.qrImage','Import QR image'));auth.append(imageInput);imageInput.addEventListener('change',async()=>{try{if(imageInput.files?.[0])importRegistration(await decodeQrBlob(imageInput.files[0],document));}catch(e){report(e);}finally{imageInput.value='';}});
  button(t('access.qrClipboard','Read QR image from clipboard'),async()=>{try{if(!navigator.clipboard?.read)throw new Error(t('access.clipboardUnavailable','Clipboard image reading is unavailable.'));const items=await navigator.clipboard.read();for(const item of items){const type=item.types.find(type=>['image/png','image/jpeg','image/webp'].includes(type));if(type){importRegistration(await decodeQrBlob(await item.getType(type),document));return;}}throw new Error(t('access.noQrImage','The clipboard has no supported image.'));}catch(e){report(e);}},auth);
  button(t('access.qrCamera','Scan QR with camera'),async()=>{try{stopCamera();const generation=cameraGeneration;if(!navigator.mediaDevices?.getUserMedia)throw new Error(t('access.cameraUnavailable','Camera access is unavailable.'));const stream=await navigator.mediaDevices.getUserMedia({audio:false,video:{width:{ideal:640,max:1280},height:{ideal:480,max:720},facingMode:'environment'}});if(generation!==cameraGeneration){stream.getTracks().forEach(track=>track.stop());return;}cameraStream=stream;camera.srcObject=cameraStream;camera.hidden=false;await camera.play();const expires=Date.now()+60000;const scan=()=>{if(!cameraStream)return;if(Date.now()>expires){stopCamera();qrStatus.textContent=t('access.cameraExpired','Camera scan timed out.');return;}if(camera.videoWidth&&camera.videoHeight){const canvas=document.createElement('canvas');canvas.width=camera.videoWidth;canvas.height=camera.videoHeight;const context=canvas.getContext('2d',{willReadFrequently:true});context.drawImage(camera,0,0);try{importRegistration(decodeQrPixels(context.getImageData(0,0,canvas.width,canvas.height).data,canvas.width,canvas.height));return;}catch{}}cameraTimer=setTimeout(scan,300);};scan();}catch(e){stopCamera();report(e);}},auth);
  button(t('access.stopCamera','Stop camera'),stopCamera,auth);
  const search=field(t('access.search','Search authenticators'),'search',auth);const authList=document.createElement('div');auth.append(authList);let editingId=null;
  async function persistEntries(){await services.credentialStore.set('authenticator:index:v1',[...entries.keys()]);}
  async function history(action,id){await services.history?.record?.({action,target:id});}
  async function refreshCodes(){for(const [id,entry]of entries){const row=authList.querySelector(`[data-entry-id="${id}"]`);if(row){const current=await totp(entry);const region=row.querySelector('output');if(region.textContent!==current)region.textContent=current;row.querySelector('small').textContent=` ${entry.period-Math.floor(Date.now()/1000)%entry.period}s`;row.querySelector('[data-next]').textContent=t('access.next','Next code')+': '+await totp(entry,Date.now()+entry.period*1000);}}}
  function renderEntries(){authList.replaceChildren();
    for(const [id,entry]of entries){const label=`${entry.issuer}: ${entry.account} ${entry.group||''}`;if(search.value&&!label.toLocaleLowerCase().includes(search.value.toLocaleLowerCase()))continue;
      const row=document.createElement('div');row.dataset.entryId=id;const name=document.createElement('strong');name.textContent=label;const codeRegion=document.createElement('output');codeRegion.setAttribute('aria-live','polite');const next=document.createElement('span');next.dataset.next='';row.append(name,document.createTextNode(' '),codeRegion,document.createElement('small'),next);
      button(t('access.copyCode','Copy code'),async()=>{try{await navigator.clipboard.writeText(await totp(entry));}catch(e){report(e);}},row);
      button(t('access.edit','Edit'),()=>{editingId=id;issuer.value=entry.issuer;account.value=entry.account;group.value=entry.group||'';algorithm.value=entry.algorithm;digits.value=entry.digits;period.value=entry.period;secret.value='';uri.value='';confirmation.value='';issuer.focus();},row);
      for(const [label,direction]of [[t('access.up','Move up'),-1],[t('access.down','Move down'),1]])button(label,async()=>{try{const list=[...entries];const at=list.findIndex(x=>x[0]===id),to=at+direction;if(to<0||to>=list.length)return;[list[at],list[to]]=[list[to],list[at]];entries.clear();list.forEach(([key,value])=>entries.set(key,value));await persistEntries();await history('authenticator-reordered',id);renderEntries();}catch(e){report(e);}},row);
      button(t('access.remove','Remove'),async()=>{try{await services.credentialStore.delete(`authenticator:${id}`);entries.delete(id);await persistEntries();await history('authenticator-removed',id);renderEntries();}catch(e){report(e);}},row);authList.append(row);
    }refreshCodes().catch(report);
  }
  search.addEventListener('input',renderEntries);if(services.attachSearch){const off=services.attachSearch(search,authList);if(typeof off==='function')cleanups.push(off);}
  button(t('access.register','Save authenticator'),async()=>{try{if(!services.credentialStore)throw new Error(t('access.vault','The local credential vault is unavailable.'));const previous=editingId?entries.get(editingId):null;const entry=uri.value?parseOtpUri(uri.value):{secret:secret.value||previous?.secret||'',issuer:issuer.value,account:account.value,algorithm:algorithm.value,digits:Number(digits.value),period:Number(period.value)};entry.group=group.value;validateOtp(entry);if(!await verifyTotp(entry,confirmation.value))throw new Error(t('access.mismatch','The code did not match.'));const id=editingId||randomId();await services.credentialStore.set(`authenticator:${id}`,entry);entries.set(id,entry);await persistEntries();await history(editingId?'authenticator-updated':'authenticator-created',id);editingId=null;for(const input of [uri,secret,confirmation,issuer,account,group])input.value='';qrPreview.replaceChildren();qrPreview.hidden=true;stopCamera();renderEntries();}catch(e){report(e);}},auth);
  button(t('access.cancelEdit','Cancel editing'),()=>{editingId=null;for(const input of [uri,secret,confirmation,issuer,account,group])input.value='';},auth);
  async function loadAuthenticators(){if(!services.credentialStore)return;const ids=await services.credentialStore.get('authenticator:index:v1')||[];for(const id of ids){const entry=await services.credentialStore.get(`authenticator:${id}`);if(entry){validateOtp(entry);entries.set(id,entry);}}renderEntries();}
  loadAuthenticators().catch(report);
  const support=document.createElement('fieldset');root.append(support);const sl=document.createElement('legend');sl.textContent=t('access.support','Support Tickets');support.append(sl);const disclosure=document.createElement('p');disclosure.textContent=translate('Nothing is sent anywhere. No ticket exists outside this machine, no network request is made, no data is collected, and nobody is reading it.');support.append(disclosure);const category=field(t('access.category','Category'),'text',support),description=field(t('access.description','Description'),'text',support);const ticketList=document.createElement('div');support.append(ticketList);
  const ticketSearch=field(t('access.ticketSearch','Search local tickets'),'search',support);
  const ticketStorage=services.storage||globalThis.localStorage;const ticketKey='material-file-encryptor.local-support-tickets.v1';let editingTicket=null;
  function saveTickets(){try{ticketStorage?.setItem(ticketKey,JSON.stringify(tickets));}catch{report(t('access.ticketStorageUnavailable','Local ticket storage is unavailable.'));}}
  function renderTickets(){ticketList.replaceChildren();for(const ticket of tickets){if(!`${ticket.category} ${ticket.description}`.toLowerCase().includes(ticketSearch.value.toLowerCase()))continue;const row=document.createElement('div');const text=document.createElement('p');text.textContent=`${ticket.id}: ${ticket.category}. ${ticket.description}. ${translate(ticket.status,true)}`;row.append(text);button(t('access.advance','Advance local ticket'),()=>{ticket.stage=Math.min(2,ticket.stage+1);ticket.status=['Created locally','Reviewed by the local automated desk','Resolved: open the application data folder to reset local data'][ticket.stage];saveTickets();renderTickets();},row);button(t('access.edit','Edit'),()=>{category.value=ticket.category;description.value=ticket.description;editingTicket=ticket;description.focus();},row);button(t('access.remove','Remove'),()=>{tickets.splice(tickets.indexOf(ticket),1);saveTickets();renderTickets();},row);ticketList.append(row);}}
  ticketSearch.addEventListener('input',renderTickets);if(services.attachSearch){const off=services.attachSearch(ticketSearch,ticketList);if(typeof off==='function')cleanups.push(off);}
  try{const saved=ticketStorage?.getItem(ticketKey);if(saved&&saved.length<=262144){const parsed=JSON.parse(saved);if(Array.isArray(parsed))for(const ticket of parsed.slice(0,100))if(ticket&&typeof ticket.id==='string'&&typeof ticket.category==='string'&&typeof ticket.description==='string'&&typeof ticket.status==='string'&&[0,1,2].includes(ticket.stage))tickets.push({id:ticket.id.slice(0,64),category:ticket.category.slice(0,100),description:ticket.description.slice(0,2000),status:ticket.status.slice(0,120),stage:ticket.stage});}}catch{report(t('access.ticketStorageInvalid','Local ticket data could not be read.'));}renderTickets();
  button(t('access.ticket','Create local ticket'),()=>{if(tickets.length>=100&&!editingTicket){report(t('access.ticketLimit','Remove a local ticket before creating another (limit 100).'));return;}const ticket={id:randomId(),category:category.value.slice(0,100),description:description.value.slice(0,2000),status:'Created locally',stage:0};if(editingTicket){editingTicket.category=ticket.category;editingTicket.description=ticket.description;editingTicket=null;}else tickets.push(ticket);saveTickets();renderTickets();description.value='';},support);
  const path=document.createElement('p');path.textContent=services.dataPath||t('access.pathUnavailable','Application data folder unavailable.');support.append(path);button(t('access.openFolder','Open application data folder'),async()=>{try{if(!services.openDataFolder)throw new Error(t('access.pathUnavailable','Application data folder unavailable.'));await services.openDataFolder();}catch(e){report(e);}},support);
  const timer=setInterval(()=>refreshCodes().catch(report),1000);cleanups.push(()=>clearInterval(timer));
  function refresh(){
    for(const close of [...waitingClosers])close();
    const previous=new Map(renderedTranslations);renderedTranslations.clear();
    const replace=value=>{const original=previous.get(value);return original?t(original.key,original.fallback,original.options):value;};
    const walker=document.createTreeWalker(root,4);let text;
    while((text=walker.nextNode())){if(!text.parentElement?.closest('[data-entry-id]'))text.nodeValue=replace(text.nodeValue);}
    for(const element of [root,...root.querySelectorAll('*')])for(const attribute of ['aria-label','title','placeholder'])if(element.hasAttribute(attribute))element.setAttribute(attribute,replace(element.getAttribute(attribute)));
    refreshLocks();renderEntries();renderTickets();updatePolicy();return root;
  }
  return {controller,refresh,refreshLocks,openUnlock,openLockWizard,loadAuthenticators,encryptPrivateCache,decryptPrivateCache,logout:endSession,get authenticated(){return profileSession.authenticated;},async load(ids){await controller.load(ids);refreshLocks();},guard:(id,callback,...args)=>controller.run(id,callback,...args),bind(rootNode){const dispose=controller.intercept(rootNode);cleanups.push(dispose);return dispose;},destroy(){endSession();cleanups.forEach(f=>f());entries.clear();root.remove();}};
}
