import {LockController,LOCK_POLICIES} from './locks.js';
import {parseOtpUri,validateOtp,totp,verifyTotp,randomId,passwordVerifier,verifyPassword,deriveCacheKey,seal,unseal} from './crypto.js';
export * from './crypto.js';
export * from './locks.js';

export function mountAccess(container,services={}) {
  const document=container.ownerDocument;const t=(key,fallback)=>services.t?.(key)||fallback;const cleanups=[];const entries=new Map();const tickets=[];
  const controller=new LockController({store:services.credentialStore,onBlocked:id=>{services.notify?.(t('access.locked','This element is locked.'));openUnlock(id);}});
  const root=document.createElement('section');root.className='access-workspace';root.setAttribute('aria-label',t('access.title','Local access'));container.append(root);
  const heading=document.createElement('h2');heading.textContent=t('access.title','Local access');root.append(heading);
  const notice=document.createElement('p');notice.textContent=t('access.disclosure','These local convenience locks do not encrypt files. Reset them by clearing this application’s local data.');root.append(notice);
  function button(label,action,parent=root){const b=document.createElement('button');b.type='button';b.textContent=label;b.addEventListener('click',action);parent.append(b);return b;}
  function field(label,type='text',parent=root){const wrap=document.createElement('label');wrap.textContent=label;const input=document.createElement('input');input.type=type;input.autocomplete='off';wrap.append(input);button(t('access.clear','Clear')+' '+label,()=>{input.value='';input.dispatchEvent(new Event('input',{bubbles:true}));input.focus();},wrap);parent.append(wrap);return input;}
  function keypad(input,parent){const pad=document.createElement('div');pad.setAttribute('role','group');pad.setAttribute('aria-label',t('access.keypad','PIN keypad'));for(const digit of '1234567890')button(digit,()=>{input.value+=digit;input.dispatchEvent(new Event('input',{bubbles:true}));input.focus();},pad);button(t('access.backspace','Backspace'),()=>{input.value=input.value.slice(0,-1);input.focus();},pad);parent.append(pad);return pad;}
  const output=document.createElement('p');output.setAttribute('role','status');root.append(output);
  const report=error=>{output.textContent=error?.message||String(error);};
  let privateKey=null;let profileRecord=null;let profileFailures=0;let profileWaitUntil=0;let profileLevel=0;
  const profile=document.createElement('fieldset');root.append(profile);const pl=document.createElement('legend');pl.textContent=t('access.profile','Local profile');profile.append(pl);
  const profilePassword=field(t('access.profilePassword','Profile password'),'password',profile);
  const profileStatus=document.createElement('p');profileStatus.setAttribute('role','status');profileStatus.textContent=t('access.profileLocked','Private cache is locked.');profile.append(profileStatus);
  function endSession(){privateKey=null;profilePassword.value='';profileStatus.textContent=t('access.profileLocked','Private cache is locked.');services.onAuthenticatedChange?.(false);}
  async function unlockProfile(create=false){
    try {
      if(Date.now()<profileWaitUntil)throw new Error(t('access.wait','Wait before trying another profile password.'));
      if(!services.credentialStore)throw new Error(t('access.vault','The local credential vault is unavailable.'));
      profileRecord=await services.credentialStore.get('local-profile:v1');
      if(create){if(profileRecord)throw new Error(t('access.profileExists','A local profile already exists. Unlock it instead.'));profileRecord=await passwordVerifier(profilePassword.value);await services.credentialStore.set('local-profile:v1',profileRecord);}
      if(!profileRecord||!await verifyPassword(profilePassword.value,profileRecord)){if(++profileFailures>=5){profileLevel++;profileWaitUntil=Date.now()+Math.min(3600000,30000*2**(profileLevel-1));profileFailures=0;}throw new Error(t('access.mismatch','The password did not match.'));}
      const candidate=await deriveCacheKey(profilePassword.value,profileRecord.salt);profilePassword.value='';privateKey=candidate;profileFailures=0;profileLevel=0;profileStatus.textContent=t('access.profileUnlocked','Private cache is unlocked until logout or application close.');services.onAuthenticatedChange?.(true);
    }catch(e){profilePassword.value='';report(e);}
  }
  button(t('access.setupProfile','Set up local profile'),()=>unlockProfile(true),profile);
  button(t('access.unlockProfile','Unlock local profile'),()=>unlockProfile(false),profile);
  button(t('access.logout','Log out'),endSession,profile);
  async function encryptPrivateCache(value,identity='personal-vocabulary'){if(!privateKey)throw new Error('Unlock the local profile first.');return seal(value,privateKey,identity);}
  async function decryptPrivateCache(value,identity='personal-vocabulary'){if(!privateKey)throw new Error('Unlock the local profile first.');return unseal(value,privateKey,identity);}
  const lockList=document.createElement('div');root.append(lockList);
  function refreshLocks(){lockList.replaceChildren();for(const record of controller.list()){const row=document.createElement('div');row.textContent=`${record.id}: ${record.policy}`;button(t('access.unlock','Unlock'),()=>openUnlock(record.id),row);button(t('access.relock','Lock again'),()=>{controller.lock(record.id);output.textContent=t('access.locked','Locked');},row);button(t('access.remove','Remove lock'),()=>openUnlock(record.id,true),row);lockList.append(row);}}
  function openUnlock(id,remove=false){const panel=document.createElement('form');panel.setAttribute('aria-label',t('access.unlock','Unlock')+' '+id);const record=controller.describe(id);if(!record)return;
    const fields={};for(const factor of LOCK_POLICIES[record.policy])fields[factor]=field(factor,factor==='totp'?'text':'password',panel);
    if(fields.pin)keypad(fields.pin,panel);
    button(t('access.unlock','Unlock'),async()=>{try{const ok=await controller.unlock(id,Object.fromEntries(Object.entries(fields).map(([k,v])=>[k,v.value])));Object.values(fields).forEach(x=>x.value='');if(!ok){report(t('access.mismatch','The values did not match, or the waiting period is active.'));return;}if(remove)await controller.remove(id);panel.remove();refreshLocks();}catch(e){report(e);}},panel);
    button(t('access.cancel','Cancel'),()=>panel.remove(),panel);button(t('access.support','Support Tickets'),()=>support.hidden=false,panel);root.append(panel);fields[Object.keys(fields)[0]]?.focus();}
  const wizard=document.createElement('fieldset');root.append(wizard);const legend=document.createElement('legend');legend.textContent=t('access.create','Lock an element');wizard.append(legend);
  const target=field(t('access.target','Element identifier'),'text',wizard);const policy=document.createElement('select');policy.setAttribute('aria-label',t('access.policy','Credential policy'));for(const [key,factors]of Object.entries(LOCK_POLICIES)){const option=document.createElement('option');option.value=key;option.textContent=factors.join(' + ');policy.append(option);}wizard.append(policy);
  const pin=field('PIN','password',wizard),password=field(t('access.password','Password'),'password',wizard),otp=field(t('access.uri','Authenticator URI'),'password',wizard),code=field(t('access.code','Current code'),'text',wizard),duration=field(t('access.duration','Unlock minutes (0 means until closing)'),'number',wizard);duration.value='0';duration.min='0';duration.max='1440';
  const pinPad=keypad(pin,wizard);function updatePolicy(){const factors=LOCK_POLICIES[policy.value];pin.parentElement.hidden=!factors.includes('pin');pinPad.hidden=!factors.includes('pin');password.parentElement.hidden=!factors.includes('password');otp.parentElement.hidden=code.parentElement.hidden=!factors.includes('totp');}policy.addEventListener('change',updatePolicy);updatePolicy();
  let lockOrigin=null;function openLockWizard(id,origin){target.value=id;lockOrigin=origin||document.activeElement;wizard.hidden=false;wizard.scrollIntoView?.({block:'nearest'});policy.focus();}
  button(t('access.cancel','Cancel'),()=>{wizard.hidden=true;lockOrigin?.focus?.();},wizard);
  const consent=document.createElement('label');const check=document.createElement('input');check.type='checkbox';consent.append(check,document.createTextNode(t('access.consent','I understand the local reset route and convenience-only protection.')));wizard.append(consent);
  button(t('access.save','Create lock'),async()=>{try{if(!check.checked)throw new Error(t('access.confirm','Confirm the disclosure first.'));if(!services.credentialStore)throw new Error(t('access.vault','The local credential vault is unavailable.'));await controller.set(target.value,policy.value,{pin:pin.value,password:password.value,totp:otp.value?parseOtpUri(otp.value):null,code:code.value},duration.value);for(const input of [pin,password,otp,code])input.value='';services.history?.record?.({action:'lock-created',target:target.value});refreshLocks();}catch(e){report(e);}},wizard);
  const auth=document.createElement('fieldset');root.append(auth);const al=document.createElement('legend');al.textContent=t('access.authenticator','Authenticator');auth.append(al);
  const unavailable=document.createElement('p');unavailable.textContent=t('access.qrUnavailable','QR rendering, image import, clipboard image scanning and camera scanning are unavailable in this build. Use a registration URI or manual entry.');auth.append(unavailable);
  const uri=field(t('access.uri','Authenticator URI'),'password',auth),secret=field(t('access.secret','Manual base32 secret'),'password',auth),issuer=field(t('access.issuer','Issuer'),'text',auth),account=field(t('access.account','Account'),'text',auth),group=field(t('access.group','Group'),'text',auth),algorithm=document.createElement('select');algorithm.setAttribute('aria-label',t('access.algorithm','Algorithm'));for(const value of ['SHA1','SHA256','SHA512']){const option=document.createElement('option');option.value=option.textContent=value;algorithm.append(option);}auth.append(algorithm);
  const digits=field(t('access.digits','Digits'),'number',auth),period=field(t('access.period','Period in seconds'),'number',auth),confirmation=field(t('access.code','Current code'),'text',auth);digits.value='6';digits.min='6';digits.max='8';period.value='30';period.min='1';period.max='86400';
  const search=field(t('access.search','Search authenticators'),'search',auth);const regexLabel=document.createElement('label');const regex=document.createElement('input');regex.type='checkbox';regexLabel.append(regex,document.createTextNode(t('access.regex','Regular expression')));auth.append(regexLabel);const authList=document.createElement('div');auth.append(authList);let editingId=null;
  async function persistEntries(){await services.credentialStore.set('authenticator:index:v1',[...entries.keys()]);}
  function history(action,id){services.history?.record?.({action,target:id});}
  async function refreshCodes(){for(const [id,entry]of entries){const row=authList.querySelector(`[data-entry-id="${id}"]`);if(row){const current=await totp(entry);const region=row.querySelector('output');if(region.textContent!==current)region.textContent=current;row.querySelector('small').textContent=` ${entry.period-Math.floor(Date.now()/1000)%entry.period}s`;row.querySelector('[data-next]').textContent=t('access.next','Next code')+': '+await totp(entry,Date.now()+entry.period*1000);}}}
  function renderEntries(){authList.replaceChildren();let matcher;try{matcher=regex.checked?new RegExp(search.value,'iu'):null;search.setCustomValidity('');}catch{search.setCustomValidity(t('access.invalidRegex','Invalid regular expression'));search.reportValidity();return;}
    for(const [id,entry]of entries){const label=`${entry.issuer}: ${entry.account} ${entry.group||''}`;if(search.value&&!(matcher?matcher.test(label):label.toLocaleLowerCase().includes(search.value.toLocaleLowerCase())))continue;
      const row=document.createElement('div');row.dataset.entryId=id;const name=document.createElement('strong');name.textContent=label;const codeRegion=document.createElement('output');codeRegion.setAttribute('aria-live','polite');const next=document.createElement('span');next.dataset.next='';row.append(name,document.createTextNode(' '),codeRegion,document.createElement('small'),next);
      button(t('access.copyCode','Copy code'),async()=>{try{await navigator.clipboard.writeText(await totp(entry));}catch(e){report(e);}},row);
      button(t('access.edit','Edit'),()=>{editingId=id;issuer.value=entry.issuer;account.value=entry.account;group.value=entry.group||'';algorithm.value=entry.algorithm;digits.value=entry.digits;period.value=entry.period;secret.value='';uri.value='';confirmation.value='';issuer.focus();},row);
      for(const [label,direction]of [[t('access.up','Move up'),-1],[t('access.down','Move down'),1]])button(label,async()=>{try{const list=[...entries];const at=list.findIndex(x=>x[0]===id),to=at+direction;if(to<0||to>=list.length)return;[list[at],list[to]]=[list[to],list[at]];entries.clear();list.forEach(([key,value])=>entries.set(key,value));await persistEntries();history('authenticator-reordered',id);renderEntries();}catch(e){report(e);}},row);
      button(t('access.remove','Remove'),async()=>{try{await services.credentialStore.delete(`authenticator:${id}`);entries.delete(id);await persistEntries();history('authenticator-removed',id);renderEntries();}catch(e){report(e);}},row);authList.append(row);
    }refreshCodes().catch(report);
  }
  search.addEventListener('input',renderEntries);regex.addEventListener('change',renderEntries);
  button(t('access.register','Save authenticator'),async()=>{try{if(!services.credentialStore)throw new Error(t('access.vault','The local credential vault is unavailable.'));const previous=editingId?entries.get(editingId):null;const entry=uri.value?parseOtpUri(uri.value):{secret:secret.value||previous?.secret||'',issuer:issuer.value,account:account.value,algorithm:algorithm.value,digits:Number(digits.value),period:Number(period.value)};entry.group=group.value;validateOtp(entry);if(!await verifyTotp(entry,confirmation.value))throw new Error(t('access.mismatch','The code did not match.'));const id=editingId||randomId();await services.credentialStore.set(`authenticator:${id}`,entry);entries.set(id,entry);await persistEntries();history(editingId?'authenticator-updated':'authenticator-created',id);editingId=null;for(const input of [uri,secret,confirmation,issuer,account,group])input.value='';renderEntries();}catch(e){report(e);}},auth);
  button(t('access.cancelEdit','Cancel editing'),()=>{editingId=null;for(const input of [uri,secret,confirmation,issuer,account,group])input.value='';},auth);
  async function loadAuthenticators(){if(!services.credentialStore)return;const ids=await services.credentialStore.get('authenticator:index:v1')||[];for(const id of ids){const entry=await services.credentialStore.get(`authenticator:${id}`);if(entry){validateOtp(entry);entries.set(id,entry);}}renderEntries();}
  loadAuthenticators().catch(report);
  const support=document.createElement('fieldset');root.append(support);const sl=document.createElement('legend');sl.textContent=t('access.support','Support Tickets');support.append(sl);const disclosure=document.createElement('p');disclosure.textContent='Nothing is sent anywhere. No ticket exists outside this machine, no network request is made, no data is collected, and nobody is reading it.';support.append(disclosure);const category=field(t('access.category','Category'),'text',support),description=field(t('access.description','Description'),'text',support);const ticketList=document.createElement('div');support.append(ticketList);
  const ticketSearch=field(t('access.ticketSearch','Search local tickets'),'search',support);
  function renderTickets(){ticketList.replaceChildren();for(const ticket of tickets){if(!`${ticket.category} ${ticket.description}`.toLowerCase().includes(ticketSearch.value.toLowerCase()))continue;const row=document.createElement('div');const text=document.createElement('p');text.textContent=`${ticket.id}: ${ticket.category}. ${ticket.description}. ${ticket.status}`;row.append(text);button(t('access.advance','Advance local ticket'),()=>{ticket.stage=Math.min(2,ticket.stage+1);ticket.status=['Created locally','Reviewed by the local automated desk','Resolved: open the application data folder to reset local data'][ticket.stage];renderTickets();},row);button(t('access.remove','Remove'),()=>{tickets.splice(tickets.indexOf(ticket),1);renderTickets();},row);ticketList.append(row);}}
  ticketSearch.addEventListener('input',renderTickets);
  button(t('access.ticket','Create local ticket'),()=>{const ticket={id:randomId(),category:category.value,description:description.value,status:'Created locally',stage:0};tickets.push(ticket);renderTickets();description.value='';},support);
  const path=document.createElement('p');path.textContent=services.dataPath||t('access.pathUnavailable','Application data folder unavailable.');support.append(path);button(t('access.openFolder','Open application data folder'),async()=>{try{if(!services.openDataFolder)throw new Error(t('access.pathUnavailable','Application data folder unavailable.'));await services.openDataFolder();}catch(e){report(e);}},support);
  const timer=setInterval(()=>refreshCodes().catch(report),1000);cleanups.push(()=>clearInterval(timer));
  return {controller,refreshLocks,openUnlock,openLockWizard,loadAuthenticators,encryptPrivateCache,decryptPrivateCache,logout:endSession,get authenticated(){return !!privateKey;},async load(ids){await controller.load(ids);refreshLocks();},guard:(id,callback,...args)=>controller.run(id,callback,...args),bind(rootNode){const dispose=controller.intercept(rootNode);cleanups.push(dispose);return dispose;},destroy(){endSession();cleanups.forEach(f=>f());entries.clear();root.remove();}};
}
